### ISSUE TITLE
Creating query parameters with same name.

### ISSUE THREAD

**Issue by j-nguyen** [amitshekhariitbhu/Fast-Android-Networking#101]
Hi, I'm using the USDA API, where the URL parameter name gets called again and again.

Ex:

https://api.nal.usda.gov/ndb/nutrients/?format=json&api_key=DEMO_KEY&nutrients=205&nutrients=204&nutrients=208&nutrients=269&ndbno=01009

Is there a way I can use the nutrients key value over and over again with addQueryParameter()?

**Comment by amitshekhariitbhu** [comment]
As of now, there is no way to do so as this is the first time, I came to know about this. Anyway, you can create that by building the Url like above.
I will think on this for adding this feature in new release.

**Comment by j-nguyen** [comment]
Thanks for the heads up. Very much appreciated! Love the work you're doing
