### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by Elessawy** [amitshekhariitbhu/Fast-Android-Networking#103]
How to dissaple SSL verification

**Comment by amitshekhariitbhu** [comment]
Refer this as of now, may we can add this as a feature in new release.
http://stackoverflow.com/questions/25509296/trusting-all-certificates-with-okhttp

**Comment by Elessawy** [comment]
where should I add this method please?

**Comment by amitshekhariitbhu** [comment]
Refer the below link:
https://amitshekhariitbhu.github.io/Fast-Android-Networking/custom_okHttpClient.html

**Comment by Elessawy** [comment]
Thanks Amitshekhariitbhu. Keep going!

**Comment by hirenpatelazilen** [comment]
@amitshekhariitbhu , Appreciate your effort done so far for this awesome library.

I have one question for you: What I have to do for enabling SSL verification(.p12 certification) for HTTPS request?

Please let me know for the same.

Thanks.

**Comment by amitshekhariitbhu** [comment]
@hirenpatelazilen Thanks. By default, it is enabled. but for customization refer this [link](https://github.com/square/okhttp/wiki/HTTPS)

**Comment by hirenpatelazilen** [comment]
@amitshekhariitbhu , Thanks for your prompt response.

I am using your  compile **'com.amitshekhar.android:rx2-android-networking:1.0.0'**. So for SSL do I need to use **AndroidNetworking** class for okHttp? or **Rx2AndroidNetworking** class has initialisation method same as  **AndroidNetworking** class?

Thanks

**Comment by amitshekhariitbhu** [comment]
@hirenpatelazilen use the same `AndroidNetworking` for that also.

Thanks
Amit Shekhar

**Comment by hirenpatelazilen** [comment]
So for setting SSL I need to user **AndroidNetworking** and for API calling I need to use **Rx2AndroidNetworking**. Can you please correct me if I wrong?

Thanks

**Comment by amitshekhariitbhu** [comment]
@hirenpatelazilen You are correct. Initialization point is single that is `AndroidNetworking`

**Comment by hirenpatelazilen** [comment]
Ok thanks @amitshekhariitbhu .

**Comment by hirenpatelazilen** [comment]
@amitshekhariitbhu, Need one help from you.

I am using p12 certificate, now I am not using `AndroidNetworking.initialize(this, client);` even though its working fine.

How it's possible that **https** can work without p12 certificate. If I use HttpClient (Old pattern) than it must required to use p12 certificate.

I am confused here so can you please help me on this?

Regards,
Hiren Patel
