### ISSUE TITLE
Effective Download Library?

### ISSUE THREAD

**Issue by ohenepee** [amitshekhariitbhu/Fast-Android-Networking#105]
Will downloads be resumed if file already exists and its size if of course lesser than the response's content-length?

Does downloads use multiple threads (multi-threaded downloads) ?

**Comment by amitshekhariitbhu** [comment]
Resume download is not supported, new version will have this feature. 
Currently this library supports multi threads.

**Comment by ohenepee** [comment]
Wow! Okay... great on the multi-threading... how many threads are used per file download, and how can I manipulate the value?

**Comment by amitshekhariitbhu** [comment]
As of now these are not customisable and it decides on the basis of core.

**Comment by amitshekhariitbhu** [comment]
I have created new library for pause and resume support. Check [PRDownloader](https://github.com/MindorksOpenSource/PRDownloader)
