### ISSUE TITLE
Upload method not working 

### ISSUE THREAD

**Issue by geniusforapp** [amitshekhariitbhu/Fast-Android-Networking#106]
AndroidNetworking.upload(getString(R.string.base_url) + getString(R.string.account) + "/" + getString(R.string.image))
                    .addMultipartFile("profile_image", new File(filePath))
                    .addHeaders(Headers.BaseHeader.getHeaders())
                    .addMultipartParameter("customer_id", userId)
                    .setTag("updateProfileImage")
                    .setPriority(Priority.HIGH)
                    .build()
                    .setUploadProgressListener(new UploadProgressListener() {
                        @Override
                        public void onProgress(long bytesUploaded, long totalBytes) {
                            imageView.progress((int) ((bytesUploaded / totalBytes) * 100));
                        }
                    })
                    .getAsJSONObject(new JSONObjectRequestListener() {
                        @Override
                        public void onResponse(JSONObject response) {
                            Log.d(TAG, "onResponse: " + response.toString());
                            imageView.progress(100);
                            BaseModel<String> baseModel = getGson().fromJson(response.toString(), BaseModel.class);
                            if (baseModel.isSuccess()) {
                                imageView.showContent(baseModel.getData());
                            } else {
                                imageView.showError(baseModel.getError());
                            }

                        }

                        @Override
                        public void onError(ANError error) {
                            Log.d(TAG, "onError: " + error.getErrorDetail());
                            imageView.progress(0);
                            imageView.showError(error.getErrorDetail() + "\n" + error.getErrorCode());
                        }
                    });

**Comment by geniusforapp** [comment]
D/OkHttp: --31de0c5b-94b2-4a17-807f-126190d47ebc--
04-09 15:08:29.298 18074-18862/com.beinmedia.kshw D/OkHttp: --> END POST (32835-byte body)
04-09 15:08:29.325 18074-18074/com.beinmedia.kshw I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@67c4538 time:2791738
04-09 15:08:29.359 18074-18862/com.beinmedia.kshw D/OkHttp: <-- HTTP FAILED: java.net.ProtocolException: unexpected end of stream

**Comment by amitshekhariitbhu** [comment]
can u tell me the exact error you are getting?

**Comment by geniusforapp** [comment]
@amitshekhariitbhu i'm trying to use upload method first i'm selecting image and give to the method by        .addMultipartFile("profile_image", new File(filePath)) but when it start upload it give this error 

D/OkHttp: --31de0c5b-94b2-4a17-807f-126190d47ebc--
04-09 15:08:29.298 18074-18862/com.beinmedia.kshw D/OkHttp: --> END POST (32835-byte body)
04-09 15:08:29.325 18074-18074/com.beinmedia.kshw I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@67c4538 time:2791738
04-09 15:08:29.359 18074-18862/com.beinmedia.kshw D/OkHttp: <-- HTTP FAILED: java.net.ProtocolException: unexpected end of stream

**Comment by geniusforapp** [comment]
@amitshekhariitbhu and also it did not connect to server so the request it did not go from my device

**Comment by geniusforapp** [comment]
@amitshekhariitbhu and also it did not connect to server so the request it did not go from my device

**Comment by geniusforapp** [comment]
@amitshekhariitbhu i think it's about D/OkHttp: Content-Length: 1061356 :\ dose it have a maximum content-Length

**Comment by amitshekhariitbhu** [comment]
I too think it's about OkHttp

**Comment by geniusforapp** [comment]
@amitshekhariitbhu what is the version u use in OkHttp in your library

**Comment by amitshekhariitbhu** [comment]
Refer https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md
It's 3.6.0

**Comment by geniusforapp** [comment]
@amitshekhariitbhu  i try to search some people said its about content length so is there any way to change it

**Comment by amitshekhariitbhu** [comment]
It seems it has been internally handled in OkHttp.

**Comment by geniusforapp** [comment]
ok @amitshekhariitbhu  how i can add file with key in post method this will help also

**Comment by geniusforapp** [comment]
@amitshekhariitbhu  if its possible .addFileBody("profile_image", new File(filePath)) like this

**Comment by amitshekhariitbhu** [comment]
As of now, there is no way to do so in the library, but the multipart is POST request only.

**Comment by geniusforapp** [comment]
@amitshekhariitbhu  is there any way to fix multipart issue :(

**Comment by amitshekhariitbhu** [comment]
I will check it and inform u if possible.

**Comment by geniusforapp** [comment]
@amitshekhariitbhu thanks my application is stoped coz of this problem i'm trying from morning and  don't want to use another libs this is very nice thanks 👍

**Comment by amitshekhariitbhu** [comment]
can you tell me the value of `error.getErrorCode()`.

**Comment by geniusforapp** [comment]
Error code 0

**Comment by geniusforapp** [comment]
@amitshekhariitbhu any update bro

**Comment by amitshekhariitbhu** [comment]
@geniusforapp you can get my mail which is publicly available, please send me the complete request like URL, file to be upload, header. I will test and fix it as soon as possible.

**Comment by amitshekhariitbhu** [comment]
The issue is in logging the okHttp response and request, so do not use body level logging if you are uploading.

**Comment by geniusforapp** [comment]
@amitshekhariitbhu thanks bro it worked very will thanks for your help 👍

**Comment by zongkang** [comment]
hey.bro，how can I control to set body level if uploading，otherwise other request should use this level to printf the log,thx

**Comment by amitshekhariitbhu** [comment]
@zongkang currently you can not customize it for each request.

**Comment by jiji42** [comment]
Hi @amitshekhariitbhu ,I'm trying to use AndroidNetworking.download(url,dirPath,fileName) to download a file from server but I got this Error "com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: java.net.ProtocolException: unexpected end of stream". Can you help me please?

**Comment by amitshekhariitbhu** [comment]
Have you enable body level logging?

**Comment by jiji42** [comment]
How could I enable it ?

**Comment by amitshekhariitbhu** [comment]
It's occurs in enabled mode.

**Comment by jiji42** [comment]
I used this method:
 private OkHttpClient getConfigOkHttpClient() {
        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BASIC);
        return new OkHttpClient.Builder()
                .addInterceptor(httpLoggingInterceptor)
                .retryOnConnectionFailure(true)
                .build();
    }

And I called it here: 
 AndroidNetworking.download(getUrl, path, file)
                .setTag(TAG_ANDROID_NETWORKING)
                .setPriority(Priority.HIGH)
                .setOkHttpClient(getConfigOkHttpClient())
                .setPercentageThresholdForCancelling(0) 
                .build();

**Comment by amitshekhariitbhu** [comment]
Try removing the logging.

**Comment by jiji42** [comment]
Hi, I removed it but I got the same error!!

**Comment by bonjourrohit89** [comment]
Hi Amit,
I am also getting this error while uploading file on server:
**com.androidnetworking.error.ANError: java.net.ProtocolException: unexpected end of stream**

How can I resolve this error. Can you please tell me?

**Comment by winnerawan** [comment]
@bonjourrohit89 did you resolve it ? also have this issue

**Comment by bonjourrohit89** [comment]
@winnerawan Yes I have resolved same, as @amitshekhariitbhu said we get this error when we enable logging. I had also enabled body level logging in my  Application class like:


//        if (BuildConfig.DEBUG) {
//            AndroidNetworking.enableLogging(HttpLoggingInterceptor.Level.BODY);
//        }

After commenting this code, my code working properly.

**Comment by hossein37** [comment]
also i have same issue.
 **com.androidnetworking.error.ANError: java.net.ProtocolException: unexpected end of stream**
or didn't get any response from server.
please solve the problem...

**Comment by sazibislam** [comment]
Just comment out the bellow code or off the debug. It works for me

// if (BuildConfig.DEBUG) {
// AndroidNetworking.enableLogging(HttpLoggingInterceptor.Level.BODY);
// }

**Comment by sazibislam** [comment]
Just comment out the bellow code or off the debug. It works for me

//if (BuildConfig.DEBUG) {
// AndroidNetworking.enableLogging(HttpLoggingInterceptor.Level.BODY)
// }/
