### ISSUE TITLE
How to use FAN with AsyncTaskLoader?

### ISSUE THREAD

**Issue by erlangp** [amitshekhariitbhu/Fast-Android-Networking#107]
How to use FAN with `AsyncTaskLoader`?
Thanks

**Comment by amitshekhariitbhu** [comment]
Sync call can be integrated with it.
https://amitshekhariitbhu.github.io/Fast-Android-Networking/synchronous_request.html

**Comment by erlangp** [comment]
Ow... Thanks! :smile: :+1:
