### ISSUE TITLE
Add file with key as post parameter

### ISSUE THREAD

**Issue by coldpinguin** [amitshekhariitbhu/Fast-Android-Networking#108]
I have POST API with some parameters like :
* `first_name` (String)
* `last_name` (String)
* `avatar_image` (File)

I can add `first_name` and `last_name` to request body using `addBodyParameter()`.
But for `avatar_image`, I don't know how to add a file.
I need to add file as post parameter with key `avatar_image` along with other parameters.
How can I do that?

**Comment by amitshekhariitbhu** [comment]
use `Multipart`, refer the below link:
https://amitshekhariitbhu.github.io/Fast-Android-Networking/upload_request.html#uploading-a-file-to-server

**Comment by coldpinguin** [comment]
I can get the response when I call using `post` but when I try using `Multipart`, I got 
` HTTP FAILED: java.net.ProtocolException: unexpected end of stream`.

**Comment by amitshekhariitbhu** [comment]
One possible reason : The issue is in logging the okHttp response and request, so do not use body level logging if you are uploading.

**Comment by coldpinguin** [comment]
Thanks @amitshekhariitbhu 
You're right. That issue is from body level logging.
Now I can post successfully.

**Comment by JanakBca1992** [comment]
I can get the response when I call using post but when I try using Multipart, I got
HTTP FAILED: java.net.ProtocolException: unexpected end of stream.

**Comment by amitshekhariitbhu** [comment]
@JanakBca1992 Please refer this https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/106
