### ISSUE TITLE
 how  do some operation before uploading ？

### ISSUE THREAD

**Issue by wfxphoebus** [amitshekhariitbhu/Fast-Android-Networking#112]
Before you upload compressed images use rxjava2

**Comment by amitshekhariitbhu** [comment]
Please explain me with example, I am not able to get what you are asking.

**Comment by wfxphoebus** [comment]
Rx2AndroidNetworking.upload(CHECKING_IN_PUBLICK_URL)
                .addMultipartParameter("icnum", icnum)
                .addMultipartParameter("content", content)
                .addMultipartFile(pics)
                .build()
                .getObjectObservable(ResultInfo.class)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread());


I want to compress images(pics) using rxjava before upload.

**Comment by wfxphoebus** [comment]
I don't know how the compression code is combined with Fast - Android - Networking

**Comment by amitshekhariitbhu** [comment]
```
getCompressBitmapObservable()
.flatMap(new Function<List<File>>, ObservableSource< ResultInfo >>() {
                    @Override
                    public ObservableSource<ApiQuizHistory> apply(<List<File>> files) throws Exception {
                        return Rx2AndroidNetworking.upload(URL)
                                   .addMultipartParameter("icnum", icnum)
                                   .addMultipartParameter("content", content)
                                   .addMultipartFile("key",files[0])
                                   .addMultipartFile("key",files[1])
                                   .build()
                                   .getObjectObservable(ResultInfo.class);
                    }
 })
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread());
```
