### ISSUE TITLE
How to keep sessions persistentce?

### ISSUE THREAD

**Issue by putraxor** [amitshekhariitbhu/Fast-Android-Networking#115]
I want to persist session between fast android networking with PHP server

**Comment by amitshekhariitbhu** [comment]
Let me find something for this and update you.

**Comment by putraxor** [comment]
thank you very much

**Comment by erlangp** [comment]
i use other lib to work with FAN to make session persistent:
`https://github.com/franmontiel/PersistentCookieJar`

> Usage
> 
> Create an instance of PersistentCookieJar passing a CookieCache and a CookiePersistor:
> 
> ClearableCookieJar cookieJar =
>                 new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(context));
> 
> Then just add the CookieJar when building your OkHttp client:
> 
> OkHttpClient okHttpClient = new OkHttpClient.Builder()
>                 .cookieJar(cookieJar)
>                 .build();

**Comment by putraxor** [comment]
I've used it too, 
but it seems PersistentCookieJar can't save httpOnly cookies
