### ISSUE TITLE
jar of the project 

### ISSUE THREAD

**Issue by guyron7** [amitshekhariitbhu/Fast-Android-Networking#116]
can you please provide a jar file of your project because i dont like to compile , make the project havey

**Comment by Bigappsdev** [comment]
i need it too please :)

**Comment by amitshekhariitbhu** [comment]
@guyron7 We will do it from the upcoming new release.

**Comment by amitshekhariitbhu** [comment]
Not a requirement. So closing this issue. Please use it through gradle dependency.
