### ISSUE TITLE
com.androidnetworking.error.ANError: 

### ISSUE THREAD

**Issue by salmansynergytop** [amitshekhariitbhu/Fast-Android-Networking#117]
Not able to request continuously getting error 

com.androidnetworking.error.ANError: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder()' on a null object reference

**Comment by amitshekhariitbhu** [comment]
@salmansynergytop tell me the URL, it must contain HTTP or HTTPS.

**Comment by hyperioniii** [comment]
I also encountered this error, i use http.

**Comment by kunal047** [comment]
Anyone resolved this issue ?

**Comment by sajib-4414** [comment]
I also faced the same problem, when I did not used HTTPS mistakenly

**Comment by hasnain-ahmad** [comment]
I also encounter the same error, my url is thsis `http://523.642.333.80:9002/`.

**Comment by fukemy** [comment]
same problem here when url is `http://192.168.100.35:xxxx/`.

**Comment by shareefhiasat** [comment]
In my case the url has typo by mistake an arabic character ظ  
instead of /  which happens to have same keyboard key.... but the logcat did not specify, 
it should provide more accurate excpetion, i suggest some one fork and improve :)

**Comment by Ndomsbrown** [comment]
> @amitshekhariitbhu I also encounter the same error, my URL is this `http://523.642.333.80:9002/`. @salmansynergytop Did you find the solution..?

I think you should use the url in his format "http://site.com" or "https://site.com" and not "site.com" coz if you use it without http or https you will get the okhttp3 url builder error

**Comment by adamfils** [comment]
Do you have -dontwarn okio.** in you proguard txt file?

**Comment by ZyreTechDeveloper** [comment]
did anyone find solution for this ?
