### ISSUE TITLE
Setting Content-Type doesn't work? 

### ISSUE THREAD

**Issue by elainedizon** [amitshekhariitbhu/Fast-Android-Networking#118]
Hi, I'm setting my Content-Type to "application/json; charset=utf-8" 
but after running the request it says my request header that my content type is still "application/x-www-form-urlencoded" Therefore, I am getting 415 Unsupported Media Type. Thank you for you help.

**Comment by amitshekhariitbhu** [comment]
@elainedizon can you put your code here so that I help you in the best possible way?

**Comment by syafiqzahir** [comment]
i think his mentioning about 
.addHeaders("content-type", "multipart/form-data"); 

but we still get an error response like this :
{"error":1003,"msg":"content-type (application\/x-www-form-urlencoded)

**Comment by code-schreiber** [comment]
I have the same problem, this is what I have tried with no success:

```java
    AndroidNetworking.post(url)
         .addHeaders("Content-Type","application/json")
         .addBodyParameter("userID", "anId")
         .addBodyParameter("password", "aPassword")
         // nothing special happens after this...
```
and
```java
    AndroidNetworking.post(url)
         .addBodyParameter("userID", "anId")
         .addBodyParameter("password", "aPassword")
         .setContentType("application/json")
         // nothing special happens after this...
```

**Comment by amitshekhariitbhu** [comment]
@code-schreiber Try setting content type like this `setContentType("application/json; charset=utf-8")`

**Comment by code-schreiber** [comment]
I tried that too, also other combinations sadly with no success. I even tried intercepting the request to overwrite the value 😿

**Comment by zongkang** [comment]
hi,I find if you use one post request ,it default Content-Type: application/x-www-form-urlencoded ,do you fix that problem?I trye to  setContentType("application/json; charset=utf-8"),but it did not work，how to fix it?

**Comment by adamvarhegyi** [comment]
Same issue, any resolve?

**Comment by lastkoh** [comment]
Same issue for me as well, any resolve? Thanks

**Comment by fukemy** [comment]
same issues here

**Comment by anujdeo** [comment]
> Guys, you can refer to #167 for this issue. I use the addApplicationJsonBody() and it's working.
> 
> ` AndroidNetworking.post(Constants.API.HOST + "/dialogflow") .addApplicationJsonBody(aiRequest)`

Thank you so soo sooo much!! I spent 5 hours and failed.. This comment has got it working.. Its 5 AM and now I can sleep :D
