### ISSUE TITLE
The correct way to retry api request,when network fail.

### ISSUE THREAD

**Issue by ltthuc1989** [amitshekhariitbhu/Fast-Android-Networking#119]
Hi,amitshekhariitbhu
While calling api request,Sometime network fail.So i want to recall current request .Could you tell me what correct way to retry current request.This is my code which use to recall current request.Thank so much
 @Override
    public void upload(final VideoRequest request) {
        getMvpView().showUploading();
        getCompositeDisposable().add(getDataManager()
                .doUploadVideo(request)
                ........
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        if (!isViewAttached()) {
                            return;
                        }
                        getMvpView().hideUploading();
                        if (throwable instanceof ANError) {
                            ANError anError = (ANError) throwable;
                            if (anError.getErrorCode() == AppConstants.API_STATUS_CODE_LOCAL_ERROR
                                    && anError.getErrorDetail().equals(ANConstants.CONNECTION_ERROR)) {
                               getMvpView().showCancelRetryAlert(R.string.connection_error, new CancelRetryCallback() {
                                   @Override
                                   public void onCancel() {
                                   }
                                   @Override
                                   public void onRetry() {
                                       upload(request);
                                   }
                               });
                            }
                            else {
                                handleApiError(anError);
                            }
                        }
                    }
                }));
    }

**Comment by amitshekhariitbhu** [comment]
The best way will be by using `retry` operator of RxJava.  Refer this [link](http://blog.danlew.net/2016/01/25/rxjavas-repeatwhen-and-retrywhen-explained/)

**Comment by ltthuc1989** [comment]
Thank for your good support ! @amitshekhariitbhu
