### ISSUE TITLE
Calling twilio api doesnt work? It returns only com.androidnetworking.error.ANError

### ISSUE THREAD

**Issue by danielsGit** [amitshekhariitbhu/Fast-Android-Networking#120]

**Comment by danielsGit** [comment]
https://{Account_SID}:{Token}@api.twilio.com/2010-04-01/Accounts/{Acount_SID}/SMS/Messages.json
It is working fine with POSTMAN. But i am not able to get response with this networking library.
How can fix it?

**Comment by amitshekhariitbhu** [comment]
can you tell me the exact code? That will help me to serve you better.

**Comment by danielsGit** [comment]
Yes here is my code.

JSONObject param = new JSONObject();
                try {
                    param.put("From", fromNo);
                    param.put("To", toNo);
                    param.put("Body", getString(R.string.receiveSMS) + verifyNumber);
                } catch (JSONException e) {
                    e.printStackTrace();
                }

AndroidNetworking.post("https://" + getString(R.string.twilio_account_sid) + ":" + getString(R.string.twilio_token) + "@api.twilio.com/2010-04-01/Accounts/" + getString(R.string.twilio_account_sid) + "/SMS/Messages.json")
                                .addJSONObjectBody(param)
                                .build()
                                .getAsJSONObject(new JSONObjectRequestListener() {
                                    @Override
                                    public void onResponse(JSONObject response) {
                                        Log.d("logs", "Response : " + response.toString());
                                    }

                                    @Override
                                    public void onError(ANError anError) {
                                        Log.d("logs", "Error : " + anError.toString());
                                    }
                                });

**Comment by danielsGit** [comment]
well twilio token number and account sid is correct. It's working fine with POSTMAN

**Comment by amitshekhariitbhu** [comment]
what error you are getting -> anError.toString()

**Comment by danielsGit** [comment]
com.androidnetworking.error.ANError

**Comment by amitshekhariitbhu** [comment]
error.getDetail()?

**Comment by danielsGit** [comment]
responseFromServerError

**Comment by amitshekhariitbhu** [comment]
check for error.getErrorBody() and errorCode

**Comment by danielsGit** [comment]
{"code": 20003, "detail": "Your AccountSid or AuthToken was incorrect.", "message": "Authentication Error - No credentials provided", "more_info": "https://www.twilio.com/docs/errors/20003", "status": 401} 401

**Comment by danielsGit** [comment]
Oh i am using the same url with postman. but it works fine.

**Comment by amitshekhariitbhu** [comment]
You can use pathParamter also. Refer [link](https://amitshekhariitbhu.github.io/Fast-Android-Networking/get_request.html#getting-parsed-object-list-as-response)

**Comment by amitshekhariitbhu** [comment]
there may case that the URL is building correctly. Check for that.

**Comment by danielsGit** [comment]
same issue with using pathParameter.
and URL is correct. I've checked several times and copy the link and paste it in postman.

**Comment by amitshekhariitbhu** [comment]
The request is get or post?

**Comment by danielsGit** [comment]
post

**Comment by amitshekhariitbhu** [comment]
You can get my e-mail on Github profile, send me the detail that you cannot sent here. So that I can also try it and help you.

**Comment by danielsGit** [comment]
What information do you need? Plz tell me exactly.

**Comment by danielsGit** [comment]
Account SID, Token number, From phone no. Do you need these informations?

**Comment by amitshekhariitbhu** [comment]
only the things required in URL

**Comment by danielsGit** [comment]
Just sent detailed informations to your gmail

**Comment by amitshekhariitbhu** [comment]
Checking

**Comment by danielsGit** [comment]
Ok thanks

**Comment by amitshekhariitbhu** [comment]
Check main sent you the solution, it works

**Comment by danielsGit** [comment]
sorry what do you mean?

**Comment by amitshekhariitbhu** [comment]
I have mailed you the solution

**Comment by danielsGit** [comment]
Oh let me see. Just mins

**Comment by danielsGit** [comment]
Yep it works. Thanks very much. I can see my fault.

**Comment by ayushdimri** [comment]
can you please send me that code .I am facing the same issue.

**Comment by amitshekhariitbhu** [comment]
![screenshot_20180110-164719](https://user-images.githubusercontent.com/9877145/34770162-24f73b66-f626-11e7-8ee3-e92f9ac181ba.png)
@ayushdimri
