### ISSUE TITLE
NullPointerException with Advanced Network Profiling in Canary 3.0

### ISSUE THREAD

**Issue by TrueV** [amitshekhariitbhu/Fast-Android-Networking#121]
Hey, 
there is a connection problem with the newest gradle canary build 3.0 with this library.  I analyzed the problem and it seems, that the "**advanced network profiling**" caused the errors while running. 

errorDetail: connectionError
deteilMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

I can't go into details, how the Error evolves, but deactivating "**advanced network profiling**" (Run->Edit Configurations) resolved the issue.

**Comment by amitshekhariitbhu** [comment]
@TrueV Ok I will check it soon.

**Comment by amitshekhariitbhu** [comment]
Not able to reproduce it.
