### ISSUE TITLE
Basic Request Send is not working

### ISSUE THREAD

**Issue by vigneshwarcet** [amitshekhariitbhu/Fast-Android-Networking#126]
public class MainActivity extends AppCompatActivity {

    private static final String TAG = MainActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //AndroidNetworking.initialize(getApplicationContext());

        System.out.println("Hello------");

        setContentView(R.layout.activity_main);

    }

    public void makeJSONArrayRequest(View v) {

try{

    AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
            .addPathParameter("pageNumber", "0")
            .addQueryParameter("limit", "3")
            .addHeaders("token", "1234")
            .setTag("test")
            .setPriority(Priority.LOW)
            .build()
            .getAsJSONArray(new JSONArrayRequestListener() {
                @Override
                public void onResponse(JSONArray response) {
                    // do anything with response

                    Toast.makeText(MainActivity.this, "Is it Working", Toast.LENGTH_SHORT).show();
                }
                @Override
                public void onError(ANError error) {
                    // handle error
                }
            });

}catch (Exception e){

    System.out.println("Error------"+e);
}

        System.out.println("Onnumae varalaayaee ulagathulaaaa");

    }

}

Above I show my code, it is pretty simple in the sense, i just call the makeJSONArrayRequest function on a button click but there isno trace for request sending, I don't know why, what is then probable reason for this.

**Comment by amitshekhariitbhu** [comment]
Put logging in `onError`.
Have you provided the internet permission in the manifest file?
