### ISSUE TITLE
5k+ Methods Count isn't too huge?

### ISSUE THREAD

**Issue by CeJienAJPC** [amitshekhariitbhu/Fast-Android-Networking#128]
I mean I just came across your library. Thanks for the awesome work. Seems very promising. However, 5k+ methods make me blink. Can something be done about this? like splitting the library into modules? (if possible).

I am an amateur/beginner developer. Please correct me if I am wrong.

Thanks

**Comment by amitshekhariitbhu** [comment]
Which module you are using ? Rxjava or Jackson ?
Anyway this library include two dependencies okhttp and gson.

**Comment by CeJienAJPC** [comment]
I wasn't elaborate. I was asking if you can break the library into modules based on use case. Like one for Upload and Download, one for GET and POST. What if the developer is in need to use the library only to Upload/Download files or only to use GET/POST. Could breaking into modules reduce the library size? Is GSON necessary in the case, the developer only needs to Upload/Download file(s) from URL? Please correct me if I am wrong.

**Comment by amitshekhariitbhu** [comment]
Yeah, we can do that also.

**Comment by CeJienAJPC** [comment]
That was I was referring to. Maybe in future versions?

**Comment by amitshekhariitbhu** [comment]
Yes

**Comment by Rainer-Lang** [comment]
@CeJienAJPC Are you using Proguard? Try it.

**Comment by CeJienAJPC** [comment]
Sure. Good idea. I would check it out.
