### ISSUE TITLE
cant run app after installing library

### ISSUE THREAD

**Issue by arielhasidim** [amitshekhariitbhu/Fast-Android-Networking#129]
i installed like the instructions in a fresh new project-
In the gradle file:

> compile "com.amitshekhar.android:android-networking:1.0.0"

> compile "com.amitshekhar.android:jackson-android-networking:1.0.0"

In the manifest:
`<uses-permission android:name="android.permission.INTERNET" />`
`<uses-permission android:name = "android.permission.ACCESS_NETWORK_STATE"/>`

in the mainActivity Java file:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       TextView text;
        AndroidNetworking.initialize(getApplicationContext());
        AndroidNetworking.setParserFactory(new JacksonParserFactory());
        AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                .addPathParameter("pageNumber", "0")
                .addQueryParameter("limit", "3")
                .addHeaders("token", "1234")
                .setTag("test")
                .setPriority(Priority.LOW)
                .build()
                .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                        text.setText(response.toString());
                    }
                    @Override
                    public void onError(ANError error) {
                        // handle error
                    }
                });

    }

this is my error:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: C:\Users\NoamH\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.8.2\1f12816593c1422be957471c98a80bfbace60fa2\jackson-databind-2.8.2.jar
	File2: C:\Users\NoamH\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.8.2\80004060cc6f71a027b81e89ef4d74628f824f\jackson-core-2.8.2.jar
	File3: C:\Users\NoamH\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.8.0\45b426f7796b741035581a176744d91090e2e6fb\jackson-annotations-2.8.0.jar

**Comment by amitshekhariitbhu** [comment]
@arielhasidim may be you are already using the Jackson library with the jar. Remove the jar.

**Comment by Patrick-Wallin** [comment]
I have same issue.  Which one should I remove? I looked at my build.gradle and do not have other Jackson-Parser.  It is possible that other library may use that that I could not see.

**Comment by amitshekhariitbhu** [comment]
@Patrick-Wallin yes it is possible that any other library may be using.

**Comment by ronanlima** [comment]
I have the same issue and solved it this way

compile ("com.amitshekhar.android:jackson-android-networking:1.0.0") {
        exclude group: "com.fasterxml.jackson.core", module: "jackson-annotations"
        exclude group: "com.fasterxml.jackson.core", module: "jackson-core"
        exclude group: "com.fasterxml.jackson.core", module: "jackson-databind"
    }

Doing this, the app back to install normally.
