### ISSUE TITLE
Parsing list in generic object.

### ISSUE THREAD

**Issue by jobnte** [amitshekhariitbhu/Fast-Android-Networking#130]

**Comment by hyperioniii** [comment]
json response array : []
i have error : 
[handleApiError:104]------------getMessage---: java.lang.SecurityException: Can not make a java.lang.reflect.Field constructor accessible 
                                                                  -getErrorCode--: 0 
                                                                  ---getErrorBody-: null 
                                                                  ---getErrorDetail-: parseError
