### ISSUE TITLE
Instrumental test and mock response

### ISSUE THREAD

**Issue by lhyjason** [amitshekhariitbhu/Fast-Android-Networking#132]
Is there any way to mock a response for Rx2AndroidNetworking under Instrumental test? I want to test the UI without having real request sent to server. Thanks!

**Comment by amitshekhariitbhu** [comment]
Please refer: [link](https://github.com/MindorksOpenSource/android-mvp-architecture/blob/master/app/src/test/java/com/mindorks/framework/mvp/ui/login/LoginPresenterTest.java)
