### ISSUE TITLE
Getting error on simple get request and image upload task

### ISSUE THREAD

**Issue by kunalmangela** [amitshekhariitbhu/Fast-Android-Networking#133]
My Code for simple get method is not working it is give me error
url="http://dev.efurtherance.com/rcis_school_new/webservice/system/all"
param=school_code
AndroidNetworking.get("http://dev.efurtherance.com/rcis_school_new/webservice/system/all")
.addQueryParameter("school_code", "RCISTHANE")
.setTag("test")
.setPriority(Priority.LOW)
.build()
.getAsJSONArray(new JSONArrayRequestListener() {
@override
public void onResponse(JSONArray response) {
// do anything with response
Log.e("resp", String.valueOf(response));

                }
                @Override
                public void onError(ANError error) {
                    // handle error
                    Log.e("resp", String.valueOf("error"));

                }
            });
/////////////////////////////////////////////////

And code for upload image file also not working it gives me connection error
url="http://dev.efurtherance.com/rcis_school_new/webservice/teacher/update"
params=profile_image(image file),action,reference;
AndroidNetworking.upload("http://dev.efurtherance.com/rcis_school_new/webservice/teacher/update")
.addMultipartFile("profile_image", new File(imgpath))
.addMultipartParameter("action", "updateprofileimage")
.addMultipartParameter("reference","T1038")
.setPriority(Priority.HIGH)
.build()
.setUploadProgressListener(new UploadProgressListener() {
@override
public void onProgress(long bytesUploaded, long totalBytes) {
// do anything with progress
}
})
.getAsJSONObject(new JSONObjectRequestListener() {
@override
public void onResponse(JSONObject response) {
// do anything with response
Log.e("resp", String.valueOf(response));
}

                @Override
                public void onError(ANError error) {
                    // handle error
                    Log.e("resp", String.valueOf("error"));
                    if (error.getErrorCode() != 0) {
                        // received error from server
                        // error.getErrorCode() - the error code from server
                        // error.getErrorBody() - the error body from server
                        // error.getErrorDetail() - just an error detail
                        Log.e("onError errorCode : ", String.valueOf(error.getErrorCode()));
                        Log.e("onError errorBody : ", String.valueOf(error.getErrorBody()));
                        Log.e("onError errorDetail : ", String.valueOf(error.getErrorDetail()));
                        // get parsed error object (If ApiError is your class)
                    } else {
                        // error.getErrorDetail() : connectionError, parseError, requestCancelledError
                        Log.e("onError errorDetail : ", String.valueOf(error.getErrorDetail()));
                    }
                }
            });

**Comment by amitshekhariitbhu** [comment]
@kunalmangela can u tell me the error detail in the first request.
