### ISSUE TITLE
ssl cert error

### ISSUE THREAD

**Issue by amervelic** [amitshekhariitbhu/Fast-Android-Networking#135]
com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

OkHttp 3.6 

https://bhmobile.bhtelecom.ba/prijava

on iOS URLSession - working fine

**Comment by amitshekhariitbhu** [comment]
Refer [link](https://stackoverflow.com/questions/25509296/trusting-all-certificates-with-okhttp) or you can fix it from the server.

**Comment by amervelic** [comment]
Yes, I tried immediately after the error - but the error again occurs

**Comment by amervelic** [comment]
Problem solved:
https://jiafei427.wordpress.com/2016/04/28/connect-to-server-with-self-signed-certificate-in-android-retrofit-or-okhttp/

Solution 1:

**Comment by vkpalmrt** [comment]
@amitshekhariitbhu 
I am using the AndroidNetworking for API integration but below error occurs for SSL but I don't know how it will be handled plz suggest how we can handle this issue.

com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
