### ISSUE TITLE
specify method programatically

### ISSUE THREAD

**Issue by paulg446** [amitshekhariitbhu/Fast-Android-Networking#137]
Is there a way to specify the method programatically, instead of calling the get/put/post/delete methods explicitly? 

AndroidNetworking.request(url)
                 .setRequestMethod("GET")

Such a feature would make the library much more re-usable.

**Comment by amitshekhariitbhu** [comment]
@paulg446 This is not present in current version, I will add this feature in new version.

**Comment by amitshekhariitbhu** [comment]
Added support for this in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
