### ISSUE TITLE
Expected BEGIN_OBJECT but was BEGIN_ARRAY

### ISSUE THREAD

**Issue by Drjacky** [amitshekhariitbhu/Fast-Android-Networking#138]
I have a web-service that return Array at the first column of JSON. Something like:
```
[
  {
    "id": 1,
    "title": "test1"
  },
  {
    "id": 1,
    "title": "test2"
  }, ... 
]
```
So I get this error:

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY

How should we handle this?! In the normal way, we can do something like below:
```
Type collectionType = new TypeToken<Collection<POJOClassss>>(){}.getType();
Collection<POJOClassss> enums = gson.fromJson(yourJson, collectionType);
//Source: https://stackoverflow.com/a/9598988/421467
```
I can't use `getAsJSONArray`, because I wanna return the result as `Observable`.
And I know about `getObjectListObservable`, but isn't another and better way?

**Comment by amitshekhariitbhu** [comment]
Use `getJSONArrayObservable`

**Comment by alexfournier** [comment]
@amitshekhariitbhu - What if I'm using `getObjectFlowable(MyClass.class)` to parse the json?

I'm trying to merge several json endpoints and parse them at the same time.

**Comment by amitshekhariitbhu** [comment]
@alexfournier It should work
