### ISSUE TITLE
Add support for custom content-type

### ISSUE THREAD

**Issue by willemevenwel** [amitshekhariitbhu/Fast-Android-Networking#14]
Thanks for great library.

Please add support to add custom content-type when using RequestBuilder. It would be nice to be able to add bytes as the body, then custom content-type.

Something like:

AndroidNetworking.post(url).addByteBody(bytes).addContentType("application/json")

Regards,

Willem

**Comment by amitshekhariitbhu** [comment]
@willemevenwel : added in development branch

**Comment by willemevenwel** [comment]
Thanks, great work. Tested and working. Will provide more feedback if more feedback comes up.

**Comment by nithingkamath** [comment]
Hi, Thanks for this awesome library. I have one question. How to get the status code from the response.? I didn't find any way to get that.

**Comment by amitshekhariitbhu** [comment]
@nithingkamath : You are welcome.

to get the response code you can call response.code() if you are using getAsOkHttpResponse.

And also like this :
We have a callback method onError(ANError error).

```
  if (error.getErrorCode() != 0) {
     // received error from server
     // error.getErrorCode() - the error code from server
     // error.getErrorBody() - the error body from server
     // error.getErrorDetail() - just an error detail
     Log.d(TAG, "onError errorCode : " + error.getErrorCode());
     Log.d(TAG, "onError errorBody : " + error.getErrorBody());
     Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());                            
    } else {
     // error.getErrorDetail() : connectionError, parseError, requestCancelledError
     Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
    }                    
```

**Comment by tausiq** [comment]
@amitshekhariitbhu 
Could you please provide support that `OkHttpResponse` object will get passed in `onResponse` method of `ParsedRequestListener` interface?
In that case, we can get the status code from `OkHttpResponse` object and still enjoying the parsed object in `onResponse`. Thanks in advance!

**Comment by amitshekhariitbhu** [comment]
As of I have done to get OkHttpResponse in Development as getAsOkHttpResponse

As of now I have uploaded it on beta.

So please compile using the below link.

`compile 'com.amitshekhar.android:android-networking:0.2.0-beta-0`

```
.getAsOkHttpResponse(new OkHttpResponseListener() {
    @Override
    public void onResponse(Response response) {
        if (response != null) {
            // we can find header also like response.headers() or anything than can be obtained from OkHttpResponse
            if (response.isSuccessful()) {
                Log.d(TAG, "response is successful");
                try {
                    Log.d(TAG, "response : " + response.body().source().readUtf8());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                Log.d(TAG, "response is not successful");
            }
        } else {
            Log.d(TAG, "response is null");
        }
    }

    @Override
    public void onError(ANError error) {
        Utils.logError(TAG, error);
    }
});
```

I think you are telling to provide both parseResponse and OkHttpResponse in a response listener

**Comment by tausiq** [comment]
Thank you for your quick reply!

I am aware of the `OkHttpResponseListener` functionality. What I requested, can be summarized like below, 

```
.getAsParsed(new TypeToken<User>() {}, new ParsedRequestListener<User>() {
    @Override
    public void onResponse(Response response, User user) {
        // we can find header like response.headers()
        // we can get user as parsed
    }
    
    @Override
    public void onError(ANError anError) {
        // handle error
    }
}); 
```

**Comment by amitshekhariitbhu** [comment]
I will try to add this as soon as possible.
