### ISSUE TITLE
Multiple values with same parameter support is missing.

### ISSUE THREAD

**Issue by guness** [amitshekhariitbhu/Fast-Android-Networking#140]
HTTP protocol allows following request. I am not able find it on FAN, please add it if missing.

`https://example.com/?q=debug&id=12&id=13&id=19&id=123123123`

**Comment by amitshekhariitbhu** [comment]
Yes, currently it does not support the two parameter with same key.

**Comment by guness** [comment]
I know this is stupid but HTTP supports it, retrofit supports it, please FAN should also support it.

**Comment by amitshekhariitbhu** [comment]
Yes I will add this support.

**Comment by amitshekhariitbhu** [comment]
Added support for this in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
