### ISSUE TITLE
Trouble accepting cert SSL when port different from 443

### ISSUE THREAD

**Issue by xbassols** [amitshekhariitbhu/Fast-Android-Networking#142]
Hi,

I'm having trouble with the library returning: 
com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

When a valid (Let's encrypt) SSL cert is used on a different port such as: https://api.example.com:8088

The cert is accepted by the phone and desktop browser so I can't understand why the library is choking with it.

Thanks.

**Comment by amitshekhariitbhu** [comment]
For now, you can refer [this](https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/135)

**Comment by xbassols** [comment]
Yes done already but that is a very unsafe way to handle the problem.

**Comment by amitshekhariitbhu** [comment]
Ok, let me come up with some better solution.

**Comment by xbassols** [comment]
Hi Amit I did some more troubleshooting and I retract myself. The problem is not the library but the configuration of the certificate on the server side.

For other people. If the library fails check first that the certificate is valid running:

openssl s_client -connect example.com:443

At the bottom you should see:  Verify return code: 0 (ok)

Otherwise the certificate configuration is wrong.

**Comment by abbasehtasham** [comment]
com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: Unacceptable certificate: CN=R3, O=Let's Encrypt, C=US
hi I'm getting this error while using Android Network library for API calls please help me
