### ISSUE TITLE
Getting error on parsing when response is empty with Observable

### ISSUE THREAD

**Issue by anderscheow** [amitshekhariitbhu/Fast-Android-Networking#143]
I saw some answers where empty response required Completable, is there anyway to use Completable instead of Observable?

**Comment by amitshekhariitbhu** [comment]
I think there will be some way to convert observable into completable. I will try to add this feature in-built in new release.

**Comment by anderscheow** [comment]
thanks a lot, waiting for your new release :)

**Comment by amitshekhariitbhu** [comment]
Added support for this in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
