### ISSUE TITLE
addStringBody() not working

### ISSUE THREAD

**Issue by shitallondhe** [amitshekhariitbhu/Fast-Android-Networking#144]
public class WebService {
    private String url;
    private HashMap<String, String> [queryParameter;](`url`)
    private HashMap<String, String> pathParameter;
    private HashMap<String, String> requestHeaders;
    private WebServiceResponseListener webServiceListener;

    public WebService() {
    }

    /**
     *
     * @param url url of request
     * @param queryParameter hashmap of query parameter
     * @param pathParameter hashmap of path parameter
     */
    public WebService(String url, HashMap<String, String> queryParameter, HashMap<String, String> pathParameter, HashMap<String, String> _requestHeaders) {
        this.url = url;
        this.queryParameter = queryParameter;
        this.pathParameter = pathParameter;
        if(_requestHeaders == null) {
            this.requestHeaders = getRequestHeaders();
        } else {
            this.requestHeaders = _requestHeaders;
        }
    }

    /**
     * Set WebserviceResponseListener parameter
     * @param webServiceListener
     */
    public void setWebServiceResponseListener(WebServiceResponseListener webServiceListener) {
        this.webServiceListener = webServiceListener;
    }

    /**
     * Post Json Object
     * @param requestTag tag
     * @param priority priority
     * @param bodyParameters hashmap of bodyparameters
     */
    //public void postJsonObject(String requestTag, Priority priority,HashMap<String,String> bodyParameters) {
    public void postJsonObject(String requestTag, Priority priority,Object bodyParameters) {
        ANRequest.PostRequestBuilder postRequestBuilder = new ANRequest.PostRequestBuilder(url);

        if (this.pathParameter != null)
            postRequestBuilder.addPathParameter(pathParameter);

        if (this.queryParameter != null)
            postRequestBuilder.addQueryParameter(queryParameter);

        if (this.requestHeaders != null)
            postRequestBuilder.addHeaders(requestHeaders);

        if (requestTag != null)
            postRequestBuilder.setTag(requestTag);

        if (priority != null)
            postRequestBuilder.setPriority(priority);

      // this is where things go wrong
      // after this when i actually make the web service call, execution goes in the error callback
       if (bodyParameters != null) {
            postRequestBuilder.addStringBody("\'" + bodyParameters.toString() + "\'");
            //postRequestBuilder.addBodyParameter(bodyParameters);
      }

        postRequestBuilder.build().getAsJSONObject(new JSONObjectRequestListener() {
            @Override
            public void onResponse(JSONObject response) {
                try {

                    webServiceListener.onSuccess(response.toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void onError(ANError anError) {
                webServiceListener.onError(anError);
            }
        });
    }  
}

**Comment by amitshekhariitbhu** [comment]
Can u tell me the error detail message?

**Comment by shitallondhe** [comment]
I am getting a callback in the onError method and the ANError object that i am receiving is as follows : 
![image](https://user-images.githubusercontent.com/24652844/28604750-b9cd81b6-71ea-11e7-87a0-09fa289042b5.png)

**Comment by amitshekhariitbhu** [comment]
This error is coming from server. Let me know what your server is telling. Here, I can only see `Service Error`. May be like contentType is wrong or something else.

**Comment by shitallondhe** [comment]
The server is not accessible by us.
We are getting the success response if we call the same api using AsyncTask
The code for the same is as follows : 

class UserInfoTask extends AsyncTask<Void,Void,String> {
        private String responseResult;
        private String verifyAuth;

        public UserInfoTask(String authToken) {
            verifyAuth=authToken;
        }

        @Override
        protected void onPreExecute() {
            pDialog.show();
        }

        @Override
        protected String doInBackground(Void... params) {
            try {
                String burl = "***URL***";
                printLog("userUrl",burl);
                URL url = new URL(burl);
                HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("POST");
                connection.setConnectTimeout(20000);
                connection.setRequestProperty("Content-Type", "application/json");
                connection.setRequestProperty("Strict-Transport-Security", "max-age=31536000");
                connection.setRequestProperty("X-Content-Type-Options", "nosniff");
                connection.setDoInput(true);
                connection.setDoOutput(true);

                JSONObject jObject = new JSONObject();
                jObject.put("token", verifyAuth);

                String bodyData = jObject.getString("token");

                connection.setRequestProperty("IcmAuthToken", verifyAuth);
                connection.connect();
                String stringEntity = '"' + bodyData + '"';
                printLog(" Body data : ", stringEntity);
                //httpPost.setEntity(new StringEntity(stringEntity));
                byte[] outputInBytes = stringEntity.getBytes("UTF-8");
                OutputStream os = connection.getOutputStream();
                os.write(outputInBytes);
                os.close();

                int responseCode = connection.getResponseCode();
                String responseMessage = connection.getResponseMessage();
                printLog("Response Code " + responseCode, " " + responseMessage);
                InputStream stream = null;
                if (responseCode >= 400) {
                    stream = connection.getErrorStream();
                } else {
                    stream = connection.getInputStream();
                }

//					InputStream stream = connection.getInputStream();
                InputStreamReader reader = new InputStreamReader(stream);
                StringBuilder builder = new StringBuilder();
                int chr;
                while ((chr = reader.read()) != -1) {
                    builder.append((char) chr);
                }
                responseResult = builder.toString();

            }catch (Exception e){
                if (pDialog!=null)
                   pDialog.hide();
//                Toast.makeText(LoginWebActivity.this, "Not Verified", Toast.LENGTH_SHORT).show();
                showUnverifiedAlert();
            }
            return responseResult;
        }

        @Override
        protected void onPostExecute(String resultstr) {

            try{


                JSONObject searchObj = new JSONObject(resultstr);


                if (searchObj.getInt("Identifier")>0){
                    int Identifier = searchObj.getInt("Identifier");
                    printLog("~~~~~~~~~~~~~~~UserID : ", "" + Identifier);
                    prefernces.savePrefIntValues(ICMUSERID, (Identifier));
                    int id = prefernces.getPrefIntValues(ICMUSERID);
                    printLog("~~~~~~~~~~~~~~~UserID : ", "" +id);
                    Toast.makeText(LoginWebActivity.this, "Verified", Toast.LENGTH_SHORT).show();
                    callMainActivity(verifyAuth);
                }else {
                    showUnverifiedAlert();
//               Toast.makeText(LoginWebActivity.this, "Not Verified", Toast.LENGTH_SHORT).show();
                }


            }catch (Exception e){
                if (pDialog!=null)
                    pDialog.dismiss();
//                Toast.makeText(LoginWebActivity.this, "Not Verified", Toast.LENGTH_SHORT).show();
                showUnverifiedAlert();
            }

            if (pDialog!=null)
                pDialog.dismiss();
        }
    }

**Comment by shitallondhe** [comment]
Also specify if any specific content type is needed to be added, because when we try to hit same api from rest client we get success by just passing content type as application/json

**Comment by amitshekhariitbhu** [comment]
Try setting this in the request `setContentType("application/json; charset=utf-8")`

**Comment by BongJaeChoi** [comment]
i suggest check parameter before request

**Comment by yehiahd** [comment]
try .**addApplicationJsonBody**(bodyParameters) it works for me
