### ISSUE TITLE
addHeaders() not working

### ISSUE THREAD

**Issue by igabice** [amitshekhariitbhu/Fast-Android-Networking#145]
I have a web service that requires authorization and content type included in the header of every post request.  using the .addHeaders("Authorization",  TOKEN);
.addHeaders("content-type", "application/json");

**Comment by igabice** [comment]
it returns unauthorized access but accessing the same service using postman returns the expected response.

**Comment by amitshekhariitbhu** [comment]
Try `addHeader("Authorization", "Bearer " + TOKEN)`

**Comment by igabice** [comment]
its still not working

**Comment by amitshekhariitbhu** [comment]
Try setting content type like this  `setContentType("application/json; charset=utf-8")`

**Comment by igabice** [comment]
its still not working

**Comment by Isabellle** [comment]
Same error here

**Comment by Isabellle** [comment]
Finally worked on my side; had unwanted chars, so did .addHeaders("Authorization", basicAuth.trim())

**Comment by igabice** [comment]
its working. thanks

**Comment by AlanPintor-git** [comment]
> basicAuth.trim()

I am getting "cannot find symbol variable basicAuth" 
Can you help me?

**Comment by AlanPintor-git** [comment]
> 

What works for me is to use the addQueryParamenter and the getAsJSONOoject, and "Bearer" before the token see code below:

AndroidNetworking.get("https:// . . .")
                 //.addPathParameter("pageNumber", "0")
                 .addQueryParameter("limit", "3")
                 .addHeaders("token", "Bearer 1234")
                 .setTag("test")
                 .setPriority(Priority.LOW)
                 .build()
                 //.getAsJSONArray(new JSONArrayRequestListener() {
                 .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                      // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                      // handle error
                    }
                });
