### ISSUE TITLE
OPTIONS Request

### ISSUE THREAD

**Issue by saber-nyan** [amitshekhariitbhu/Fast-Android-Networking#146]
Hello.
Can I make an `OPTIONS` request using your library? Or for this purpose it is necessary to use `OkHttp`?

**Comment by amitshekhariitbhu** [comment]
It does not support currently, may we can add this support in the future.

**Comment by amitshekhariitbhu** [comment]
Added support for this in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).

**Comment by saber-nyan** [comment]
Oh, thanks.
