### ISSUE TITLE
Retry on requests

### ISSUE THREAD

**Issue by anderscheow** [amitshekhariitbhu/Fast-Android-Networking#148]
Is there any possible ways to retry if request failed?

**Comment by amitshekhariitbhu** [comment]
You can customize the OkHttpClient for retrying. In the new release we will add a very simple interface.

**Comment by molavy** [comment]
can i ask ,when retry simple interface become ready?

**Comment by amitshekhariitbhu** [comment]
Planned in the upcoming release. More 3 weeks

**Comment by martinho2604** [comment]
May I ask is simple interface ready now or when will it be?

**Comment by amitshekhariitbhu** [comment]
Now, can be easily done through RxJava, so closing the issue.
