### ISSUE TITLE
Support for custom respsonses, and response content type.

### ISSUE THREAD

**Issue by willemevenwel** [amitshekhariitbhu/Fast-Android-Networking#15]
Hi,

Thanks again for wonderful library.

Please consider adding support to handle custom responses, and response Content-Type.

For example something like this for both post and get:

AndroidNetworking.get(pUrl)
    .setPriority(Priority.LOW)
    .build()
    .getResponse(new ResponseListener() {
         @Override
         public void onResponse(Response response) {
             // do anything with response
             Logger.info(AsyncOkHttpTask.class, "AndroidNetworking.get - onResponse");

             String contentType = response.getContentType(); //application/json or application/text or xml etc...

             String body = response.getBodyAsString(); //getBodyAsBytes() or getBodyAsStream() etc....

             String status = response.getStatusString();

             int code = response.getResultCode();
             
         }

         @Override
         public void onError(ANError error) {
             // handle error
             Logger.info(AsyncOkHttpTask.class, "AndroidNetworking.get - onError");

         }

    }

);

Kind Regards

Willem

**Comment by amitshekhariitbhu** [comment]
@willemevenwel : Thanks for the request. This is a much needed feature. We will surely add this in new version.

**Comment by amitshekhariitbhu** [comment]
@willemevenwel  : added in development branch

**Comment by willemevenwel** [comment]
Thanks, great work. Tested and working. Will provide more feedback if more feedback comes up.

**Comment by amitshekhariitbhu** [comment]
@willemevenwel : version 0.2.0 has been released
