### ISSUE TITLE
Expected BEGIN_ARRAY but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by thanhbinh84** [amitshekhariitbhu/Fast-Android-Networking#152]
I have managed to post an java object, but cannot with list of object: 

static public void submitStatistics(List<Item> items,
                                        final Consumer<String> onSuccess, final Consumer<Throwable> onError) {
        Rx2AndroidNetworking.post().addBodyParameter(items)

It always throw exception 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 3 path $[0]

**Comment by amitshekhariitbhu** [comment]
I will check it, if required, I will fix this in new version.

**Comment by xdnan7** [comment]
any workaround for this? thanks

**Comment by xdnan7** [comment]
Thanks for your help @thanhbinh84, but in case anyone needs, this is my workaround:
Convert your list of object into JSON String.

Public UpdateObjekRequest(List<DetPhoto> detPhotos) {
        // convert list to json string
        Gson gson = new Gson();
        if (detKoordinats != null) {
            Type listType = new TypeToken<List<DetKoordinat>>() {
            }.getType();
            this.detKoordinatListJson = gson.toJson(detKoordinats, listType);
        }
}

**Comment by CiceroRegis** [comment]
I have the same problem and so far I can not solve the problem 
 could someone tell me what I'm missing?
 
`public List<Candidato> getlistar() {
	Client client =  Client.create();
	
	WebResource resource = client.resource("https://dadosabertos.camara.leg.br/api/v2/deputados");
    System.out.println(resource.get(String.class));

    String json = resource.get(String.class);
    Gson gson = new Gson();
    return gson.fromJson(json, new TypeToken<List<Candidato>>(){}.getType());
	}`
