### ISSUE TITLE
Is it possible to ignore a field to post 

### ISSUE THREAD

**Issue by thanhbinh84** [amitshekhariitbhu/Fast-Android-Networking#153]
User user = new User();
user.firstname = "Amit";
user.lastname = "Shekhar";

Let say User class has another attribute such as fullName which is not needed to post, how can we ignore this field? Does our lib support some kind of annotation @ignore to bypass this field?  

AndroidNetworking.post("https://fierce-cove-29863.herokuapp.com/createUser")
                 .addBodyParameter(user) // posting java object
                 .setTag("test")
                 .setPriority(Priority.MEDIUM)
                 .build()
                 .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                      // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                      // handle error
                    }
                });

**Comment by amitshekhariitbhu** [comment]
@thanhbinh84 Yes it's possible, Check the [project](https://github.com/MindorksOpenSource/android-mvp-architecture)

Thanks
Amit Shekhar

**Comment by thanhbinh84** [comment]
@amitshekhariitbhu thanks, checked, but cannot figure out. :D. could you give the keyword, would be very useful. thanks again.

**Comment by amitshekhariitbhu** [comment]
@Expose annotation

**Comment by amitshekhariitbhu** [comment]
And also use 
`GsonBuilder builder = new GsonBuilder().excludeFieldsWithoutExposeAnnotation();
  Gson gson = builder.create();
AndroidNetworking.setParserFactory(new GsonParserFactory(gson));
`

**Comment by amitshekhariitbhu** [comment]
You have to set the parser factor with custom Gson.

```
GsonBuilder builder = new GsonBuilder().excludeFieldsWithoutExposeAnnotation(); 
Gson gson = builder.create();
AndroidNetworking.setParserFactory(new GsonParserFactory(gson));
```


```
public class {

@Expose
private String name;

private int age;

}
```
So here, the age field will be ignored

**Comment by thanhbinh84** [comment]
@amitshekhariitbhu perfect! problem is solved. thanks a lot

**Comment by thanhbinh84** [comment]
@amitshekhariitbhu I found an easier approach. Don't need to set custom GSON, just add transit modifier to the ignore wanted field 
`private transient int age;`
Tested, work like a charm. :) 
http://memorynotfound.com/gson-excluding-fields-with-modifiers-from-json/
