### ISSUE TITLE
java.net.SocketTimeoutException: failed to connect to /192.168.0.106 (port 3000) after 60000ms

### ISSUE THREAD

**Issue by Anandsoni14** [amitshekhariitbhu/Fast-Android-Networking#154]
Was trying to run it via localhost IP.

**Comment by amitshekhariitbhu** [comment]
There must be some issues with the server. By the way you can configure the timeout. Refer this [link](https://amitshekhariitbhu.github.io/Fast-Android-Networking/configure_timeout.html).

**Comment by Anandsoni14** [comment]
I am working on localhost managed on my another laptop. And things are
working fine Postman.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=anandsoni.india@gmail.com&idSignature=22>

On Sat, Aug 12, 2017 at 8:51 PM, AMIT SHEKHAR <notifications@github.com>
wrote:

> There must be some issues with the server. By the way you can configure
> the timeout. Refer this link
> <https://mailtrack.io/trace/link/cb257f5fa7fa9c227b17ac886f42209f2e25ba52?url=https%3A%2F%2Famitshekhariitbhu.github.io%2FFast-Android-Networking%2Fconfigure_timeout.html&userId=1015939&signature=34eab620acc5c593>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/60d866a7368e45861e4b37bf85cd14702b2bd51d?url=https%3A%2F%2Fgithub.com%2Famitshekhariitbhu%2FFast-Android-Networking%2Fissues%2F154%23issuecomment-321987678&userId=1015939&signature=84644c636f57bcd0>,
> or mute the thread
> <https://mailtrack.io/trace/link/5104e366ab85eacb3d562e83e6905a40f230b41d?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJJE0RSOkvPSWBBBidLGXIacopkIEeAoks5sXcLmgaJpZM4O1Yyx&userId=1015939&signature=aebe89d318280ec2>
> .
>



--

**Comment by johnwatsondev** [comment]
@Anandsoni14 Did you solve this issue? Glad to hear about the progress.

**Comment by amrishkakadiya** [comment]
I am facing same issue, Its working in Postman, but not in Android. And after loading too much shows timeout exception but in postman its done in just few ms.

**Comment by sseninfo** [comment]
Basically it's blocked my firewall. Check your installed firewall and add your displaying IP address and allow them.

**Comment by Das-Dz1307** [comment]
I am facing same issue, Its working in Postman, but not in Android. And after loading too much shows timeout exception but in postman its done in just few ms.

**Comment by bhaveshjethani** [comment]
Facing same issue on specific network carrier!
