### ISSUE TITLE
Multiple upload programmatically

### ISSUE THREAD

**Issue by eihror** [amitshekhariitbhu/Fast-Android-Networking#155]
Hey guys, What´s up?
On this project, i can do upload manually, but i wanna know if is possible to make images multiples upload programmatically.

Thks

**Comment by amitshekhariitbhu** [comment]
Yes, you can do. Refer this [link](https://amitshekhariitbhu.github.io/Fast-Android-Networking/building_a_request.html).

**Comment by eihror** [comment]
Awesome.
Thanks Amit. o/

**Comment by johnwatsondev** [comment]
Hi. @eihror Did we have any problem? We should close this issue if the answer is negative.
