### ISSUE TITLE
why add header is no action

### ISSUE THREAD

**Issue by LOWANGA** [amitshekhariitbhu/Fast-Android-Networking#16]
like this 
public static void postStringJson(String url, HashMap<String,String> params,StringRequestListener listener){
        AndroidNetworking.post(url).addHeaders(getRequestHeader()).addBodyParameter(params).build().getAsString(listener);
    }

    public static HashMap<String,String> getRequestHeader(){
        HashMap<String,String> headParams = new HashMap<>();
        headParams.put("Content-Type", "application/json");
        String token = SharedPreferenceUtil.getInstance(AppApplication.getInstance()).getString(SharedPreferenceUtil.TOKEN);
        if(!StringUtil.isEmpty(token)){
            headParams.put("Authorization","token "+token);
        }
        headParams.put("client","android");

        return headParams;
    }

**Comment by amitshekhariitbhu** [comment]
Just checked, it should work ...may be you should use Authorization Bearer Instead of token.

**Comment by LOWANGA** [comment]
headParams.put("Content-Type", "application/json");  this is no action

**Comment by LOWANGA** [comment]
how to set it Content-Type

**Comment by amitshekhariitbhu** [comment]
For setting custom content type I have aded support.. Will make live in next releas
As of now I have uploaded it on beta.

So please compile using the below link.

compile 'com.amitshekhar.android:android-networking:0.2.0-beta-0'

If there is any problem or suggestion. Tell me.

setContentType("application/json; charset=utf-8") - in post request I have added.

**Comment by amitshekhariitbhu** [comment]
Default content type are added on the basis of body sent to post request . But now you can add this as I explained above

**Comment by LOWANGA** [comment]
ok i will try it ,thanks

**Comment by LOWANGA** [comment]
public static void postStringJson(String url, HashMap<String,String> params,StringRequestListener listener){
        AndroidNetworking.post(url).setContentType("application/json; charset=utf-8").addHeaders(getRequestHeader()).addBodyParameter(params).build().getAsString(listener);
    }
I like this,but my server return this {"code":"server.internal","desc":"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"} error ,so I think it  be covered

**Comment by amitshekhariitbhu** [comment]
Ok will check it and fix it if there is a bug and will inform u

**Comment by LOWANGA** [comment]
thanks

**Comment by LOWANGA** [comment]
is ok?

**Comment by amitshekhariitbhu** [comment]
In the beta version, there is no way to set custom ContentType addBodyParameter, but in other method like addJSONObjectBody, addJSONArrayBody, addStringBody, addFileBody, you can add custom ContentType, I will try to add it in new release. Will inform you soon on new release.

**Comment by LOWANGA** [comment]
thanks  i used addStringBody can do it
