### ISSUE TITLE
How to use Synchronous Request in Service?

### ISSUE THREAD

**Issue by erlangp** [amitshekhariitbhu/Fast-Android-Networking#162]
how to use Synchronous Request in Service?

i got error: `networkOnMainThreadError`

Thanks

**Comment by amitshekhariitbhu** [comment]
Synchronous Request are made to be called from background thread.

**Comment by johnwatsondev** [comment]
@erlangp Please using ThreadPool in normal service or directly using IntentService. Should we close this issue?

**Comment by erlangp** [comment]
ow.. Thanks @amitshekhariitbhu @johnwatsondev 👍
