### ISSUE TITLE
[Feature Request] Batched cancel some request by group tag

### ISSUE THREAD

**Issue by johnwatsondev** [amitshekhariitbhu/Fast-Android-Networking#163]
## Why
We will request network data through serval times from a single fragment or activity. Because of the network request is asynchronous and the user would exit the UI before it finished. As a result, we meet a situation that we need cancel all request in `onDestroyView()` or `onDestroy()` method. This would be painful. It broke the DRY principle.

## The Elegant Way
Can we help developer manage some request by group tag? Each group tag will map to a Map's key.
The map's value is a set of requests. The developer can cancel a couple of requests in once.

```
AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                 .addPathParameter("pageNumber", "0")
                 .addQueryParameter("limit", "3")
                 .addHeaders("token", "1234")
                 .setTag("test")
                 .setGroupTag("TestGroup")
                 .setPriority(Priority.LOW)
                 .build()
                 .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                      // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                      // handle error
                    }
                });   

AndroidNetworking.cancelByGroup("TestGroup");
AndroidNetworking.forceCancelByGroup("TestGroup"); 
```

## The Detail Of Implement
We didn't guarantee the group tag's uniqueness. The developer should keep the all the group tag's uniqueness in the app in another word.

## The Last
I will push a PR for this. 

Thanks for hard work.

**Comment by amitshekhariitbhu** [comment]
This will be a great feature. Expecting the PR :)

**Comment by amitshekhariitbhu** [comment]
@johnwatsondev Are you doing it? As I will be releasing a new version.

**Comment by johnwatsondev** [comment]
@amitshekhariitbhu Yes. I will give a PR this days. :)
