### ISSUE TITLE
We should change the minSdkVersion to 14 in library

### ISSUE THREAD

**Issue by johnwatsondev** [amitshekhariitbhu/Fast-Android-Networking#165]
## Why
Android Support Library has set minSdkVersion to 14. We also set the minSdkVersion to 14 in the production project. There is no meaning that we still use 9 for production ready.

## Log SNAPSHOOT
![jietu20170825-101215 2x](https://user-images.githubusercontent.com/12760754/29697038-472bc832-897f-11e7-9186-7e3069c5ce4c.jpg)

## Discuss
@amitshekhariitbhu Any suggestion for this idea?

**Comment by amitshekhariitbhu** [comment]
We can proceed with the minSdkVersion 14.

**Comment by johnwatsondev** [comment]
I will give this a PR. :)
