### ISSUE TITLE
How to add Authorization header token

### ISSUE THREAD

**Issue by diegohdez90** [amitshekhariitbhu/Fast-Android-Networking#170]
### Is this a bug report or feature request?

I try to get user data after a user is logged in android application.

I have a backend with expressJS and mongodb database.
The express routes has a JWT authentication get user data and then get access to route endpoint (POST, GET).

### Expected behavior

How can I add authorization header (token) to get access in my **JWT authorization** function in expressJS

### Actual behavior

After a user is logged, in the Android Networkon **_get_** function access to user data route **auth/me** but first enter in **JWT authorization** function to get user info but return a empty object and the server send me an error

### Steps to reproduce the behavior

1. After user logged I get JWT token.
2. How to add header JWT token in Android Networkon **_get_** function to use in expressJS **JWT authorization** function.
3. Get user logged data.

**Comment by amitshekhariitbhu** [comment]
As you can customize okHttpClient while initializing it ([refer this link](https://amitshekhariitbhu.github.io/Fast-Android-Networking/custom_okHttpClient.html)) 

One solution can be referred from this [link](http://lgvalle.xyz/2015/07/27/okhttp-authentication/)

Thanks
Amit Shekhar
