### ISSUE TITLE
Leaked Warning

### ISSUE THREAD

**Issue by aschmois** [amitshekhariitbhu/Fast-Android-Networking#171]
Recently started using Android 8.0 and I've been starting to get warnings from OkHttpClient about the body leaking.

This is the error:
````
A connection to http://192.168.1.51:9090/ was leaked. Did you forget to close a response body?
````

This is the only code I'm using referring to OkHttpClient. I don't see how I could close the body from this:

````
OkHttpClient.Builder okHttpClient = new OkHttpClient().newBuilder();
okHttpClient.connectTimeout(1, TimeUnit.SECONDS);
okHttpClient.readTimeout(4, TimeUnit.SECONDS);
requestBuilder.setOkHttpClient(okHttpClient.build());
````

Using Gradle Version 1.0.0

**Comment by amitshekhariitbhu** [comment]
Ok I will check it on Android 8.0.
