### ISSUE TITLE
Possible error messages

### ISSUE THREAD

**Issue by mohsin1122** [amitshekhariitbhu/Fast-Android-Networking#172]
i want to find what possible type of error messages ANError.getErrorDetail() thorws?
i only able to find **connectionError**

plz let me know where to find all errors.

**Comment by phoenixvk** [comment]
What are possible error messages?

**Comment by mbf5923** [comment]
in volley we have different ErrorType like TimeoutError,ServerError,AuthFailureError, etc.
how can get error type in FAN?
