### ISSUE TITLE
com.androidnetworking.error.ANError: com.google.gson.stream.MalformedJsonException

### ISSUE THREAD

**Issue by mohsin1122** [amitshekhariitbhu/Fast-Android-Networking#173]
hi,
i am receiving this error in ANError

> com.androidnetworking.error.ANError: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

that error occured because request was blocked by Web Application Firewall (WAF)

but **getErrorBody()** and **getCause()** return **null**

plz update the library

**Comment by amitshekhariitbhu** [comment]
No way to reproduce it.

**Comment by mohamedhamada1** [comment]
com.androidnetworking.error.ANError: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 159 path $.dateOfBirth


I got same issue

**Comment by hasnain-ahmad** [comment]
@amitshekhariitbhu what will be the reason behind it? @mohsin1122 Did you find the solution..?

**Comment by amitshekhariitbhu** [comment]
@hasnain-ahmad The Json is not valid
