### ISSUE TITLE
Updates? 

### ISSUE THREAD

**Issue by elainedizon** [amitshekhariitbhu/Fast-Android-Networking#174]
Good day sir, when are new updates coming out? as of now the library is using oktthp 3.6.0 and recently released is 3.9.0. Would be nice to get that new update rolling here. Thank you.

**Comment by amitshekhariitbhu** [comment]
Yes, will do it within a week.

**Comment by amitshekhariitbhu** [comment]
Updated OkHttp to 3.9.1 in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
