### ISSUE TITLE
RxJava SIngle instead of Observable

### ISSUE THREAD

**Issue by orikl84** [amitshekhariitbhu/Fast-Android-Networking#176]
Hi,

Wasn't it more logical to make responses to be RxJava Single instead of Observable, as you will get only one response?

**Comment by amitshekhariitbhu** [comment]
Yes, you are correct.  I will do it in the next release.

**Comment by orikl84** [comment]
and don't forget Completable ;)

**Comment by amitshekhariitbhu** [comment]
Added support for `Single`, `Completable`, `Flowable` and `Maybe` in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
