### ISSUE TITLE
setConnectionQualityChangeListener is not working.

### ISSUE THREAD

**Issue by ajitjati** [amitshekhariitbhu/Fast-Android-Networking#177]
###

        AndroidNetworking.setConnectionQualityChangeListener(new ConnectionQualityChangeListener() {
            @Override
            public void onChange(ConnectionQuality currentConnectionQuality, int currentBandwidth) {
                Logger.d("onChange: currentConnectionQuality : " + currentConnectionQuality + " currentBandwidth : " + currentBandwidth);
            }
        });

I have added this method after initializing. When i am turning wifi off/on the onChange is never called

**Comment by amitshekhariitbhu** [comment]
It calls the onChange when the internet speed changes. You will have to make few request to get the effect as it calculate from the network request that you make.
It does not calls when the wifi is turned on/off.

**Comment by ajitjati** [comment]
Thanks Amit.

Can we add this ability to detect network on/off?

**Comment by amitshekhariitbhu** [comment]
We can think of that.
