### ISSUE TITLE
How can I avoid request parameter names getting encoded when making a POST request? 

### ISSUE THREAD

**Issue by kpnkarthik** [amitshekhariitbhu/Fast-Android-Networking#179]
### Is this a bug report or feature request?
I need to avoid request parameter names getting encoded when making a POST request
postRequest.addBodyParameter("token","7aNh79QwvLs+87TAaisq21F+UIkmzLc/5nu0kgMrWD4=");
### Expected behavior
token=7aNh79QwvLs+87TAaisq21F+UIkmzLc/5nu0kgMrWD4=
### Actual behavior
token=7aNh79QwvLs%2B87TAaisq21F%2BUIkmzLc%2F5nu0kgMrWD4%3D

**Comment by amitshekhariitbhu** [comment]
Try addJSON

**Comment by kpnkarthik** [comment]
I have tried with addJSONObject, but the requested json object is acceptable in the server code.
