### ISSUE TITLE
Retry Request

### ISSUE THREAD

**Issue by hank08** [amitshekhariitbhu/Fast-Android-Networking#18]
Is there a way to tell the request to retry on Authentication failure?  My server uses token based authentication and I store the token in the Android Authentication System.  When a request comes back from the server that says the token has expired I would like to be able to tell the authenticator to invalidate the cookie stored in the android system and then to retry the request.  I have set up a custom okhttp client with an interceptor that automatically asks for authentication to be added to each request.  Currently I am unsure how to tell it to retry the request.

**Comment by amitshekhariitbhu** [comment]
@hank08 : This link may help http://stackoverflow.com/questions/24562716/how-to-retry-http-requests-with-okhttp-retrofit

**Comment by hank08** [comment]
Thanks for the speedy response!  I had found a similar link and implemented it as follows.  
However when the authetication error is called the onError(ANError anError) method gets triggered and then the onResponse is never called.  I would have assumed that the returned response would be what gets read and interpreted to determine whether it succeded or not.  So I guess my real question is why doesn't my AFN.onResponse method get fired?

 public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request();
                        request = request.newBuilder()
                                .addHeader("cookie", getAuthentication(context))
                                .build();
                        Response response = chain.proceed(request);
                        if(!response.isSuccessful() && response.code() == 401){
                            Log.d("OKHTTP","401 error unauthenticated");
                            OsiiAccountManager.logout(context, getAuthentication(context),null);
                            Request newRequest = chain.request();
                            newRequest = newRequest.newBuilder()
                                    .addHeader("cookie", getAuthentication(context))
                                    .build();
                            response = chain.proceed(newRequest);
                        }
                        return response;
                    }

**Comment by amitshekhariitbhu** [comment]
Will check it and inform u

**Comment by hank08** [comment]
Sorry, I was having a race condition that was resulting in the authentication invalidating itself after it had gotten a new token.  It is working correctly now.
