### ISSUE TITLE
Support Google Gson JSON Parsing Library ?

### ISSUE THREAD

**Issue by GulajavaMinistudio** [amitshekhariitbhu/Fast-Android-Networking#180]
### feature request
Support for Gson library for serialize and deserialize JSON
https://github.com/google/gson

Since it more lightweight than Jackson.

**Comment by anandgaurav10** [comment]
@GulajavaMinistudio by default it uses GSON.

**Comment by GulajavaMinistudio** [comment]
Oke thanks, close it now
