### ISSUE TITLE
prior setted Cookies not exist in server when use a new AndroidNetworking.post

### ISSUE THREAD

**Issue by abolfazlrma** [amitshekhariitbhu/Fast-Android-Networking#182]

**Comment by amitshekhariitbhu** [comment]
please explain more

**Comment by abolfazlrma** [comment]
Actually i have an AnImageView, when i call method anImageView.setImageUrl("img_url"); the called url return a png captcha image, simultaneous some cookies are sets, but when user enter the captcha an post it with AndroidNetworking.post, already setted cookies have null values,

**Comment by amitshekhariitbhu** [comment]
Refer [this](https://amitshekhariitbhu.github.io/Fast-Android-Networking/cookie.html).

**Comment by abolfazlrma** [comment]
thank you, i could give cookies.
