### ISSUE TITLE
why the totalBytes =-1 in the onProgress() method

### ISSUE THREAD

**Issue by invisible66** [amitshekhariitbhu/Fast-Android-Networking#185]
I want to download a file with progress button but totalBytes -1. what is wrong?

     AndroidNetworking.download(faxType.getFileUrl(),"/storage/","test_xxx.pdf")
                                .setTag("downloadFile")
                                .setPriority(Priority.HIGH)
                                .build()
                                .setDownloadProgressListener(new DownloadProgressListener() {
                                    @Override
                                    public void onProgress(long bytesDownloaded, long totalBytes) {
                                        // do anything with progress
                                        Log.i("****",bytesDownloaded+" - "+totalBytes+" = "+(100*bytesDownloaded/totalBytes));
                                        circularButton1.setProgress((int)(100*bytesDownloaded/totalBytes));
                                    }
                                })
                                .startDownload(new DownloadListener() {
                                    @Override
                                    public void onDownloadComplete() {
                                        // do anything after completion
                                        circularButton1.setProgress(100);
                                    }
                                    @Override
                                    public void onError(ANError error) {
                                        // handle error
                                        circularButton1.setProgress(-1);
                                    }
                                });`

**Comment by agl-developer** [comment]
Does your server set the "Content-Length" header? That might be the issue.
