### ISSUE TITLE
ANImageView's method setDefaultImageResId(R.drawable.default); remove Image on touch

### ISSUE THREAD

**Issue by Inzimam-Tariq** [amitshekhariitbhu/Fast-Android-Networking#186]
### Is this a bug report 
Please fix ANImageView to show Default Image Until set manually.

### Expected behavior
Default Image set should persist until we set image path as mentioned in docs `mageView.setImageUrl(imageUrl);`
I'm using it inside ExpandableListView to show Parent Category Images. Some of my Categories are fix (hardcoded) so I want this `ANImageView` to set default image for that and there is no need to change their image at all. So I do not suppose them to remove images when I click on them or unless I provide image path to change Image.

### Actual behavior
It remove the default image that I set as `imageView.setDefaultImageResId(R.drawable.default);` that is the case in `ExpandableListView` I have not test it otherwise outside `ExpandableListView`.

**Comment by Inzimam-Tariq** [comment]
Hi,
Is anyone maintaining this Library?

**Comment by amitshekhariitbhu** [comment]
Ok, I will check it.
