### ISSUE TITLE
FATAL EXCEPTION  when deserialization throws an exception

### ISSUE THREAD

**Issue by szendo** [amitshekhariitbhu/Fast-Android-Networking#187]
### Is this a bug report or feature request?
This is  **bug report**

### Expected behavior
If **deserialize** throws an exception, it should print error and call onError()

### Actual behavior
It didn't call onError but throws Fatal Exception and kills application :(

![image](https://user-images.githubusercontent.com/8846466/32317660-d2f47092-bfb4-11e7-989c-9ef69578bfc0.png)

### Steps to reproduce the behavior

1) Create an deserialization that throws an exception:
```
public class TickerDeserializer implements JsonDeserializer<Ticker> {
    @Override
    public Ticker deserialize(final JsonElement json, final Type typeOfT, final JsonDeserializationContext context) {
        throw new JsonParseException("");
    }
}
```
2) Register deserializer
3) Prepare an request and subscribe.
```
Rx2AndroidNetworking
                .get(someUrl)
                .build()
                .getObjectObservable(Ticker.class)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe();
```

**Comment by amitshekhariitbhu** [comment]
Ok, got it, we will handle it in the new release. You can raise a PR for this. :)

**Comment by szendo** [comment]
It's default ERROR_CONSUMER from Observable.... so it's not a bug, it's a feature.
Can be closed.
