### ISSUE TITLE
Is there any way to prevent from having multiple same request?

### ISSUE THREAD

**Issue by anderscheow** [amitshekhariitbhu/Fast-Android-Networking#188]
I'm not sure is it because of device problem, sometimes I'm having an issue where some clients accidentally send multiple same request to server, but server already handle that by sending error back to client. Is it possible to prevent this?

**Comment by amitshekhariitbhu** [comment]
Currently it's not present. I will be adding this in new release.

**Comment by anderscheow** [comment]
Thanks, but when are you going to release new version

**Comment by hasnain-ahmad** [comment]
@amitshekhariitbhu have you add the above-said functionality.

**Comment by hasnain-ahmad** [comment]
> @amitshekhariitbhu have you add the above-said functionality.

Sir reminder for it.

**Comment by JalalJanKhan3336** [comment]
Hi there, I'm working with Fast Android Networking Library to send request to server and get back response from the server. It works perfectly, but sometimes when User clicks on a button say **Mark Punch In** to mark User's attendance & another button say **Mark Punch Out** to Update User's attendance. It sends multiple requests i.e. if User clicks on **Mark Punch In** button the **Fast Android Networking** library sends a post request to server and waits for the response if it doesn't get response within httpok specified time, it sends same request again and Server adds these two records into database.

How to prevent sending multiple same requests to Server in **Fast Android Networking**. Kindly do response if anyone has already fix this issue.

Regards,

**Comment by OVL** [comment]
@JalalJanKhan3336 , the best approach is server side ... use a unique request identifier , and check for duplicate on server side..
if (duplicate) ignore ...
