### ISSUE TITLE
Incomplete URLs

### ISSUE THREAD

**Issue by hank08** [amitshekhariitbhu/Fast-Android-Networking#19]
Is it possible to set only the path of the url but not the host.  I would like to have the request be something like AndroidNetworking.get("/the/coolest/endpoint/ever")...
Then in the interceptor I will append the server to the front of the request before sending it.
`public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request();
                        request = request.newBuilder()
                                .url("https://myServer"+request.url().toString())
                                .addHeader("cookie", getAuthentication(context))
                                .build();
                        Response response = chain.proceed(request);`

Currently when I do this the onError method gets fired with the following. 
`java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder()' on a null object reference`

Also it never gets to the interceptor to inject the first part of the url

**Comment by amitshekhariitbhu** [comment]
No
