### ISSUE TITLE
POST & Upload Method

### ISSUE THREAD

**Issue by saad129** [amitshekhariitbhu/Fast-Android-Networking#190]
Is there any way to send data and image at same time?
Like if click button then post and upload method will send data at same time
i want to send image and post data

**Comment by amitshekhariitbhu** [comment]
Yes use upload method

**Comment by saad129** [comment]
Sure. 
But i've list of images 
and i'm using  .addMultipartFile("images",uploadImage.get(i)) in loop
and in multipartparameter is   .addMultipartParameter("user_id","2")
loop will size time work and multipartparameter updated in each iteration. how can i avoid this thing that only uploadimage will be in loop not multipartparameters

**Comment by amitshekhariitbhu** [comment]
Refer this [link](https://amitshekhariitbhu.github.io/Fast-Android-Networking/building_a_request.html)

**Comment by saad129** [comment]
There is not enough explanation there!
can you explain for me?

**Comment by saad129** [comment]
According to your link. i'll use addpathparameter for images too?
because there is not option for addmultipartfile for images according to that link

**Comment by saad129** [comment]
for(int i=0; i<uploadImage.size();i++) {
                    getMultiRequestBuilder.addMultipartFile("images", uploadImage.get(i));
                }
             
Above code will over write images key or not? 
because i want all images so this thing according 
ANRequest.MultiPartBuilder getMultiRequestBuilder=new ANRequest.MultiPartBuilder<>(config.AddProperty);

**Comment by amitshekhariitbhu** [comment]
Currently, all the images must be added with the different key.

**Comment by saad129** [comment]
Sure.. but can you tell me the way how to upload multiple pictures with same key?
because i want to send all photos with "images" as a key

**Comment by shyamsathyanathan** [comment]
Why don't you send the images in Base64?
