### ISSUE TITLE
MultiPartBuilder parameters as int

### ISSUE THREAD

**Issue by ChaconC** [amitshekhariitbhu/Fast-Android-Networking#191]
I'm trying to make an upload request using MultiPartBuilder, I've got everything working except
`builder.addMultipartParameter("key", "value");` this method expects a String value.

The webservice I'm working with requires an int value and I'm unable to change that.

Is there anyway to add parameters as something other than String? I tried using `addMultipartObject` but that just maps it back to String.

**Comment by amitshekhariitbhu** [comment]
For now, you can use `String.valueOf(variable)`

**Comment by ChaconC** [comment]
Thanks, I was afraid that would be the case.
Sadly that solution doesn't work for this specific webservice, since it's converting the value to a double quote (something like "1" to "\"1\"") and fails.

I understand that's not a problem on your end. Thanks!
