### ISSUE TITLE
AndroidNetworking.getCurrentConnectionQuality() always returns UNKNOWN

### ISSUE THREAD

**Issue by pacifire** [amitshekhariitbhu/Fast-Android-Networking#192]
### BUG REPORT:
Internet is switched OFF, then AndroidNetworking.getCurrentConnectionQuality() returns UNKNOWN
Internet is switched OFF, then AndroidNetworking.getCurrentBandwidth() returns 0.

Switch ON the WIFI, then also, AndroidNetworking.getCurrentConnectionQuality() returns UNKNOWN.
Switch ON the WIFI, then also, AndroidNetworking.getCurrentBandwidth() returns 0.

### Steps to reproduce the behavior
Switch off the WIFI:
Install  the Sample app given on Github, run the "app i.e. AndroidNetworking"
Click on "STARTOKHTTPRESPONSETESTACTIVITY", then click on "GETCURRENTCONNECTIONQUALITY"
**O/P: getCurrentConnectionQuality : UNKNOWN currentBandwidth : 0**

NOW Click the same button "GETCURRENTCONNECTIONQUALITY" after switching ON the WIFI,
the output will be the same:
**O/P: getCurrentConnectionQuality : UNKNOWN currentBandwidth : 0**

### Expected behavior
When WIFI is ON, the output should be different, as compared when there is no Internet connection.

**Comment by amitshekhariitbhu** [comment]
It's start giving internet speed after some network calls.
