### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: SSL Handshake Aborted

### ISSUE THREAD

**Issue by eniserkaya** [amitshekhariitbhu/Fast-Android-Networking#194]
When i try to DOWNLOAD image or any file, some devices( i get error device which is android version 6.0.1) get error like this
 -- > javax.net.ssl.SSLHandshakeException: SSL Handshake Aborted: ssl = 0xb8804: I/O error during system call, Connection reset by peer.

And Then
When i try to UPLOAD image or any file, some devices get error from network library like this:
--> Problem while transferring data, sorry. Email me please! "

Urgent help please.

**Comment by amitshekhariitbhu** [comment]
Please provide more information if possible. I am looking into the issue.

**Comment by eniserkaya** [comment]
The devices which getting error :  http://vestelsmartphone.com/phone/vestel-5000.html

**Comment by amitshekhariitbhu** [comment]
Not able to reproduce it.
