### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/MediaType;]

### ISSUE THREAD

**Issue by xtagwgj** [amitshekhariitbhu/Fast-Android-Networking#195]
I made the following request:   

       fun findAllGroup(): Observable<MutableList<GroupEntity>> {
            return Rx2AndroidNetworking.get(getBaseUrl() + "/app/group")
                    .addHeaders(headerMap)
                    .setPriority(Priority.IMMEDIATE)
                    .build()
                    .getObjectListObservable(GroupEntity::class.java)
                    .map { it.toMutableList() }
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
        }

 But it crash as follow

    W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/MediaType;
    W/System.err:     at com.androidnetworking.common.ANRequest.<clinit>(ANRequest.java:101)
    W/System.err:     at com.rx2androidnetworking.Rx2ANRequest$GetRequestBuilder.build(Rx2ANRequest.java:155)
    W/System.err:     at com.xbdl.flalexaclock.http.HttpRequest.findAllGroup(HttpRequest.kt:238)
    W/System.err:     at com.xbdl.flalexaclock.utils.ClockUtils.refreshAllGroup(ClockUtils.kt:243)
    W/System.err:     at com.xbdl.flalexaclock.ui.MainActivity.initEventListener(MainActivity.kt:187)
    W/System.err:     at com.xtagwgj.baseproject.base._BaseActivity.onCreate(_BaseActivity.java:42)
    W/System.err:     at android.app.Activity.performCreate(Activity.java:6100)
    W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
    W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
    W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
    W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:178)
    W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
    W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
    W/System.err:     at android.os.Looper.loop(Looper.java:194)
    W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5643)
    W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
    W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
    W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.MediaType" on path: DexPathList[[zip file "/data/app/com.xbdl.flalexaclock-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xbdl.flalexaclock-1/lib/arm, /vendor/lib, /system/lib]]
    W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    W/System.err: 	... 19 more
    W/System.err: 	Suppressed: java.lang.ClassNotFoundException: okhttp3.MediaType
    W/System.err:     at java.lang.Class.classForName(Native Method)
    W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
    W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
    W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    W/System.err: 		... 20 more

**Comment by amitshekhariitbhu** [comment]
Let me check it with kotlin once

**Comment by amitshekhariitbhu** [comment]
Not able to reproduce it.

**Comment by jatinderrana** [comment]
packagingOptions {
               exclude 'META-INF/Lokhttp3/MediaType'
    }

Please Use this line may be some conflict-ion in 2 library

**Comment by amitshekhariitbhu** [comment]
@jatinderrana Great. Thanks for the helping others on this issue.
