### ISSUE TITLE
okhttp update

### ISSUE THREAD

**Issue by guyulmaz** [amitshekhariitbhu/Fast-Android-Networking#198]
Hello,
is there any plan to update okhttp to the latest version
targetSdkVersion 23 to 27
compileSdkVersion 23 to 27
buildToolsVersion "23.0.3" to '26.0.2'
com.android.support:appcompat-v7:23.2.1 to v7:27.0.2
'com.google.code.gson:gson:2.8.0' to 2.8.2
'com.squareup.okhttp3:mockwebserver:3.6.0' to 3.9.1

**Comment by tomxposed** [comment]
amit sir pls update it quickly👍

**Comment by amitshekhariitbhu** [comment]
@tomxposed @guyulmaz I will update it soon.

**Comment by amitshekhariitbhu** [comment]
Updated in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
