### ISSUE TITLE
How to handle snake_case field using getObjectObservable?

### ISSUE THREAD

**Issue by mishbah** [amitshekhariitbhu/Fast-Android-Networking#201]
What should we do, if we handle api with snake_case data like `city_id`, or `first_name`
Example:
```
{
  "data": [
    {
      "id": 1,
      "first_name": "Jhon Anton"
    },
    {
      "id": 2,
      "first_name": "Lisa Walker"
    },
  ]
}
```
And our db (sqlite) using camelCase like `cityId` or `firstName`

Thanks.

**Comment by amitshekhariitbhu** [comment]
It works in the snake_case also.
