### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by samyotech** [amitshekhariitbhu/Fast-Android-Networking#203]
Hello Amit, 
Thanks for such a good and perfect library. I am very happy to use.
I am facing one problem please help me in that. My APIs is working perfect on PostMan and other Http client but some time in Android Networking case APIs respond me -
**java.net.SocketTimeoutException**

**com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: java.net.SocketTimeoutException: failed to connect to /164.132.170.155 (port 80) from /192.168.1.2 (port 49757) after 60000ms**

I don't know y way ? Sometimes it works but some time is not ?
Please suggest me what should I do ?

Thanks
Amit

**Comment by amitshekhariitbhu** [comment]
One way can be you can increase the time out by customizing the okhttp client and pass it while initializing the library.
