### ISSUE TITLE
Some devices can't handle multiple Headers

### ISSUE THREAD

**Issue by KSas** [amitshekhariitbhu/Fast-Android-Networking#204]
On some devices, only one header is sent with a GET or POST request instead of several headers.

```
AndroidNetworking.post(API)
	.addPathParameter("requestName", reqParam)
	.addHeaders(getHeaders())
	.setPriority(Priority.HIGH)
	.addBodyParameter(postParam)
	.build()
	.getAsJSONObject(new JSONObjectRequestListener() {
		public void onResponse(JSONObject response) {
			if(BuildConfig.DEBUG){
				Log.v("A", response);
			}
			
			// do somthing
		}

		public void onError(ANError anError) {
			Log.d(TAG, "onError errorDetail : " + anError.getErrorDetail());
		}
	});

private HashMap<String, String> getHeaders(){

        HashMap<String, String> headers = new HashMap<>();
		
        headers.put("DeviceID", getDeviceAuthID());
        headers.put("AppVersionCode", getVersionCode() + "");
        headers.put("AppVersionName", getVersionName());
        headers.put("DeviceName", getDeviceName());
        headers.put("PhoneName", getPhoneName());
        headers.put("PhoneVersionCode", android.os.Build.VERSION.SDK_INT + "");
        headers.put("PhoneVersionName", android.os.Build.VERSION.RELEASE);

        return headers;
    }
```

On a Pixel XL:

> HEADER:
> array(13) {
>   ["PhoneName"]=>
>   string(9) "Sascha K."
>   ["AppVersionCode"]=>
>   string(1) "1"
>   ["DeviceID"]=>
>   string(16) "d917a87f108ff4a8"
>   ["AppVersionName"]=>
>   string(9) "1.0-DEBUG"
>   ["PhoneVersionName"]=>
>   string(5) "8.1.0"
>   ["PhoneVersionCode"]=>
>   string(2) "27"
>   ["DeviceName"]=>
>   string(15) "Google Pixel XL"
>   ["Content-Type"]=>
>   string(33) "application/x-www-form-urlencoded"
>   ["Content-Length"]=>
>   string(4) "1376"
>   ["Connection"]=>
>   string(10) "Keep-Alive"
>   ["Accept-Encoding"]=>
>   string(4) "gzip"
>   ["User-Agent"]=>
>   string(12) "okhttp/3.6.0"
> }

On Samsung Galaxy S5 Mini:
> HEADER:
> array(7) {
>   ["AppVersionCode"]=>
>   string(1) "1"
>   ["Content-Type"]=>
>   string(33) "application/x-www-form-urlencoded"
>   ["Content-Length"]=>
>   string(4) "1389"
>   ["Connection"]=>
>   string(10) "Keep-Alive"
>   ["Accept-Encoding"]=>
>   string(4) "gzip"
>   ["User-Agent"]=>
>   string(12) "okhttp/3.6.0"
> }

**Comment by amitshekhariitbhu** [comment]
This is weird. Will check it.
