### ISSUE TITLE
Strange problem 

### ISSUE THREAD

**Issue by amervelic** [amitshekhariitbhu/Fast-Android-Networking#21]
I have a strange problem. I use a simple HTTP POST form for authentication, use two accounts with different user credentials (username and passowrd). Often, to sign up with one account and http data are from  other. I tried it with Android Asynchronous HTTP Client (http://loopj.com/android-async-http) and the problem did not show up ... I do not understand how this is possible

**Comment by amervelic** [comment]
The problem occurs only on 3G. On Wifi, these problems do not occur

**Comment by amitshekhariitbhu** [comment]
@amervelic : can u provide more detail about the request u r making?

**Comment by amervelic** [comment]
@Override
    public void onCreate() {
        super.onCreate();

        mInstance = this;
        
        SetCookieCache setCookieCache = new SetCookieCache();
        setCookieCache.clear();
               cookieJar = new PersistentCookieJar(setCookieCache,
                          new SharedPrefsCookiePersistor(getApplicationContext()));

        cookieJar.clear();


        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
               .cookieJar(cookieJar)
               .retryOnConnectionFailure(true)
               .writeTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
               .readTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
               .connectTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
               .build();

        AndroidNetworking.initialize(getApplicationContext(),okHttpClient);
        AndroidNetworking.setUserAgent(USER_AGENT);
        AndroidNetworking.enableLogging();
        AndroidNetworking.setConnectionQualityChangeListener(new ConnectionQualityChangeListener() {
            @Override
            public void onChange(ConnectionQuality currentConnectionQuality, int currentBandwidth) {
                Log.d(TAG, "onChange: currentConnectionQuality : " + currentConnectionQuality + " currentBandwidth : " + currentBandwidth);
            }
        });

}


public static void login(String username, String password, StringRequestListener stringRequestListener , AnalyticsListener analyticsListener) {


        AndroidNetworking.post(BASE_URL)
                .addBodyParameter("korisnickoIme", username)
                .addBodyParameter("lozinka", password)
                .setTag(getInstance())
                .setPriority(Priority.HIGH)
                .doNotCacheResponse()
                .build()
                .setAnalyticsListener(analyticsListener)
                .getAsString(stringRequestListener);



    }

**Comment by amitshekhariitbhu** [comment]
@amervelic : what is the exact problem u r facing here ?

**Comment by amervelic** [comment]
I enrolled problem above , but I managed to solve it . I turn off the cache in your source code and is now working properly

**Comment by amitshekhariitbhu** [comment]
Ok
