### ISSUE TITLE
Exception java.lang.NoClassDefFoundError: okhttp3.MediaType 

### ISSUE THREAD

**Issue by syahnurizal** [amitshekhariitbhu/Fast-Android-Networking#211]
I got this error when running on Xiaomi Redmi Note 2.
Anyone know what is the issue?

**Comment by amitshekhariitbhu** [comment]
Please provide more detail like Android version

**Comment by syahnurizal** [comment]
The phone is running API level  19

**Comment by syahnurizal** [comment]
@amitshekhariitbhu do you know the error that causes this?

**Comment by amitshekhariitbhu** [comment]
r u using multidex?

**Comment by syahnurizal** [comment]
yes

**Comment by amitshekhariitbhu** [comment]
Not sure why. But this can be issue because of loading multiple dex.
