### ISSUE TITLE
Failed to upload file when using HttpLoggingInterceptor

### ISSUE THREAD

**Issue by erlangp** [amitshekhariitbhu/Fast-Android-Networking#213]
### Is this a bug report or feature request?

This is a bug report

### Version of the library

    api 'com.amitshekhar.android:android-networking:1.0.0'

### Steps to Reproduce

    HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
    interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    builder.addInterceptor(interceptor);

    ANRequest request = AndroidNetworking.upload(url)
            .addMultipartFile(PARAM_FILE, file)
            .addMultipartParameter(PARAM_TOKEN, token)
            .setOkHttpClient(builder.build())
            .build();

### Expected Behavior

Success uploading file and showing response body on logcat

### Actual Behavior

Fail uploading file and showing error `HTTP FAILED: java.net.ProtocolException: unexpected end of stream` on logcat

**Comment by erlangp** [comment]
@amitshekhariitbhu Thanks before 🙏

**Comment by amitshekhariitbhu** [comment]
This is issue with okhttp logger

**Comment by amitshekhariitbhu** [comment]
It works with header level logging
