### ISSUE TITLE
Multipart Upload Error: NullPointerException at okhttp3.RequestBody.create

### ISSUE THREAD

**Issue by athasamid** [amitshekhariitbhu/Fast-Android-Networking#217]
i trying to upload image to my server, but only multipart parameter were sent, but not mulipart file

here my code
`OkHttpClient client =  new OkHttpClient
                .Builder()
                .connectTimeout(15, TimeUnit.SECONDS)
                .build();

        AndroidNetworking.enableLogging();

        Log.e("file", fileGambar.getAbsolutePath());

        AndroidNetworking.upload(Const.KEGIATAN)
                .setOkHttpClient(client)
                .addHeaders("Authorization", Const.token())
                .addHeaders("Accept", "application/json")
                .addMultipartFile("foto", fileGambar)
                .addMultipartParameter("id_jenis_kegiatan", selectedJenis.id + "")
                .addMultipartParameter("kegiatan", kejadian.getText().toString())
                .addMultipartParameter("lokasi", lokasi.getText().toString())
                .addMultipartParameter("keterangan", keterangan.getText().toString())
                .addMultipartParameter("id_anggaran", selectedAnggaran == null ? null : selectedAnggaran.id + "")
                .addMultipartParameter("progress", prosess.getText().toString().replaceAll("\\D+", ""))
                .addMultipartParameter("selesai", radioSelesai.isChecked() + "")
                .setPriority(Priority.HIGH)
                .build()
                .setUploadProgressListener(new UploadProgressListener() {
                    @Override
                    public void onProgress(long bytesUploaded, long totalBytes) {
                        int percentUploaded = (int) ((bytesUploaded * 100) / totalBytes);
                        Log.e("Percent", percentUploaded+"");
                        progressBarUpload.setProgress(percentUploaded);
                    }
                })
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                        if (response.has("success")) {
                            Toast.makeText(NewKegiatanActivity.this, "Kegiatan berhasil di tambah", Toast.LENGTH_SHORT).show();
                            NewKegiatanActivity.this.setResult(RESULT_OK);
                            finish();
                        } else {
                            Toast.makeText(NewKegiatanActivity.this, "Terjadi kesalahan", Toast.LENGTH_SHORT).show();
                        }
                        progressBarUpload.setVisibility(View.GONE);
                    }

                    @Override
                    public void onError(ANError anError) {
                        Const.errorHandler(NewKegiatanActivity.this, anError);
                        progressBarUpload.setVisibility(View.GONE);
                    }
                });`

error 

> java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
     at okhttp3.RequestBody.create(RequestBody.java:56)
     at com.androidnetworking.common.ANRequest.getMultiPartRequestBody(ANRequest.java:859)
     at com.androidnetworking.internal.InternalNetworking.performUploadRequest(InternalNetworking.java:227)
     at com.androidnetworking.internal.InternalRunnable.executeUploadRequest(InternalRunnable.java:123)
     at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:61)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
     at java.lang.Thread.run(Thread.java:818)

**Comment by amitshekhariitbhu** [comment]
Try after disabling logging

**Comment by athasamid** [comment]
still didn't work

**Comment by athasamid** [comment]
my gradle 

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "digital.synergics.www.testupload"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.amitshekhar.android:android-networking:1.0.1'
    compile 'com.github.darsh2:MultipleImageSelect:v0.0.4'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
}`

**Comment by athasamid** [comment]
sorry, this is my fault, there is null in my parameter
