### ISSUE TITLE
Android 6 Can not connect to server support SSLV3 and TLS 1.0 only

### ISSUE THREAD

**Issue by victory1908** [amitshekhariitbhu/Fast-Android-Networking#22]
Hi I have a strange issue while using library to make post to Server which only support SSL v3 and TLS 1.0 only. Our request work fine with API level 22 and below. Only when use with android API 23 (android 6+) I have connection error

 this my code to make POST request

`String url2 = "https://prdesb1.singpost.com/ma/GetItemTrackingDetails";`

`final String payload2 = "<ItemTrackingDetailsRequest xmlns=\"http://singpost.com/paw/ns\"><ItemTrackingNumbers><TrackingNumber>SMT0000000628</TrackingNumber></ItemTrackingNumbers></ItemTrackingDetailsRequest>";`

```
AndroidNetworking.initialize(this);
        AndroidNetworking.post(url2)
                .addHeaders("Content-Type","application/xml")
                .addByteBody(payload2.getBytes())
                .build()

                .getAsString(new StringRequestListener() {
                    @Override
                    public void onResponse(String response) {
                        Log.v("successAndroid1",response);
                    }

                    @Override
                    public void onError(ANError anError) {
                        Log.v("FailAndroidDetail",anError.getErrorDetail());
                        Log.v("FailAndroidBody",anError.getData().toString());


                        Log.v("FailAndroidCode",String.valueOf(anError.getErrorCode()));
                     }
                });
```

this only happen with android 6+. I have added all the necessary permission

**Comment by amitshekhariitbhu** [comment]
@victory1908  - I am try to figure it out. For time being check this out http://stackoverflow.com/questions/27112082/httpclient-fails-with-handshake-failed-in-android-5-0-lollipop

**Comment by victory1908** [comment]
Thanks i'll try to dig into it. The problem only happen on android 6+. Android 5 (api 22 Loilipop) still work normally.
