### ISSUE TITLE
how to config cache with this?

### ISSUE THREAD

**Issue by wenjiangit** [amitshekhariitbhu/Fast-Android-Networking#220]
when network is available, get data from net ,otherwise get data from cache   like  below
` Interceptor cacheInterceptor = new Interceptor() {
            @Override
            public Response intercept(@NonNull Chain chain) throws IOException {
                Request request = chain.request();
                //没网强制走缓存
                if (!NetworkUtils.isNetworkAvailable()) {
                    request.newBuilder()
                            .cacheControl(CacheControl.FORCE_CACHE)
                            .build();

                }

                Response response = null;
                try {
                    response = chain.proceed(request);
                    //有网不缓存,最大保存时长为0
                    if (NetworkUtils.isNetworkAvailable()) {
                        response.newBuilder()
                                .header("Cache-Control", "public, max-age=" + 0)
                                .removeHeader("Pragma")
                                .build();
                    } else {
                        //没网进行,保存时间为4周
                        response.newBuilder()
                                .header("Cache-Control", "public, only-if-cached, max-stale=" + MAX_STALE)
                                .removeHeader("Pragma")
                                .build();

                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }

                return response;
            }
        };`

**Comment by amitshekhariitbhu** [comment]
[Here is the detailed explanation.](https://amitshekhariitbhu.github.io/Fast-Android-Networking/caching.html)

**Comment by wenjiangit** [comment]
I define a okhttp instance to init AndroidNetworking, add a intercept with it ,but it dot work ,and give me a exception  : java.net.UnknownHostException    why?


`Interceptor cacheInterceptor = new Interceptor() {
            @Override
            public Response intercept(@NonNull Chain chain) throws IOException {
                Request request = chain.request();
                //没网强制走缓存
                if (!NetworkUtils.isNetworkAvailable()) {
                    request.newBuilder()
                            .cacheControl(CacheControl.FORCE_CACHE)
                            .build();

                }

                Response response = null;
                try {
                    response = chain.proceed(request);
                    //有网不缓存,最大保存时长为0
                    if (NetworkUtils.isNetworkAvailable()) {
                        response.newBuilder()
                                .header("Cache-Control", "public, max-age=" + 0)
                                .removeHeader("Pragma")
                                .build();
                    } else {
                        //没网进行,保存时间为4周
                        response.newBuilder()
                                .header("Cache-Control", "public, only-if-cached, max-stale=" + MAX_STALE)
                                .removeHeader("Pragma")
                                .build();

                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }

                return response;
            }
        };`
