### ISSUE TITLE
Rx2AndroidNetworking adding Interceptor

### ISSUE THREAD

**Issue by daniftodi** [amitshekhariitbhu/Fast-Android-Networking#223]
Hi,

I would like to use Chuck (https://github.com/jgilfelt/chuck) as network interceptor, how it is possible to do this in Rx2AndroidNetworking ?

**Comment by amitshekhariitbhu** [comment]
Yes init with AndroidNetworking.initialize(context, client)

**Comment by daniftodi** [comment]
I'm doing requests this way:

```
Rx2AndroidNetworking.post(ApiEndPoint.ENDPOINT_SERVER_LOGIN)
                    .addHeaders(apiHeader.publicApiHeader)
                    .addBodyParameter(request)
                    .build()
```


I have looked and rx2sampleapp but can't understand how is related:

```
AndroidNetworking.initialize(getApplicationContext());
        AndroidNetworking.enableLogging();
        AndroidNetworking.setConnectionQualityChangeListener(new ConnectionQualityChangeListener() {
            @Override
            public void onChange(ConnectionQuality currentConnectionQuality, int currentBandwidth) {
                Log.d(TAG, "onChange: currentConnectionQuality : " + currentConnectionQuality + " currentBandwidth : " + currentBandwidth);
            }
        });
```
https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/rx2sampleapp/src/main/java/com/rx2sampleapp/Rx2MyApplication.java

With requests that are made in file: https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/rx2sampleapp/src/main/java/com/rx2sampleapp/Rx2ApiTestActivity.java

**Comment by amitshekhariitbhu** [comment]
@daniftodi basically Rx2AndroidNetworking used AndroidNetworking internally. You can refer this also https://amitshekhariitbhu.github.io/Fast-Android-Networking/custom_okHttpClient.html

**Comment by daniftodi** [comment]
@amitshekhariitbhu thank you for your response. but how to pass AndroidNetworking instance to Rx2AndroidNetworking ?

**Comment by amitshekhariitbhu** [comment]
You just have to init with `AndroidNetworking`, it will handle internally.

**Comment by daniftodi** [comment]
I have the solution. I have to init an OkHttpClient, set on it the interceptors and use the setter from Rx2AndroidNetworking  for setting my initialized OkHttpClient.
