### ISSUE TITLE
javax.servlet.ServletException: Could not resolve view with name‘ XXXX’in servlet 

### ISSUE THREAD

**Issue by liudao01** [amitshekhariitbhu/Fast-Android-Networking#224]
javax.servlet.ServletException: Could not resolve view with name‘ XXXX’in servlet with name 'spring'

This error occurs using the network framework, but I can use httpurlconnection to return the data

**Comment by amitshekhariitbhu** [comment]
Please give more detail.

**Comment by liudao01** [comment]
![image](https://user-images.githubusercontent.com/5665224/35431180-7218c3fa-02b6-11e8-801e-7667758f0350.png)

**Comment by liudao01** [comment]
Problem solving
