### ISSUE TITLE
Adding json converter

### ISSUE THREAD

**Issue by daniftodi** [amitshekhariitbhu/Fast-Android-Networking#227]
Hi,

I'm interested in changing the date format that is used when converting from POJO objects to JSON and back.

I would like create an instance of Gson and pass it to this library as json converter:
Example:

```
val gson = GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ssz")
                .create()

Rx2AndroidNetworking.setConverter(gson);
```

**Comment by amitshekhariitbhu** [comment]
Use AndroidNetworking.setConvertorFactory

**Comment by daniftodi** [comment]
@amitshekhariitbhu thank you for your response, unfortunately I can't find this method in AndroidNetworking class.

**Comment by amitshekhariitbhu** [comment]
AndroidNetworking.setParserFactory.

**Comment by xj913492952** [comment]
why Rx2AndroidNetworking can not custom json response parser?

**Comment by amitshekhariitbhu** [comment]
What error you are getting
