### ISSUE TITLE
opt is not working correctly

### ISSUE THREAD

**Issue by Inzimam-Tariq** [amitshekhariitbhu/Fast-Android-Networking#229]
I'm getting data from server and using the below code.

- keysStrList is a list containing keys available in response

- myAllItemsList is a list of Type Object.

```
if (keysStrList.get(a).equals("banner")) {
          JSONObject promotionObject = modules.optJSONObject("banner");
          Slideshow banner = new Slideshow(
               promotionObject.optString("banner"),
               promotionObject.optString("id"),
               promotionObject.optString("banertype"));
          myAllItemsList.add(banner);
  }
```
Everything was working fine But un-intentionally the banner in above code that is of type Object set to of type Array. Now when I run the app it close forcefully and point me to the line 
`promotionObject.optString("banner")`
I know there is no Object present there but I'm using `optJSONObject` and `optString` they should simply skip this if not available else what is the purpose of `opt`.
Similarly I have observed that if `JSONObject` has invalid JSON or have empty sting it closes the app to rather than throwing the exception even if its inside the try{}catch{} blocks.

Please fix these issues as soon as possible. OR Let me know if the alternative way is available.
Thanks

@amitshekhariitbhu , @PrashantGupta17

**Comment by amitshekhariitbhu** [comment]
I will check and update in new release.
