### ISSUE TITLE
cancelTag someTime is not taken into effect 

### ISSUE THREAD

**Issue by LOWANGA** [amitshekhariitbhu/Fast-Android-Networking#23]
```
public void cancelRequestWithGivenTag(final Object tag, final boolean forceCancel) {
        try {
            if (tag == null) {
                return;
            }
            cancel(new RequestFilter() {
                @Override
                public boolean apply(ANRequest request) {
                    return request.getTag() == tag;
                }
            }, forceCancel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

if I used like this 
```
public static void uploadFile(String url,String tag,HashMap<String, String> params, String key,File file, UploadProgressListener uploadProgressListener, StringRequestListener listener) {        

AndroidNetworking.upload(url)
.setTag(tag)
.addHeaders(getRequestHeader())
.addMultipartFile(key,file)
.addMultipartParameter(params)
.build()
.setUploadProgressListener(uploadProgressListener).getAsString(listener);
 }

 public static void cancleByTag(String tag){
        AndroidNetworking.cancel(tag);
  }

```
tag is no == 
 I think if use equals will be better

**Comment by amitshekhariitbhu** [comment]
@LOWANGA : it should work like that also, but I must verify it. Thanks for the feedback

Thanks
Amit Shekhar

**Comment by LOWANGA** [comment]
I get string tag from two different objects it won't ＝＝   thanks

**Comment by amitshekhariitbhu** [comment]
```
        String stringOne = "one";
        String stringTwo = "one";

        Object objectOne = stringOne;
        Object objectTwo = stringTwo;

        if (objectOne == objectTwo) {
            Log.d(TAG, "Both are equal");
        }
```

I have tried this. This is printing "Both are equal";

**Comment by LOWANGA** [comment]
void isEqual(){
        MyVrImageBean bean1 = new MyVrImageBean();
        bean1.setName("123");
        MyVrImageBean bean2 = new MyVrImageBean();
        bean1.setName("123");

        Object object1 = bean1.getName();
        Object object2 = bean2.getName();
        if(object1==object2){
            LogUtil.e("xxxxxx","equal");
        }else{
            LogUtil.e("xxxxxx","noequal");
        }
    }

but I used like this is noequal  sometime i must used bean  id ,url or name to as tag and cancle it

**Comment by amitshekhariitbhu** [comment]
Ok. Will check it.

**Comment by LOWANGA** [comment]
When do you release the new version  I used 0.2.0-beta-0  but I do not have the source code to modify this question , thanks

**Comment by amitshekhariitbhu** [comment]
I will try to do it within 2-3 days. Anyway at present, you can find the source code of development branch [**here**](https://github.com/amitshekhariitbhu/Fast-Android-Networking/tree/development)

**Comment by LOWANGA** [comment]
😊   thanks

**Comment by amitshekhariitbhu** [comment]
fixed here : https://github.com/amitshekhariitbhu/Fast-Android-Networking/commit/9f0d0d253ac302e582e0fa426a7306a4bda423fa
