### ISSUE TITLE
Do request when network is available 

### ISSUE THREAD

**Issue by Ali-Khazaee** [amitshekhariitbhu/Fast-Android-Networking#234]
Hello there

I was thinking about new feature: when the client is offline these requests will be add to a pending queue list so when it get back online those pending requests will executed

Do you have plan to implement this feature ?

**Comment by amitshekhariitbhu** [comment]
@BioGram yes we are thinking of adding this feature.

**Comment by scavengerinc** [comment]
Any update on this feature yet, @amitshekhariitbhu ? Really stalling on this and would love a response!

**Comment by amitshekhariitbhu** [comment]
This week I am prioritizing the features. I will consider this too.

**Comment by scavengerinc** [comment]
@amitshekhariitbhu Thank you! Looking forward to hearing about this at the earliest. Would love to give my two cents if I had the chance!

**Comment by arpitjoshi08** [comment]
@amitshekhariitbhu  is there any updates?
