### ISSUE TITLE
Add Auth headers to imageView

### ISSUE THREAD

**Issue by MohadFarhan** [amitshekhariitbhu/Fast-Android-Networking#235]
Hello Amit, thanks for this awesome library. I was thinking of new feature or it maybe already exists, its that in imageView to set auth headers in java or xml because some servers allow to fetch images only for valid authentication.

**Comment by amitshekhariitbhu** [comment]
Currently it does not support this. One way u can do is with adding interceptor in okhttp and initialize the library with that okhttp.

**Comment by amitshekhariitbhu** [comment]
I will try to add this support in new release

**Comment by MohadFarhan** [comment]
Ok I will try doing that. I have another 1 question, How do I get response code in onResponse() interface method for getAsJsonObject() method.

**Comment by amitshekhariitbhu** [comment]
Use `getAsOkHttpResponseAndJSONObject ` for the above.

**Comment by MohadFarhan** [comment]
Thanks am getting reponse code using okHttpResponseListeners
