### ISSUE TITLE
Read Token from Header

### ISSUE THREAD

**Issue by IbrahemSabbah** [amitshekhariitbhu/Fast-Android-Networking#239]
How can i read specific header from post request , i do the request like this
`fun <T> post(apiHeader: ApiHeader, method: String, request: String, parseObject: Class<T>): Single<T> {
            return Rx2AndroidNetworking.post(BuildConfig.BASE_URL)
                    .addHeaders(apiHeader)
                    .addJSONObjectBody(jsonObject)
                    .build()
                    .getObjectSingle(parseObject)
                    .map(Function {
                        var js = JSONObject(it.toString())
                        return@Function convertDATAToObject(js.getJSONObject("DATA"), parseObject)
                    })

        }`

**Comment by amitshekhariitbhu** [comment]
Currently this feature is not available in the rxjava version of the library.

**Comment by IbrahemSabbah** [comment]
thank you

**Comment by rajscet** [comment]
I also want same. otherwise i have to use other lib

**Comment by rajscet** [comment]
Done
OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                        .addInterceptor(new Interceptor() {
                            @Override
                            public okhttp3.Response intercept(Chain chain) throws IOException {

                            String s= chain.proceed(chain.request()).header("Server");
                            String t=s;
                                return null;
                            }
                        })
                        .build();
                AndroidNetworking.post(BuildConfig.URL + "?action=test")
                        .addBodyParameter("data", data)
                        .addBodyParameter("log", jsonObject.toString())
                        .setOkHttpClient(okHttpClient)
                        .setTag("test")
                        .setPriority(Priority.HIGH)
                        .build()
                        .getAsJSONObject(new JSONObjectRequestListener() {
                            @Override
                            public void onResponse(JSONObject response) {

                            }

                            @Override
                            public void onError(ANError error) {
                                
                            }
                        });

**Comment by rajscet** [comment]
Close the issue now
https://stackoverflow.com/questions/30777419/getting-header-from-response-retrofit-okhttp-client

**Comment by mhafeezgr8** [comment]
@amitshekhariitbhu  whats the plan of adding this feature?
