### ISSUE TITLE
TimeOut

### ISSUE THREAD

**Issue by willemevenwel** [amitshekhariitbhu/Fast-Android-Networking#24]
How can I change the time out on a service request?

Something like:

AndroidNetworking.post(pUrl)
            .addByteBody(bytes)
            .setContentType("application/json")
            .setPriority(Priority.HIGH)
            .setExecutor(Executors.newSingleThreadExecutor())
            **.setTimeOut(60000) //milis**
            .build()
            .getAsOkHttpResponse(new OkHttpResponseListener() {

**Comment by amitshekhariitbhu** [comment]
You can set your custom okhttp client with custom timeout with setokhttpclient method

**Comment by willemevenwel** [comment]
Fantastic thanks.

**Comment by amitshekhariitbhu** [comment]
You are welcome 

Thanks
Amit Shekhar
