### ISSUE TITLE
Android Studio warning - All support libraries must use the exact same version

### ISSUE THREAD

**Issue by dev-myatminsoe** [amitshekhariitbhu/Fast-Android-Networking#240]
When I use version 1.0.1. The above warning is occurring. I'm using appcompat 26.1.0

**Comment by Anandsoni14** [comment]
I am using 27.0.2 and AndroidNetworking 1.0.0. I am not facing any issue. I think it must be issue from your side.

**Comment by amitshekhariitbhu** [comment]
Ok let me check and fix it.

**Comment by bisonterbang** [comment]
Hi, I'm using version 1.0.2 and I got the same error. It says that I have another appcompat using version 27.1.1. I'm currently using appcompat 26.1.0.
![image](https://user-images.githubusercontent.com/10974441/82978538-0a8a2280-a00f-11ea-8032-b231ff970113.png)
