### ISSUE TITLE
No response Error

### ISSUE THREAD

**Issue by roshan608** [amitshekhariitbhu/Fast-Android-Networking#242]
Hello sir,  I'm using this library in my application but suddenly it stopped working. I'm getting following error after calling webservice.
------------------------------------------------------------------------------------------------------
System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.myAppPackageName/cache/cache_an/journal.tmp
02-27 14:09:39.045 27265-27265/com.myAppPackageName D/servererror: com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: java.net.ProtocolException: Expected ':status' head
-------------------------------------------------------------------------------------------------------

I'm using version,
com.amitshekhar.android:android-networking:0.8.0

When I updated it to 1.0.0 . It started working fine again. But  I have used this in many projects.

And are there any licensing issues or credits we need to give.
Thank You.

**Comment by amitshekhariitbhu** [comment]
Not sure about the issue. Great that the new version is working. There is no licensing issue. Use it where ever you want.

**Comment by roshan608** [comment]
Please update if you get any solution on this issue. It will definitely help me saving users I'm gonna loose due to the sudden update.

**Comment by roshan608** [comment]
have you removed support for 0.8.0 and 0.2.0 ?

**Comment by rakeshrapaka** [comment]
I have postr esquest with no response, I only get http 200 ok. Body is null
How to handle such request with observable

**Comment by Daemon1993** [comment]
hello 

I have the same problem

java.io.FileNotFoundException: /data/user/0/myAppPackageName/cache/cache_an/journal.tmp (No such file or directory)

com.androidnetworking.error.ANError: java.lang.IllegalArgumentException: out == null

I'm using version, 1.0.1
