### ISSUE TITLE
Support for UploadProgressListener in Simple Post Request

### ISSUE THREAD

**Issue by LOWANGA** [amitshekhariitbhu/Fast-Android-Networking#25]
I used like this         AndroidNetworking.post(url).setTag(tag).addByteBody(bytes).build().setUploadProgressListener(uploadProgressListener).getAsString(listener);

uploadProgressListener is not taken into effect

**Comment by LOWANGA** [comment]
or upload can add addByteBody(bytes)

**Comment by LOWANGA** [comment]
or upload can add addByteBody(bytes)

**Comment by amitshekhariitbhu** [comment]
setUploadProgressListener is only for `AndroidNetworking.upload(url)`.

**Comment by LOWANGA** [comment]
Can support addByteBody (bytes)

**Comment by LOWANGA** [comment]
If the partition upload files need this mode

**Comment by amitshekhariitbhu** [comment]
@LOWANGA : sure I will try to add support for this.

**Comment by LOWANGA** [comment]
thanks

**Comment by dg76** [comment]
Hi! I think I have implemented this now, please see here #158 

Would you like to integrate it? Is it good this way? I could use it with setUploadProgressListener as described above afterward.

Kind regards

Dominique
