### ISSUE TITLE
android OREO ConnectionError problem

### ISSUE THREAD

**Issue by rezasadeghi93** [amitshekhariitbhu/Fast-Android-Networking#258]
Hi,
my app working fine with all version of android except android oreo or API 26,

the library show "ConnectionError" !

please help me with this...

----------------------
manifest permission:
`
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
`
and:

compile 'com.amitshekhar.android:android-networking:1.0.1'

**Comment by rezasadeghi93** [comment]
now, waiting 4 days and still no answer.

sounds like changing library helps...

**Comment by amitshekhariitbhu** [comment]
Can u send me more details like
- Is is happening with all the request?
- Url
- Get or post request or other.

**Comment by rezasadeghi93** [comment]
- yes with all
- url is like https://www.weboptic.ir/something/somthing.php
- post request

app working fine with all lower version of android but connectionError with areo! other apps workings fine with areo! network is good.

**Comment by amitshekhariitbhu** [comment]
I have tried but it is working for me.
Any specific device?

**Comment by amitshekhariitbhu** [comment]
This issue is not related to any library. Please [refer](https://github.com/square/okhttp/issues/3180).

**Comment by nanugarg93** [comment]
Hi Sir,

As i am using Fast Android Networking Library in all my apps to integrate apis, its working fine but when we use our app on Android OS Pie (P) it always shows **connectionError** in every Api response. what should i do ? It's creating too much problem.

implementation 'com.amitshekhar.android:android-networking:1.0.1'

Please help me with this...

**Comment by AmirNorouzpour** [comment]
look at : [https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted)

simple and unsafe way add  `android:usesCleartextTraffic="true"` in manifest file in application tag.

**Comment by ArunkumarAndanshetti** [comment]
Thank you @AmirNorouzpour
