### ISSUE TITLE
Pass the OkHttpResponse object in onResponse method 

### ISSUE THREAD

**Issue by tausiq** [amitshekhariitbhu/Fast-Android-Networking#26]
Could you please provide support for, `OkHttpResponse` object will get passed as parameter in `onResponse` method of `ParsedRequestListener` interface?
In that case, we can get the status code/headers from OkHttpResponse object and still enjoying the parsed object in `onResponse`. 

For better visualization, my request can be summarized below, 

```
.getAsParsed(new TypeToken<User>() {}, new ParsedRequestListener<User>() {
    @Override
    public void onResponse(Response response, User user) {
        // we can find header like response.headers()
        // we can get user as parsed
    }

    @Override
    public void onError(ANError anError) {
        // handle error
    }
}); 
```

Thanks in advance!

P.S: Requested the same feature as a comment in [another issue](https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/14). The issue has been closed. So I am creating a separate issue.

**Comment by amitshekhariitbhu** [comment]
Ok no problem . This week most probably we will be releasing 2.0 with this feature.

**Comment by amitshekhariitbhu** [comment]
@tausiq how about this. I am planning to add like below in all requests, this will be an optional listener.

```
AndroidNetworking.get(url)
                .build()
                .setResponseListener(new ResponseListener() {
                    @Override
                    public void onReceived(Response response) {
                        // access header here
                    }
                })
                .getAsParsed(new TypeToken<User>() {
                }, new ParsedRequestListener<User>() {
                    @Override
                    public void onResponse(User user) {
                        
                    }

                    @Override
                    public void onError(ANError anError) {
                        
                    }
                });
```

**Comment by tausiq** [comment]
Please consider this case, the server will return the same User object with different header code and that should be considered as two separate responses. 

In such cases, if we need to make a decision based on the header/response then we would be required to save the response object and then we will be able to access the response object in `onResponse` method. 

In my opinion, it would be better if we could get the Response object and User object in the same method. But of course, there might be implementation challenges and you can plan for it in next version. 

Thanks for consideration.

**Comment by tausiq** [comment]
I am guessing, `ResponseListener.onReceived` (if set) will always be invoked before `ParsedRequestListener. onResponse`. Otherwise, it will create another set of problems regarding synchronization.

**Comment by amitshekhariitbhu** [comment]
@tausiq : Got the use case. Will implement it.

**Comment by amitshekhariitbhu** [comment]
@tausiq - version 0.2.0 has been released with the features that you had requested.

```
AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAnUserDetail/{userId}")
                .addPathParameter("userId", "1")
                .setTag(this)
                .setPriority(Priority.LOW)
                .setUserAgent("getAnUser")
                .build()
                .getAsOkHttpResponseAndParsed(new TypeToken<User>() {
                }, new OkHttpResponseAndParsedRequestListener<User>() {
                    @Override
                    public void onResponse(Response okHttpResponse, User user) {
                      // do anything with okHttpResponse and user
                    }
                    @Override
                    public void onError(ANError anError) {
                      // handle error
                    }
                });
```

**Comment by tausiq** [comment]
Thank you so much! Really appreciate your effort.
