### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

### ISSUE THREAD

**Issue by amirhoseinpourali** [amitshekhariitbhu/Fast-Android-Networking#263]
I get this error when sending a get request

this is my code:

** build.gradle **
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "ir.supersoft.androidfastnetworking"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.amitshekhar.android:android-networking:1.0.0'
    compile 'com.library.tangxiaolv:telegramgallery:1.0.3'
}
`

**User.java**
`public class User {

  public int id;
  public String first_name;
  public String last_name;
  public int age;
}
`

**MainActivity.java**
AndroidNetworking.initialize(getApplicationContext());

`AndroidNetworking.get("http://sekeh.gigfa.com/getUsers.php")
          .setTag("test")
          .setPriority(Priority.LOW)
          .build()
          .getAsOkHttpResponseAndObjectList(User.class, new OkHttpResponseAndParsedRequestListener<List<User>>() {
            @Override
            public void onResponse(Response okHttpResponse, List<User> users) {
              // do anything with response
              Log.d("amirhosein", "userList size : " + users.size());
              for (User user : users) {
                Log.d("amirhosein", "id : " + user.id);
                Log.d("amirhosein", "firstname : " + user.first_name);
                Log.d("amirhosein", "lastname : " + user.last_name);
                Log.d("amirhosein", "age : " + user.age);
              }
            }

            @Override
            public void onError(ANError anError) {
              Log.e("amirhosein", "error: " + anError.getLocalizedMessage());
            }
          });
`

i test that in localhost(xampp) but it`s worked!

keep in mind that my androidnetworking version is 1.0.0
because 1.0.1 need to appcompatv7:27.0.2

**Comment by amitshekhariitbhu** [comment]
Do like this
```
AndroidNetworking.initialize(getApplicationContext());

Gson gson = new GsonBuilder()
        .setLenient()
        .create();

AndroidNetworking.setParserFactory(new GsonParserFactory(gson));
```

**Comment by amitshekhariitbhu** [comment]
And also refer [this](https://stackoverflow.com/questions/39918814/use-jsonreader-setlenienttrue-to-accept-malformed-json-at-line-1-column-1-path)

**Comment by amitshekhariitbhu** [comment]
Also check your response correctly, is it maps to the object correctly?

**Comment by amirhoseinpourali** [comment]
Use JsonReader.setLen....... is fixed. thank you
but i get this error: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
What is its cause?

**Comment by amitshekhariitbhu** [comment]
Please check the response. Is it matching with the Object?

**Comment by amirhoseinpourali** [comment]
yes

**Comment by amitshekhariitbhu** [comment]
Provide the dummy response.

**Comment by amitshekhariitbhu** [comment]
Your response is not json. It is text/html so it is unable to parse. Send application/json from the server as the content-type.

**Comment by amirhoseinpourali** [comment]
it`s worked
the reason is content-type!
Thank you for your prompt answer

**Comment by NanaGithub** [comment]
> Your response is not json. It is text/html so it is unable to parse. Send application/json from the server as the content-type.

very thank you!!!!

**Comment by deepak-prajapatii** [comment]
> Your response is not json. It is text/html so it is unable to parse. Send application/json from the server as the content-type.

@NanaGithub @amitshekhariitbhu 
Please tell me how to send application/json from the server as the content type. I am working on app and library using Retrofit

**Comment by zigic88** [comment]
you need to define content type from your service API (server-side)

**Comment by waheed006** [comment]
In my case from server side content type is already json but I'm still getting same error.

**Comment by grandeefidel** [comment]
In my case from the server side, the content type is already JSON but I'm still getting the same error.

**Comment by kazirakibivan** [comment]
;
