### ISSUE TITLE
File caching method - Clarification needed

### ISSUE THREAD

**Issue by gowtham4us** [amitshekhariitbhu/Fast-Android-Networking#266]
Hi amit.. consider the scenario.

I have given a link to download file. F.A.N library will download and store it in the location i have given.
The 2nd time i m requesting the same link, will F.A.N download the file again ?

If NO, "downloadCompleted" will be called instantly ?? 

When will F.A.N decides to download the file again ? ( in both cases, cache-control supported url and cache-control unsupported url )

How F.A.N find the file exists already ? ( Maintaining a DB mapping for the file location and link ? )

It would be great if you can explain the cases and flows in file download feature alone.
Thank you..

**Comment by amitshekhariitbhu** [comment]
@gowtham4us OkHttp does it by keeping it in the diskcache.

**Comment by amitshekhariitbhu** [comment]
Why you will redownload if you already have file.

**Comment by gowtham4us** [comment]
:D :D i have the file alone. I cannot make sure that file belongs to the URL. Even if it belongs to the URL(i can maintain a mapping), it's content might have changed right (lifetime of the file in that link expires or a new file is added to the link) ?

**Comment by gowtham4us** [comment]
Shall we take this discussion to whatsapp ? The case i m conveying is so deep. We can try to solve this with F.A.N itself.

**Comment by guyulmaz** [comment]
Just download md5 of the file, and compare with local file, if not match, download again the file...

**Comment by gowtham4us** [comment]
Hey guys.. I ve got the complete guide for caching a file. Here is an article from a Google dev.

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
