### ISSUE TITLE
Don't work with header "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by pesvn20** [amitshekhariitbhu/Fast-Android-Networking#27]
I need example post request with header "application/x-www-form-urlencoded". I tried this

                 AndroidNetworking.post("url")
                .addUrlEncodeFormBodyParameter("grant_type","password")
                .addUrlEncodeFormBodyParameter("username",username)
                .addUrlEncodeFormBodyParameter("password",password)
                .addHeaders("Content-Type","application/x-www-form-urlencoded;charset=UTF8")
                .setTag("authentication")
                .setPriority(Priority.MEDIUM)
                .build()
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                        Log.i("Data from api success", response.toString());
                    }

                    @Override
                    public void onError(ANError anError) {
                        Log.i("Data from api error", anError.toString());
                    }
                });

but it returns "_Attempt to invoke virtual method 'okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder()' on a null object reference_"
Thank you

**Comment by amitshekhariitbhu** [comment]
@pesvn20  : just confirming why u are adding custom header? It automatically do the same while you use `addUrlEncodeFormBodyParameter` to the request. I think there is no need to add the header.

**Comment by pesvn20** [comment]
@amitshekhariitbhu i just remove header, but it still run error

**Comment by amitshekhariitbhu** [comment]
@pesvn20 : ok, I will test it and fix it, if there is any bug.

**Comment by pesvn20** [comment]
@amitshekhariitbhu: thank you
