### ISSUE TITLE
How to Read addJSONObjectBody using PHP

### ISSUE THREAD

**Issue by nian88** [amitshekhariitbhu/Fast-Android-Networking#270]
AndroidNetworking.post(UtilNet.url+"student")
                .setPriority(Priority.MEDIUM)
                .addJSONObjectBody(studentsObj)
                .setOkHttpClient(UtilNet.getHttp())
                .build()

how to read JSONObjectBody using PHP

**Comment by amitshekhariitbhu** [comment]
You can try `json_decode`.
