### ISSUE TITLE
Form Data result is coming wrong.

### ISSUE THREAD

**Issue by jmimohsin** [amitshekhariitbhu/Fast-Android-Networking#278]
Hi Amit,

Your library is very simple and I always request to my friends to use this library but first time I have got stuck in one API. I am not able to get correct result which I am getting from Postman.

Please check complete issue with code here: https://stackoverflow.com/questions/50239061/not-able-to-get-form-data-result-in-android-using-volley-or-fast-android-network

Please try to resolve this issue.

Thanks,
Mohsin

**Comment by amitshekhariitbhu** [comment]
@jmimohsin  Hi, I am not able to open the link. Can u please check and update?

**Comment by jmimohsin** [comment]
Fixed, issue was not coming from your SDK. Thanks for support.
