### ISSUE TITLE
cant get Headers

### ISSUE THREAD

**Issue by hiteshrawat** [amitshekhariitbhu/Fast-Android-Networking#28]
Headers s=AndroidNetworking.get("http://www.frendz4m.com/forum/login.php")
                        .build().getHeaders() ;
                textView.setText(s.toMultimap().values().size()+"");

final  ANRequest s=AndroidNetworking.post("http://www.frendz4m.com/forum/authenticate.php")
                .addHeaders("Cookie",cookieToString(cookies))
           .build() ;
String str=s.getHeaders().get("Set-Cookie")+"";

addHeaders() method working fine.

but getHeaders() return null value

I want to save cookies. but i am unable to get "Set-Cookie:" header

**Comment by amitshekhariitbhu** [comment]
@hiteshrawat : Using getHeaders, do you want to get Headers returned from server?

**Comment by hiteshrawat** [comment]
Yes, I want to store cookies returned by server

**Comment by amitshekhariitbhu** [comment]
In version 0.1.0 there is no way to access headers from server. I have added it in 0.2.0. which I am testing now. and going to release by tomorrow, For now you can use that version 

`'com.amitshekhar.android:android-networking:0.2.0-dev-0'`

The sample code is : 

```
AndroidNetworking.get(url)
                            .build()
                            .getAsOkHttpResponse(new OkHttpResponseListener() {
                                @Override
                                public void onResponse(Response response) {
                                    Log.d(TAG, "Headers :" + response.headers());
                                }

                                @Override
                                public void onError(ANError anError) {
                                    //handle error
                                }
                            });
```

**Comment by hiteshrawat** [comment]
thank you Amit. Please add download link for  .jar library files also

**Comment by amitshekhariitbhu** [comment]
I wanted to know why u don't use gradle ?

**Comment by hiteshrawat** [comment]
Mostly I use college wifi. I dont have network connection at home. So I use jar files and test apps on mobile's 3g connection.

**Comment by amitshekhariitbhu** [comment]
Oh nice .

**Comment by amitshekhariitbhu** [comment]
I have uploaded the version 0.2.0 here ignore dev version and use this

`com.amitshekhar.android:android-networking:0.2.0`

Will upload the jar file by tomorrow.

**Comment by hiteshrawat** [comment]
Thanks Amit. Keep it up. Your AndroidNetworking library is very useful for beginners.

**Comment by Reza-77** [comment]
Thanks for comfortable lib. where is uploaded jar file ?
