### ISSUE TITLE
File's not downloaded but the progress shows as already downloaded

### ISSUE THREAD

**Issue by zomaru** [amitshekhariitbhu/Fast-Android-Networking#281]
Hi dev, i used your library and found following issue as the title said, i'm downloading an image from my hosting, previously i was able to display the image into an imageview, but i tried to add a download section for the image and i found this issue.

// even when i changed context.getFilesDir().getAbsolutePath() with the actual name of directory, it's same //
// variable string is the url to the file (an image) //
// variable namafile is the filename //

AndroidNetworking.download(string, context.getFilesDir().getAbsolutePath(), namafile).setTag("Download").setPriority(Priority.HIGH).build().setDownloadProgressListener(new DownloadProgressListener() {
                    private int prosentase;

                    @Override
                    public void onProgress(long bytesDownloaded, long totalBytes) {
                        final int progress = (int) (bytesDownloaded * 100 / totalBytes);
                        if (progress != prosentase) {
                        Toast toast = Toast.makeText(WallPaperPicker.this, getApplicationContext().getResources().getString(R.string.downloading), Toast.LENGTH_LONG);
                                toast.show();
                                progressBar.setProgress(progress);
                                textView.setText("Mendownload.." + progress + " %");
                                prosentase = progress;
                                }
                        }
                  }).startDownload(new DownloadListener() {
                    @Override
                    public void onDownloadComplete() {
                        progressBar.setProgress(100);
                        Toast toast = Toast.makeText(WallPaperPicker.this, getApplicationContext().getResources().getString(R.string.download_finish), Toast.LENGTH_LONG);
                        toast.show();
                    }

                    @Override
                    public void onError(ANError anError) {
                        progressBar.setVisibility(View.GONE);
                        progressBar.setProgress(0);
                        Toast toast = Toast.makeText(WallPaperPicker.this, getApplicationContext().getResources().getString(R.string.download_error), Toast.LENGTH_LONG);
                        toast.show();
                    }
                });
                progressBar.setProgress(0);
                progressBar.setVisibility(View.VISIBLE);

**Comment by amitshekhariitbhu** [comment]
Once check if the file is really downloaded or not?

**Comment by zomaru** [comment]
oh my mistake, i wasn't declaring the directory for the downloaded images yet, so it was saved on the temp directory..
