### ISSUE TITLE
Check by Tag, if any Network Request is running or not ?

### ISSUE THREAD

**Issue by devsideal** [amitshekhariitbhu/Fast-Android-Networking#29]
Hi @amitshekhariitbhu,
Is this possible to check by Tag name, if any Network Request is running or not ?
like AndroidNetworking.isRunning(Object tag);

**Comment by amitshekhariitbhu** [comment]
As of now it is not there. It is a good feature. Will add it in next release

**Comment by amitshekhariitbhu** [comment]
Added support for this in the new release.
Check [here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/CHANGELOG.md).
