### ISSUE TITLE
Multiple file upload with single key 

### ISSUE THREAD

**Issue by AravinthSri** [amitshekhariitbhu/Fast-Android-Networking#294]
Hi..

File upload i got struggled in formdata key, and value. key is "files" and value is list of files. but here unable to use list of files in value side.

Please help me to upload single key with list of files

**Comment by amitshekhariitbhu** [comment]
We are building this feature in the new release.

**Comment by adesousabarroso** [comment]
Hi,
try to put the name of the file to upload indexed:

ANRequest.MultiPartBuilder builder = ...
...
for (int i = 0; i < filesList.size(); i++) {
    File file = filesList.get(i);
    builder.addMultipartFile(**"fileName[" + i + "]"**, file);
}

Good luck,
Antonio
