### ISSUE TITLE
How to cancel All Rx2AndroidNetworking ?

### ISSUE THREAD

**Issue by mdtuyen** [amitshekhariitbhu/Fast-Android-Networking#299]
I have many requests using Rx2AndroidNetworking,

And I have a stop button, and a start button
I want when I click the stop button all requests stop and do not get results

Then I press the start button, all requests will be re-initialized and executed.

How can I stop all requests.

I used TAG for each request or added the request to CompositeDispose then cancel or clear but failed.

Please give me a solution with your library.

**Comment by amitshekhariitbhu** [comment]
You need to create a single disposable for all. Also you can try HashMap like <TAG, Disposable> and put the request with respect to the TAG in the Disposable.

**Comment by mdtuyen** [comment]
Hi,

I have a CompositeDisposable "disposable" to add all request:

    public Disposable getString(String url, String TAG,  DisposableObserver<String> observer) {
        return Rx2AndroidNetworking.get(url)
                .setTag(TAG)
                .build()
                .getStringObservable()
                .subscribeOn(Schedulers.io())
                .unsubscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(observer);
    }

with each request is called I add them to disposable:
disposable.add(getString(my_url, TAG));

Now I have two solution to cancel request is:
disposable.clear();
or 
AndroidNetworking.forceCancel(TAG);

But nothing work!

**Comment by amitshekhariitbhu** [comment]
`disposable.clear()' should work.
