### ISSUE TITLE
how to cancel  a synchronous call

### ISSUE THREAD

**Issue by LOWANGA** [amitshekhariitbhu/Fast-Android-Networking#30]
how to cancle  a synchronous call

**Comment by amitshekhariitbhu** [comment]
@LOWANGA : you can set a tag on synchronous call too. In the same way you can cancel like in asynchronous call.

`AndroidNetworking.cancel(tag);`

**Comment by LOWANGA** [comment]
but it is not add "ANRequestQueue.getInstance().addRequest(this)"
public ANResponse executeForString() {
        this.mResponseType = ResponseType.STRING;
        return SynchronousCall.execute(this);
    }

**Comment by amitshekhariitbhu** [comment]
@LOWANGA : If you are using the Synchronous request. You must be calling it from your custom thread. So here, I believe you should implement at your end. You should kill the thread

**Comment by LOWANGA** [comment]
I see 
thanks
