### ISSUE TITLE
 How to Post resquest with no need response

### ISSUE THREAD

**Issue by caka-ict** [amitshekhariitbhu/Fast-Android-Networking#306]
Hi, I have post resquest with no response, I only get http 200 ok. Body is null
How to handle such request with observable

**Comment by amitshekhariitbhu** [comment]
Use `getAsOkHttpResponse` when you do not need response.

**Comment by javier4mar** [comment]
How can I get an observable with getAsOkHttpResponse ?

**Comment by amitshekhariitbhu** [comment]
@javier4mar I will add this support.
