### ISSUE TITLE
Unable to use okhttp response with RxJava observer

### ISSUE THREAD

**Issue by usmanrana07** [amitshekhariitbhu/Fast-Android-Networking#310]
I can not get **errorCode** in case of failure when using RxJava, it gives throwable in onError method, how can we get 'AnError' object in onError method?

**Comment by amitshekhariitbhu** [comment]
Yes, you can do like this.
```
if (throwable instanceof ANError) {
  ANError anError = (ANError) throwable;
  handleApiError(anError);
}
```

**Comment by usmanrana07** [comment]
Thanks, this is what i was looking for.
