### ISSUE TITLE
[question] What is the response of a request, when the device is offline

### ISSUE THREAD

**Issue by Arcfej** [amitshekhariitbhu/Fast-Android-Networking#319]
Hi!

Can you tell me, what will be the response to a request, when the device is offline? Can I somehow manage, that in this case onError will be called?

Thanks for your asnwer!

Mike

**Comment by amitshekhariitbhu** [comment]
Please refer [this](https://amitshekhariitbhu.github.io/Fast-Android-Networking/error_code_handling.html)
