### ISSUE TITLE
How to set timeout in Request

### ISSUE THREAD

**Issue by vsoft-phuong** [amitshekhariitbhu/Fast-Android-Networking#32]
ErrorCode=0,
ErrorMessage=com.androidnetworking.error.ANError: java.net.SocketTimeoutException

How I solve this problem, please?

**Comment by amitshekhariitbhu** [comment]
@vsoft-phuong : You can pass custom okHttpClient with increased timeout.

```
OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(120, TimeUnit.SECONDS)
                .readTimeout(120, TimeUnit.SECONDS)
                . writeTimeout(120, TimeUnit.SECONDS)
                .build();

AndroidNetworking.initialize(getApplicationContext(),okHttpClient);  
```

**Comment by amitshekhariitbhu** [comment]
@vsoft-phuong : You can also customize it for a particular request.

```
OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(120, TimeUnit.SECONDS)
                .readTimeout(120, TimeUnit.SECONDS)
                . writeTimeout(120, TimeUnit.SECONDS)
                .build();
AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                 .addPathParameter("pageNumber", "0")
                 .addQueryParameter("limit", "3")
                 .addHeaders("token", "1234")
                 .setTag("test")
                 .setPriority(Priority.LOW)
                 .setOkHttpClient(okHttpClient) // passing a custom okHttpClient 
                 .build()
                 .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                      // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                    // handle error
                    }
                });
```

**Comment by vsoft-phuong** [comment]
Thanks you!

**Comment by hiteshrawat** [comment]
Please post a tutorial on uploading multipart files  in background service and update ui progress.

**Comment by amitshekhariitbhu** [comment]
@hiteshrawat 
```
AndroidNetworking.upload(url)
                 .addMultipartFile("image",file)    
                 .addMultipartParameter("key","value")
                 .build()
                 .setUploadProgressListener(new UploadProgressListener() {
                    @Override
                    public void onProgress(long bytesUploaded, long totalBytes) {
                      // do anything with progress 
                    }
                 })
                 .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                      // do anything with response                
                    }
                    @Override
                    public void onError(ANError error) {
                      // handle error 
                    }
                 }); 
```

This code does uploading in background you can write this anywhere.

**Comment by hiteshrawat** [comment]
Thanks Amit I have tried it.Its working fine. But I want implement it with the Service and make it work even after exiting the app.
I am beginner to android.Please guide me.

**Comment by amitshekhariitbhu** [comment]
@hiteshrawat : Sure sure I am here help everybody.
You can write the same code in your service and then use LocalBroadcast to post progress from service to Activity . Example is present [here](https://gist.github.com/Antarix/8131277)

**Comment by hiteshrawat** [comment]
Thanks Amit

**Comment by nikhiljadhav159** [comment]
How to get the **status code** for Response?

**Comment by amitshekhariitbhu** [comment]
@nikhiljadhav159 : refer [this](https://amitshekhariitbhu.github.io/Fast-Android-Networking/accessing_headers.html).

**Comment by RanchhodRamani** [comment]
@amitshekhariitbhu How can i send multiple image and video in single request? 
is it like
while(loop){
   .addMultipartFile("image[]",file[i])    
}

i am little confuse

**Comment by amitshekhariitbhu** [comment]
Depends on you

**Comment by hasnain-ahmad** [comment]
@amitshekhariitbhu is there any standard/best practices to follow it...

**Comment by hasnain-ahmad** [comment]
> @vsoft-phuong : You can pass custom okHttpClient with increased timeout.
> 
> ```
> OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
>                 .connectTimeout(120, TimeUnit.SECONDS)
>                 .readTimeout(120, TimeUnit.SECONDS)
>                 . writeTimeout(120, TimeUnit.SECONDS)
>                 .build();
> 
> AndroidNetworking.initialize(getApplicationContext(),okHttpClient);  
> ```

Does this code will work for `Rx2AndroidNetworking`???

**Comment by KhizarJaved** [comment]
> > @vsoft-phuong : You can pass custom okHttpClient with increased timeout.
> > ```
> > OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
> >                 .connectTimeout(120, TimeUnit.SECONDS)
> >                 .readTimeout(120, TimeUnit.SECONDS)
> >                 . writeTimeout(120, TimeUnit.SECONDS)
> >                 .build();
> > 
> > AndroidNetworking.initialize(getApplicationContext(),okHttpClient);  
> > ```
> 
> Does this code will work for `Rx2AndroidNetworking`???

Will this code work for all network calls used in the android project?? If the above is written in the `Application` class.

**Comment by gianghoang1995** [comment]
not working.
