### ISSUE TITLE
File Upload Failed

### ISSUE THREAD

**Issue by knight-shade** [amitshekhariitbhu/Fast-Android-Networking#321]
I have a upload a file to a server using form-data. Below is the code:

AndroidNetworking.upload(uploadUrl)
                .addMultipartFile("objfile", File(getUriFromDrawable(R.raw.dogvideo).path))
                .addMultipartParameter("requestfrom", "mobile")
                .setPriority(Priority.HIGH)
                .build()
                .setUploadProgressListener(object : UploadProgressListener {
                    override fun onProgress(bytesUploaded: Long, totalBytes: Long) {
                        Log.d(javaClass.simpleName, "Uploaded $bytesUploaded/$totalBytes, ${(bytesUploaded/totalBytes) * 100}%")
                    }
                })
                .getAsJSONObject(object : JSONObjectRequestListener {
                    override fun onResponse(response: JSONObject?) {
                        Log.d(javaClass.simpleName, "$response")
                    }

                    override fun onError(anError: ANError) {
                        Log.d(javaClass.simpleName, "${anError.response}\n${anError.errorBody}\n${anError.errorDetail}\n${anError.errorCode}")
                    }
                })

Error: Connection Error

**Comment by amitshekhariitbhu** [comment]
Can u try moving the file to internal or external SD card and then upload?

**Comment by knight-shade** [comment]
@amitshekhariitbhu , I tried moving the file in internal, but still the same error. Cannot verify for SD card since I don't use one.
