### ISSUE TITLE
How to send multipart/form-data 

### ISSUE THREAD

**Issue by nuwanchamara** [amitshekhariitbhu/Fast-Android-Networking#323]
I need to send a post request  request witn following data. how can i achieve that using this library? 

**contetnt-type** : multipart/form-data; boundary=----WebKitFormBoundaryaUXFG5FuyEr1P2UZ

`------WebKitFormBoundaryaUXFG5FuyEr1P2UZ
Content-Disposition: form-data; name="json"

{"user":{"fullName":"skdfnmsdf","email":"frrrfr.q@sdfs.vv","password":"nuwan123"},"org":{"name":"asdasd","planType":"ORG_INVOICED"}}
------WebKitFormBoundaryaUXFG5FuyEr1P2UZ--`

**Comment by amitshekhariitbhu** [comment]
Use `AndroidNetworking.upload()`
