### ISSUE TITLE
Cant upload multiple file in same parameter as multipart file

### ISSUE THREAD

**Issue by Arjunbabuc92** [amitshekhariitbhu/Fast-Android-Networking#326]
I am using fast android network library 1.0.2. When i put a hash map as multi part parameter the last file overwrite the previous files. Please go through my code. If there is any issue please help me.. I am on dead end of a project.

                   `JSONObject temp=json.optJSONObject(0);
                    File file=new File(temp.optString("img"));
                    JSONObject temp1=json.optJSONObject(1);
                    File file1=new File(temp1.optString("img"));
                    Map<String, File> multiPartFileMap= new HashMap<>();
                    multiPartFileMap.put("userFiles[]", file);
                    multiPartFileMap.put("userFiles[]", file1);
                    AndroidNetworking.upload(url)
                            .addMultipartFile(multiPartFileMap)
                            .addMultipartParameter("userid",userid)
                            .setTag("uploadTest")
                            .setPriority(Priority.HIGH)
                            .build()
                            .setUploadProgressListener(new UploadProgressListener() {
                                @Override
                                public void onProgress(long bytesUploaded, long totalBytes) {
                                    // do anything with progress
                                }
                            })
                            .getAsString(new StringRequestListener() {
                                @Override
                                public void onResponse(String response) {
                                    Log.d("uploadresponse",response.toString());
                                    String pathName = Environment.getExternalStorageDirectory().toString()+path;
                                    final File file = new File(pathName);
                                    deleteRecursive(file);
                                    pDialog.dismiss();
                                }

                                @Override
                                public void onError(ANError error) {
                                    // handle error
                                    Log.d("uploadresponse",error.toString());
                                    pDialog.dismiss();
                                    Toast.makeText(getApplicationContext(),"Please try again",Toast.LENGTH_LONG).show();
                                }
                            });`

**Comment by amitshekhariitbhu** [comment]
Use multipartFileList()
