### ISSUE TITLE
SSL handshake aborted

### ISSUE THREAD

**Issue by eniserkaya** [amitshekhariitbhu/Fast-Android-Networking#329]
Hi, firstly i would like to thank you Mr.
I have a problem about this library. I use this library and it work very well.
But a device which is
Samsung SM- T520 Android:  4.4.2 
API Version: 19
gives error like this:

com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7b9c42b0: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x76c7cce0:0x00000000) 

Is there any solution? Thanks.

**Comment by eniserkaya** [comment]
I solved it. I added this code and it is work.
"Android 4.4 and lower don't support certain protocols by themselves ( eg TLS 1.2 ), but Google made a workaround by bundling them inside play services." For more detail: https://github.com/bumptech/glide/issues/3120

if (Build.VERSION.SDK_INT == 19) {
            try {
                ProviderInstaller.installIfNeeded(this);
            } catch (Exception ignored) {
                Log.e("EXCEPTIONNN",ignored.getMessage()+" ");
            }

        }

**Comment by Aksz1988** [comment]
Where this code need to implement, in Service call class or in Activity.
This code:

if (Build.VERSION.SDK_INT == 19) {
try {
ProviderInstaller.installIfNeeded(this);
} catch (Exception ignored) {
Log.e("EXCEPTIONNN",ignored.getMessage()+" ");
}
