### ISSUE TITLE
Timeouts never ocurr

### ISSUE THREAD

**Issue by aschmois** [amitshekhariitbhu/Fast-Android-Networking#33]
I have tried using this code:
`OkHttpClient okHttpClient = new OkHttpClient().newBuilder().connectTimeout(1, TimeUnit.SECONDS).readTimeout(1, TimeUnit.SECONDS).writeTimeout(1, TimeUnit.SECONDS).build();
ANRequest request = AndroidNetworking.get(url).setOkHttpClient(okHttpClient).build();
ANResponse<String> response = request.executeForString();`

and

`OkHttpClient okHttpClient = new OkHttpClient().newBuilder().connectTimeout(1, TimeUnit.SECONDS).readTimeout(1, TimeUnit.SECONDS).writeTimeout(1, TimeUnit.SECONDS).build();
        AndroidNetworking.initialize(getApplicationContext(), okHttpClient);`

And both never timeout (and neither do they respond).

**Comment by amitshekhariitbhu** [comment]
@aschmois  : Any error response ?

**Comment by aschmois** [comment]
None, just blocks without ever responding.

**Comment by amitshekhariitbhu** [comment]
I just tried it. It is working fine.

```
    OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                        .connectTimeout(1, TimeUnit.SECONDS)
                        .readTimeout(1, TimeUnit.SECONDS)
                        .writeTimeout(1, TimeUnit.SECONDS).build();

                ANRequest request = AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                        .addPathParameter("pageNumber", "0")
                        .addQueryParameter("limit", "3")
                        .setOkHttpClient(okHttpClient)
                        .build();

                ANResponse<String> response = request.executeForString();

                if(response.isSuccess()){
                    Log.d(TAG,"success"+response.getResult());
                }else {
                    ANError error = response.getError();
                    if (error.getErrorCode() != 0) {
                        Log.d(TAG, "onError errorCode : " + error.getErrorCode());
                        Log.d(TAG, "onError errorBody : " + error.getErrorBody());
                        Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
                    } else {
                        Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
                    }
                }
```

**Comment by amitshekhariitbhu** [comment]
it should work. Anyway I will try to find out why this is occurring in your case.

**Comment by aschmois** [comment]
Ah, I missed that part, I thought IoExceptions were thrown on timeouts. Thank you for the quick help very surprised! Also great library.

**Comment by molavy** [comment]
@aschmois ,have same problem, how you solved your problem?
i use getAsJSONObject

**Comment by amirzeinaly** [comment]
I have same problem too! timeout never called
`OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
            .connectTimeout(200, TimeUnit.MILLISECONDS)
            .readTimeout(200, TimeUnit.MILLISECONDS)
            . writeTimeout(200, TimeUnit.MILLISECONDS)
            .build();

        AndroidNetworking.post(baseUrl+"/api/v1/Restaurants/RestaurantFilter/Search")
                .setTag("SearchRestaurant")
                .setPriority(Priority.LOW)
                .addApplicationJsonBody(request)
                .addQueryParameter("paging", String.valueOf(paging))
                .setOkHttpClient(okHttpClient)
                .build()
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                       
                    }

                    @Override
                    public void onError(ANError anError) {
                        
                    }
                });`
