### ISSUE TITLE
Send files array in Multipart file.

### ISSUE THREAD

**Issue by lakshmi098** [amitshekhariitbhu/Fast-Android-Networking#335]
I couldn't able to send the multiple files in multipart file body either in the post or in upload method.

**Comment by indraniltalukdar** [comment]
@lakshmi098 This code worked for me to send multiple files using `upload` method.

```
Map<String, File> multiPartFileMap = new HashMap<>();
               multiPartFileMap.put("image1" , file1);
               multiPartFileMap.put("image2" , file2);

AndroidNetworking.upload(url)
                   //.addMultipartFileList(mMultiPartFileMap)
                   .addMultipartFile(multiPartFileMap)
                   .addMultipartParameter("text",STRING_VALUE))
                   .setTag("uploadTest")
                   .setPriority(Priority.HIGH)
                   .build()
                   .setUploadProgressListener(new UploadProgressListener() {
                       @Override
                       public void onProgress(long bytesUploaded, long totalBytes) {
                           // do anything with progress
                           console("progress => " + bytesUploaded);
                       }
                   })
                   .getAsString(new StringRequestListener() {
                       @Override
                       public void onResponse(String response) {
                           console("upload => " + response);
                       }

                       @Override
                       public void onError(ANError anError) {

                       }
                   });
```

**Comment by lakshmi098** [comment]
Thanks for your reply.

But i want to send it as a single array for single key.

**Comment by adimuwardi** [comment]
This Work For Lib 1.0.2
`
List<File> FOTO = new ArrayList<File>();
FOTO.add(new File(PATH_PHOTO));
FOTO.add(new File(PATH_PHOTO));

AndroidNetworking.upload(url)
     .addMultipartFileList("myfoto[]", FOTO))
     .setTag("uploadTest")
     .setPriority(Priority.HIGH)
     .build()
     .setUploadProgressListener(new UploadProgressListener() {
         @Override
         public void onProgress(long bytesUploaded, long totalBytes) {
             // do anything with progress
             console("progress => " + bytesUploaded);
         }
     })
     .getAsString(new StringRequestListener() {
         @Override
         public void onResponse(String response) {
             console("upload => " + response);
         }

         @Override
         public void onError(ANError anError) {

         }
     });
`

Tanks @amitshekhariitbhu
