### ISSUE TITLE
Question: How to get response in worker thread?

### ISSUE THREAD

**Issue by boyfox** [amitshekhariitbhu/Fast-Android-Networking#34]
Hi, thanks you for great library! I've a question, I need get response in worker thread and doing somethings(parsing, saving, sorting) and after completing all operation then showing result in main thread. Can you say how to solve this problem with Fast-Android-Networking without sync request. Because I don't want open extra custom thread and send request with synchronous and doing all operation and then pass result main thread. I'm currently doing with this still, but some code boilerplate. I want use asynchronous request of "Fast-Android-Networking" but get response on worker background thread. It is possible?

**Comment by amitshekhariitbhu** [comment]
@boyfox : you can set the custom executor by using 
`setExecutor(Executors.newSingleThreadExecutor()) `

For more detail refer the below link
https://amitshekhariitbhu.github.io/Fast-Android-Networking/custom_executor.html

**Comment by boyfox** [comment]
@amitshekhariitbhu thank you for quickly replying, but my problem is difference with your answer. I already putted setExecutor(Executors.newSingleThreadExecutor()). If we Executors.newSingleThreadExecutor() name is threadA, when request finished I need get response data in threadA not in thread main, for example

```
AndroidNetworking.post(FussballConfig.BASE_LOCAL_URL)
                    .setContentType("application/json; charset=utf-8")
                    .addJSONObjectBody(bodyJS)
                    .setTag("LoginBySms")
                    .setPriority(Priority.HIGH)
                    .setExecutor(Executors.newSingleThreadExecutor())
                    .build()
                    .getAsParsed(new TypeToken<User>() {}, new ParsedRequestListener<User>() {
                        @Override
                        public void onResponse(User user) {
                            // I need here get result in ThreadA not a Main thread
                            // I need doing something here and I will be call main thread manually self
                            // I have MyApplication.runOnMainThread(new Runnable(){}); code to calling
                            // main thread, but response on main thread.
                           // I need some user operation doing in background not on main thread
                        }
                        @Override
                        public void onError(ANError anError) {
                            HLog.i("ProfileFrag", "error :" + anError + " thread : " + Thread.currentThread().getName());
                        }
                    });
```

do you understand me?

**Comment by amitshekhariitbhu** [comment]
@boyfox  : on using `setExecutor(Executors.newSingleThreadExecutor())` it will send the response in that thread only which you have provided in setExecutor().

**Comment by boyfox** [comment]
@amitshekhariitbhu yes you are right I seen logs onError callback in Android Monitor, thanks you for helping. Getting successfully response on custom thread and error on main thread great job, thanks you very much for great library!

**Comment by boyfox** [comment]
you can close this question i got fully answer to my question!
