### ISSUE TITLE
Throwing me error on OkHttpResponseAndParsedRequestListener

### ISSUE THREAD

**Issue by kafan1986** [amitshekhariitbhu/Fast-Android-Networking#345]
I am using the below code. It is giving me error "Anonymous class derived from OkHttpResponseAndParsedRequestListener must either be declared abstract or implement abstract method onResponse(Response,t) in OkHttpResponseAndParsedRequestListener. Not sure where is the error.

  
AndroidNetworking.post(CommonConstants.getInstance().serverAddress+"/"+CommonConstants.getInstance().getAdCreativesEndpoint)
                             .addBodyParameter(afnr) // posting java object
                            .setTag(CommonConstants.getInstance().networkCallTag)
                            .setPriority(Priority.MEDIUM)
                            .build()
                            .getAsOkHttpResponseAndObject(AdFetchNetworkResponse.class,
                                    new OkHttpResponseAndParsedRequestListener<AdFetchNetworkResponse>() {
                                @Override
                                public void onResponse(Response okHttpResponse, AdFetchNetworkResponse afnResponse) {                         }
                               @Override
                               public void onError(ANError error) {               }
                            });

If it helps, below is how I initialized the library.

        // Networking libraries setup
        OkHttpClient okHttpClient = new OkHttpClient().newBuilder().connectTimeout(10, TimeUnit.SECONDS)
                .readTimeout(20, TimeUnit.SECONDS)
                . writeTimeout(20, TimeUnit.SECONDS)
                .addInterceptor(new GzipRequestInterceptor())
                .build();
        AndroidNetworking.initialize(mContext,okHttpClient);
        Gson gson = new GsonBuilder().setLenient().create();

        AndroidNetworking.setParserFactory(new GsonParserFactory(gson));

**Comment by kafan1986** [comment]
import com.google.gson.annotations.SerializedName;
public class AdFetchNetworkResponse {

    @SerializedName("status")
    public boolean Status;

    @SerializedName("message")
    public String Message;

    @SerializedName("rtms")
    public int ResponseTime;

    public AdFetchNetworkResponse(){
        // no-args constructor
    }
}

**Comment by kafan1986** [comment]
@amitshekhariitbhu An additional question. When is the onError called? Any response with 'non-200' http response code triggers this block?

**Comment by amitshekhariitbhu** [comment]
Looks like error with sending data in `afnr` class.

**Comment by kafan1986** [comment]
My class is below

import com.google.gson.annotations.SerializedName;
public class AdFetchNetworkRequest {
    @SerializedName("stoken")
    public String sessionToken;

    @SerializedName("did")
    public String deviceID;

    public AdFetchNetworkRequest(){
        // no-args constructor
    }
}

// Code to create afnr object
AdFetchNetworkRequest afnr = new AdFetchNetworkRequest();
afnr.sessionToken = CommonConstants.getInstance().loginSecretID;
afnr.deviceID = CommonConstants.getInstance().deviceID;

**Comment by kafan1986** [comment]
@amitshekhariitbhu Got it sorted. The Response got imported from wrong package name. Can you answer my previous queries regarding some other stuff?

a) When is the onError called? Any response with 'non-200' http response code triggers this block? Can not find any clear mention in the documentation and not eager to look into the repo.

b) As the library has been set with GSON, would the keys of the serialized JSON be using SerializedName, as per gson functionality?
