### ISSUE TITLE
Wrong calculation of Network Bandwidth Quality 

### ISSUE THREAD

**Issue by liorzam** [amitshekhariitbhu/Fast-Android-Networking#35]
when a network request finished you took the Content-Length and the TimeMS of the request for calculating the quality of the network but there is an additional parameter that you should take care of when you calculating the bandwidth quality: How much requests you perform in parallel during the request because the bandwidth divided for all your request in the app

**Comment by amitshekhariitbhu** [comment]
@liorzam  : This has been taken care.
 But not considered in android versions where TrafficStats is not supported
  ```
       if (startBytes == TrafficStats.UNSUPPORTED || finalBytes == TrafficStats.UNSUPPORTED) {
           diffBytes = okHttpResponse.body().contentLength();
        } else {
            diffBytes = finalBytes - startBytes;
        }
```
Using TrafficStats, we are finding the diffBytes from all parallel calls.
As of now those cases are ignored. Need to fix it in upcoming release.
