### ISSUE TITLE
Header Authentication error

### ISSUE THREAD

**Issue by diegohdez90** [amitshekhariitbhu/Fast-Android-Networking#355]
Error in add header 

I added this code in my `Button` in `onClick` event

```
String encode = android.util.Base64.encodeToString((username + ":" + password).getBytes("UTF-8"), Base64.DEFAULT);
```
where `username` and `password` are strings from `EditText`

In my networking code I wrote
```
AndroidNetworking
....
.addHeaders("Authorization", "Basic " +  encode)
.build();
```
Bui when I press this button appear this code
`java.lang.IllegalArgumentException: Unexpected char 0x0a at 38 in Authorization value: Basic <encode> `

There is something wrong in my code.

**Comment by amitshekhariitbhu** [comment]
You should try adding like this
`addHeaders("Authorization: Bearer ", encode)`

**Comment by amitshekhariitbhu** [comment]
Or try the below link
https://stackoverflow.com/questions/22490057/android-okhttp-with-basic-authentication

**Comment by diegohdez90** [comment]
Thanks @amitshekhariitbhu. Woks good with `Credentials.basic(username, password);`
