### ISSUE TITLE
Question: Is there any option to define bandwidth for request?

### ISSUE THREAD

**Issue by liorzam** [amitshekhariitbhu/Fast-Android-Networking#36]
i want to define the bandwidth of request during sending large file request with poor connectivity connection.
The priorty system doesnt help me in this case, because the request already in process.
it would be great if i could to tell for request to take X% of the bandwitdh.

**Comment by amitshekhariitbhu** [comment]
@liorzam : As of now it is not present. I don't there is any way to do so(restrict the bandwidth) in Android. So, if there is any way that you can tell me to implement will be great. I will be happy to implement. Need your help.

**Comment by liorzam** [comment]
I work on it, I will let you know if I found and solution.
btw I have a hypothesis to solve this problem, if we will change the buffer size that written over the HTTPConnection or to find elegant why to delay writing buffer...
