### ISSUE TITLE
Attempt to invoke virtual method 'okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder()' on a null object reference

### ISSUE THREAD

**Issue by nanchen2251** [amitshekhariitbhu/Fast-Android-Networking#367]
I just get the Exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder()' on a null object reference

And I just use  http.

I do not know the problem,please help me.

that is my code:
Rx2AndroidNetworking.post(HttpConsts.GET_SMS_CODE)
                .addBodyParameter("phone", phone)
                .build()
                .stringObservable
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(object : Observer<String> {
                    override fun onComplete() {
                    }
                    override fun onSubscribe(d: Disposable) {
                    }
                    override fun onError(e: Throwable) {
                        showToast("获取验证码失败：${e.message}")
                    }
                    override fun onNext(t: String) {
                        showToast("获取验证码成功！")
                    }
                })

**Comment by nanchen2251** [comment]
Is it not supporting kotlin?
The error occurred in .stringObservable

**Comment by NikhilBhadouria** [comment]
getting same error in Kotlin, any solution ?

**Comment by Skshakti** [comment]
Register properly in IBM side
