### ISSUE TITLE
onError not called when receiving a StatusCode 400 

### ISSUE THREAD

**Issue by zwirne** [amitshekhariitbhu/Fast-Android-Networking#368]
Hello,

I'm using the following code to delete an user account. When receiving an error 400 the onError method is not called. Could you help me out on this one?

`
AndroidNetworking.post(ApplicationDefines.DELETE_ACCOUNT_ROUTE)
                .addHeaders("authToken", userData.authToken)
                .build()
                .getAsOkHttpResponse(new OkHttpResponseListener() {
                    @Override
                    public void onResponse(Response response) {

                        // do something

                    }

                    @Override
                    public void onError(ANError error) {

                        // this is not called with error code 400

                    }
                });
`

**Comment by amitshekhariitbhu** [comment]
In case of using the getAsOkHttp, all the error from network will come in onResponse

**Comment by zwirne** [comment]
that did the trick. thank you so much!
