### ISSUE TITLE
Supported download resume?

### ISSUE THREAD

**Issue by MahdiPishguy** [amitshekhariitbhu/Fast-Android-Networking#38]
this library could support download resume?

**Comment by amitshekhariitbhu** [comment]
@tux-world presently it is not added, I will try to add it in the upcoming release.

**Comment by mindfreak269** [comment]
need this feature too.

**Comment by amitshekhariitbhu** [comment]
We will try our best to include this in the upcoming new release.

**Comment by amitshekhariitbhu** [comment]
@MahdiPishguy @mindfreak269 I have created new library for pause and resume support. Check [PRDownloader](https://github.com/MindorksOpenSource/PRDownloader).

**Comment by MahdiPishguy** [comment]
@amitshekhariitbhu  Thanks a lot 🥇
