### ISSUE TITLE
Multipart request and JSON body as request

### ISSUE THREAD

**Issue by st-sathish** [amitshekhariitbhu/Fast-Android-Networking#386]
```android
 JSONObject body = new JSONObject();
            body.put("user_id", "1");
            body.put("data", <array data>);
Rx2AndroidNetworking.upload(ApiEndpoints.API_SAVE_ATTRIBUTE_VALUES)
                    .setTag("SAVE_ATTRIBUTE_VALUE")
                    .addMultipartFile("file", mUploadImageFile)
                    .addMultipartParameter("key", body.toString())
                    .build()
                    .getAsJSONObject(new JSONObjectRequestListener() {
                        @Override
                        public void onResponse(JSONObject response) {
                            mValuesHolder = new JSONArray();
                            try {
                                if(mUploadImageFile != null) {
                                    mUploadImageFile.deleteOnExit();
                                }
                                String msg = response.getString("message");
                                popup(msg);
                            } catch (Exception e) {
                                AppLog.error(TAG, e.getMessage());
                            }
                        }
                        @Override
                        public void onError(ANError error) {
                            // handle error
                        }
                    });
```
Hello everyone, I was trying to upload an image and json body to backend php. I have two questions
1. If I send multipart request parameter as Object (tried both JSONObject and Map<String, Object>) seems like both is throwing error like object must start with BEGIN_OBJECT (something) like this so convert into string. How can we solve this?
2. It would be great if someone knows core PHP or provide an link to guide me how to handle this request because I can handle file image but not body data. please look at the below code

```php
$payload = json_decode(file_get_contents("php://input"), false);
$attribute = new Attribute();
$response = array();
try{
	$response["hello"] = $payload;
	$response["test"] = $_FILES['file']['name'];
	if(isset($_FILES['file']['name'])) {
		$file_path = "/<absolute_path>/public/uploaded_images/";
	  	$tmp = explode('.', basename($_FILES["file"]["name"]));
	  	$base_name = date('dmYHis') . '.' . end($tmp);
	  	$payload["image_name"] = $base_name;
	  	$file_path = $file_path . $base_name;
		if(move_uploaded_file($_FILES['file']['tmp_name'], $file_path)) {
		  	$response["message"] = "success";
		} 
		else { 
		  	$response["message"] = "fail";
		}
	} else {
		$response["message"] = "Successfully Created";
	}
    $data = array();
    $response["success"] = 1;
    //$response["message"] = "Successfully Created";
    $response["data"] = $data;
} catch (Exception $e) {
    $response["success"] = 0;
    $response["message"] = $e->getMessage();
    $response["data"] = null;
}
```

**Comment by amitshekhariitbhu** [comment]
Is it working after converting to string?

**Comment by st-sathish** [comment]
No amitshekhariitbhu (sad). Even, I commented the addMultipartFile(API) and cross-checked, I was getting empty value in the server side.

**Comment by st-sathish** [comment]
any updates?

**Comment by st-sathish** [comment]
@amitshekhariitbhu , any updates on this? I put my development on hold please provide the solution

**Comment by st-sathish** [comment]
I think I made a mistake. The file upload parameter value should send through form-data not JSON payload. please confirm and let me know. Otherwise, I will close this issue once I successfully implemented

**Comment by ibrar1988** [comment]
> I think I made a mistake. The file upload parameter value should send through form-data not JSON payload. please confirm and let me know. Otherwise, I will close this issue once I successfully implemented

Any update from your side on it?

**Comment by st-sathish** [comment]
No, @ibrar1988 . I have not yet started to implement. If you need to close this issue? please go a head. If I need to re-open again I will do it once I started to work on it.

**Comment by st-sathish** [comment]
I had used multipart form data and multipart parameter to send request body/payload. Everything is work successfully seamlessely.

**Comment by yogithesymbian** [comment]
`{"error":"array_filter() expects parameter 1 to be array, null given"}`
i can't access the backend 

the backend needed object request for example
```
{
  "file": file,
  "mark" : [
      {
          id: 1,
          name: "yogi"
       }
   ]
}
```

i have use `.toString` but get the errors
