### ISSUE TITLE
Rx integration

### ISSUE THREAD

**Issue by Zeyad-37** [amitshekhariitbhu/Fast-Android-Networking#4]
Are you guys planning to implement rxjava integration

**Comment by amitshekhariitbhu** [comment]
@Zeyad-37  : YES, we are planning to add it. Very soon, we will be adding it.

**Comment by Zeyad-37** [comment]
Ok thats great :) will be looking forward for it

**Comment by amitshekhariitbhu** [comment]
@Zeyad-37 : Now Fast-Android-Networking Supports RxJava [Check Here](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/RxAndroidNetworking.md) Thanks to @PrashantGupta17  for adding support for RxJava. And much more to come.
