### ISSUE TITLE
How to get progress when I use get or post?

### ISSUE THREAD

**Issue by wtchaos** [amitshekhariitbhu/Fast-Android-Networking#40]
Hello!How to get progress when I use get or post?Thank you.

**Comment by amitshekhariitbhu** [comment]
@wtchaos : unfortunately there is no way to get progress in GET/POST. Presently it is only supported in UPLOAD/MULTIPART. By the way, I will try to add support for it in upcoming releases.

Thanks
Amit Shekhar

**Comment by wtchaos** [comment]
Thanks.And I have a few questions.
1.How to set The Cookie?
2.How to set cacheable or uncacheable for some GET/POST method?

Thank you

**Comment by amitshekhariitbhu** [comment]
you can pass custom okHttpClient by setting Cookie in that.
reference link 
http://stackoverflow.com/questions/24263921/how-to-implement-cookie-handling-on-android-using-okhttp
https://amitshekhariitbhu.github.io/Fast-Android-Networking/configure_timeout.html

And for caching, you can refer 
https://github.com/amitshekhariitbhu/Fast-Android-Networking#how-caching-works-

supported methods are `doNotCacheResponse` , `getResponseOnlyIfCached` , `getResponseOnlyFromNetwork`
