### ISSUE TITLE
Enhancement the log system

### ISSUE THREAD

**Issue by johnwatsondev** [amitshekhariitbhu/Fast-Android-Networking#41]
There were some logs by setting `AndroidNetworking.enableLogging();` through a upload file request.

```
D/AndroidNetworking: addRequest: after addition - mCurrentRequests size: 1

D/AndroidNetworking: execution started : ANRequest{sequenceNumber='1, mMethod=1, mPriority=HIGH, mRequestType=2, mUrl=someUrl}

D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='1, mMethod=1, mPriority=HIGH, mRequestType=2, mUrl=someUrl}

D/AndroidNetworking: execution done : ANRequest{sequenceNumber='1, mMethod=1, mPriority=HIGH, mRequestType=2, mUrl=someUrl}

D/AndroidNetworking: finish: after removal - mCurrentRequests size: 0
```

Should it show some HTTP header and body just like okhttp logging system?

Maybe did I just replace the default OkHttpClient with custom OkHttpClient which enable its' logging function? (P.S. I'm a lazy guy. :))

Thanks in advance.

**Comment by amitshekhariitbhu** [comment]
you can add interceptor while initializing it.

by using OkHttp3 Logging Interceptor
```
compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'

HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
logging.setLevel(Level.BASIC);
OkHttpClient okHttpClient = new OkHttpClient() .newBuilder()
                        . addInterceptor(logging)
                        .build();
AndroidNetworking.initialize(getApplicationContext(),okHttpClient);
```

for more refer the link
 https://amitshekhariitbhu.github.io/Fast-Android-Networking/logging.html#logging-it-with-okhttp-logging-interceptor

Thanks
Amit Shekhar

**Comment by johnwatsondev** [comment]
@amitshekhariitbhu  Yup, I knew this way. I just didn't want to set it by hand. Hahaha. :)
