### ISSUE TITLE
Asynchronous task

### ISSUE THREAD

**Issue by Mojtaba-Shafaei** [amitshekhariitbhu/Fast-Android-Networking#42]
Whenever we implement Volley , there is no need to use AsyncTask or IntentService for long time operations to avoid ANR. 

in Fast-Android-Networking , should I use asyncTask ?

thanks

**Comment by amitshekhariitbhu** [comment]
Similar to volley. There is no need to implement async as it makes the request in background thread and returns in main thread 

Thanks 
Amit Shekhar

**Comment by Mojtaba-Shafaei** [comment]
Very interesting.

**Comment by hasnain-ahmad** [comment]
> Similar to volley. There is no need to implement async as it makes the request in background thread and returns in main thread
> 
> Thanks
> Amit Shekhar

when its returns the data on main thread, but i want to parse JSON response and insert the 1000 records in SQLite using ActiveAndroid ORM in android app. Which method of Rx2AndroidNetworking is best for request response to insert data in the db.

**Comment by amitshekhariitbhu** [comment]
@hasnain-ahmad If you use the RxJava version(Rx2AndroidNetworking), you have all control to manage threads.

**Comment by hasnain-ahmad** [comment]
> @hasnain-ahmad If you use the RxJava version(Rx2AndroidNetworking), you have all control to manage threads.

Yes i am using the Rx2AndroidNetworking. Kindly guide me in 2 or 3 lines and mention the specific methods names & its flows.

**Comment by amitshekhariitbhu** [comment]
> > @hasnain-ahmad If you use the RxJava version(Rx2AndroidNetworking), you have all control to manage threads.
> 
> Yes i am using the Rx2AndroidNetworking. Kindly guide me in 2 or 3 lines and mention the specific methods names & its flows.

Yes, here is the complete example: https://github.com/amitshekhariitbhu/RxJava2-Android-Samples/blob/master/app/src/main/java/com/rxjava2/android/samples/ui/networking/NetworkingActivity.java
