### ISSUE TITLE
How do I use addbodyparameter with get request?

### ISSUE THREAD

**Issue by maxdelmore** [amitshekhariitbhu/Fast-Android-Networking#425]
Hello,
I was wondering if its possible to use addbodyparam with rxjava2androidnetworking lib ? I see the query working in postman based on how our server is set up,but theres no way i can add that with rx2networkong android lib. Is there a way around this or anyway I can implement to get this to work? my code is below :

Override
    public Single<MyResponse> getMyApiCall(String userId) {
        return Rx2AndroidNetworking.get(processUrl(ApiEndPoint.MY_ENDPOINT))
                .addPathParameter("userid", userId)
                .addHeaders("Auth", mApiHeader.getFormattedProtectedApiHeader())
//I want the below line to be addBodyParameter, but doesnt work
                .addQueryParameter("my_session_token", mPreferencesHelper.getMyToken())
                .build()
                .getObjectSingle(MyResponse.class);
    }

any ideas?

**Comment by maxdelmore** [comment]
@amitshekhariitbhu @rakshakhegde @BrianOn99 @SUPERCILEX any idea?

**Comment by SUPERCILEX** [comment]
Use retrofit.

**Comment by maxdelmore** [comment]
@SUPERCILEX  is there no possible way to achieve that with Rx2AndroidNetworking ?  Also, does retrofit support get requests with body param? never tried that with body param before

**Comment by SUPERCILEX** [comment]
Lol, sorry, I didn't think you were serious. I haven't used this library in years, so I don't if it's possible.

Regardless, if you're just starting Android, I would highly recommend using Retrofit instead. Just google the name and you'll get tons of resources since the library has been around forever and is an industry standard. In terms of networking basics, you can't send a body in a GET request. You'd have to make it a POST on the server or use query parameters, URL path params, etc.

**Comment by maxdelmore** [comment]
thats what i ended up doing, using query params on the server. i wish there was a way to use body with get request. do you happen to have any idea, why its not included?

**Comment by SUPERCILEX** [comment]
Because that's not how REST works:
> Yes. In other words, any HTTP request message is allowed to contain a message body, and thus must parse messages with that in mind. Server semantics for GET, however, are restricted such that a body, if any, **has no semantic meaning to the request**. The requirements on parsing are separate from the requirements on method semantics.
> 
> So, yes, you can send a body with GET, and no, it is never useful to do so.
> 
> This is part of the layered design of HTTP/1.1 that will become clear again once the spec is partitioned (work in progress).
> 
> ....Roy

**Comment by maxdelmore** [comment]
thanks cutie
