### ISSUE TITLE
BitmapFactory.Options and Utils.decodeBitmap()

### ISSUE THREAD

**Issue by andreaboi83** [amitshekhariitbhu/Fast-Android-Networking#43]
Hi, you are doing a very nice job with your "hybrid" networking library!!! I was looking for a new networking lib for Android, with both the advantage of OkHttp and Volley (especially for the image part). However, as in the Volley lib, I can't set the BitmapFactory.Options flags that I need.

Is it possible to add a method like decodeBitmap but with the ability of pass a BitmapFactory.Options object instead of the Bitmap.Config? The best solution should be pass a "base" config to the main instance of the AndroidNetworking, so that the same config can be used for all bitmap decoding processes.

I really need this feature, because in some device I need to set on BitmapFactory.Options some other flags (like inPurgeable) for avoiding OOMs.

Please, help me :)! Thanks in advance.

**Comment by amitshekhariitbhu** [comment]
@andreaboi83  : Glad to hear it that you liked the library, your suggestion is awesome, I will add it in the upcoming release.

Thanks
Amit Shekhar

**Comment by andreaboi83** [comment]
@amitshekhariitbhu Thank you so much!!!
