### ISSUE TITLE
Error code is 0 

### ISSUE THREAD

**Issue by eypibee** [amitshekhariitbhu/Fast-Android-Networking#433]
Hi @amitshekhariitbhu , I am currently facing with this kind of error.

![error](https://user-images.githubusercontent.com/46506486/60059014-3de87100-971d-11e9-9d6a-a42babeb83ad.JPG)

The `ANError` returns an error code 0 with no error detail. I need to view the `cause` to see its detailed cause.

**Comment by amitshekhariitbhu** [comment]
We will improve this in a new release.
