### ISSUE TITLE
Delete request execution

### ISSUE THREAD

**Issue by eypibee** [amitshekhariitbhu/Fast-Android-Networking#441]
hi @amitshekhariitbhu , I'm having trouble with the response from server when request method is delete. Due to framework restriction, the server responds with an unparsable value throwing `java.io.EOFException`. I want to atleast parse it to String but the method `getObjectObservable(Class<T> objectClass)` has a default value of `ResponseType.PARSED`. This is my code:

'Rx2AndroidNetworking.delete(baseUrl)
            .addHeaders(mHeadersMap)
            .addPathParameter(pathParametersMap)
            .addQueryParameter(queryParametersMap)
            .setTag(mCurrentRequestTag)
            .build()
            .getObjectObservable(clazz) // clazz should be String 
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(object : Observer<T> {

                lateinit var disposable: Disposable

                override fun onComplete() {
                    startDisposal(disposable)
                }

                override fun onSubscribe(d: Disposable) {
                    disposable = d
                }

                override fun onNext(result: T) {
                    apiResponse.onSuccess(result as Any)
                }

                override fun onError(e: Throwable) {
                    apiResponse.onFailure(e as ANError)

                    startDisposal(disposable)
                }

            })'

Temporarily, I used `getOkHttpResponse` but still hoping to get an observable response. Thanks.

**Comment by amitshekhariitbhu** [comment]
Have you tried `getStringObservable`?

**Comment by eypibee** [comment]
> Have you tried `getStringObservable`?

It worked! Thanks. 

One more question. What if I want to also include the headers in an `Observable` response? The only way it can be done as I look in the documentation is through `OkHttpResponse`.

**Comment by amitshekhariitbhu** [comment]
Yes as of now, the only way is to use the `OkHttpResponse`
