### ISSUE TITLE
Error when trying to upload zip file 

### ISSUE THREAD

**Issue by Dverybest** [amitshekhariitbhu/Fast-Android-Networking#442]
com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR

**Comment by amitshekhariitbhu** [comment]
@Dverybest problem solved or still facing?

**Comment by petarljubic** [comment]
I have same problem and can't solve it. I try to upload image on Huawei P20 Lite, and get this error

**Comment by Dverybest** [comment]
I have solved the problem. I found out the issue was form the file uri
