### ISSUE TITLE
 org.json.JSONException: Value <div of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by sachinharne** [amitshekhariitbhu/Fast-Android-Networking#446]
Hello, I am getting error while parsing json object as com.androidnetworking.error.ANError: org.json.JSONException: Value <div of type java.lang.String cannot be converted to JSONObject

Please help

**Comment by amitshekhariitbhu** [comment]
Your server is not sending correct JSON. Please check.

**Comment by sachinharne** [comment]
Thanks,
Issue is resolved.
