### ISSUE TITLE
socket time exception in android networking

### ISSUE THREAD

**Issue by Vishal6ji2** [amitshekhariitbhu/Fast-Android-Networking#449]
com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: java.net.SocketTimeoutException: timeout 

there is this error today but yesterday there is no such  type error why?
Is it server side problem because i use 000webhostapp server . Please help me .

**Comment by amitshekhariitbhu** [comment]
It's a server-side problem. You can try increasing the timeout to solve from client end too.

**Comment by Vishal6ji2** [comment]
Ok  my problem solved.

**Comment by Vishal6ji2** [comment]
Thanks sir
