### ISSUE TITLE
Invalidate url from cache after I get response ? 

### ISSUE THREAD

**Issue by rene-dohan** [amitshekhariitbhu/Fast-Android-Networking#45]
Well I found workaround but kind of ugly...

```
public static void invalidate(String url) {
        try {
            Iterator<String> it = _client.cache().urls();
            while (it.hasNext()) {
                String next = it.next();
                if (next.contains(url)) it.remove();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

**Comment by amitshekhariitbhu** [comment]
@rene-dohan : I did not get the use-case. Can u tell me in more details?
Anyway, you can use `doNotCacheResponse()` to tell the request that it should not be cached.

for more refer
 https://amitshekhariitbhu.github.io/Fast-Android-Networking/caching.html#do-not-cache-response

**Comment by rene-dohan** [comment]
A recieve response , and the response is for example some exception on server. Then I don't want to cache that response at all. But I know this after I get de response not before.

**Comment by amitshekhariitbhu** [comment]
@rene-dohan : I will add it as a simple API in the new version.

**Comment by amitshekhariitbhu** [comment]
Not planned.
