### ISSUE TITLE
Request always fails when the url is an IP address.

### ISSUE THREAD

**Issue by GanzaCharles** [amitshekhariitbhu/Fast-Android-Networking#450]
When I make a request and the url is an IP address, the request always fails as if the server doesn't exist. I've tried making the exact same request using different clients and it works. Please help.

Refer to the code below 

**This works.**
```
//works
AndroidNetworking.get("http://example.com/")
                .addHeaders(AUTHORIZATION, TOKEN_ + token)
                .setPriority(Priority.MEDIUM)
                .build()
                .getAsJSONObject(object : JSONObjectRequestListener {
                    override fun onResponse(response: JSONObject) {
                        recentPriceMessage.value = Gson().fromJson(response.toString(), RecentPriceModel::class.java)
                    }
                    override fun onError(anError: ANError) {
                        Log.e("error", anError.errorBody)
                    }
                })

```
**This doesn't work.**
```
//fails
AndroidNetworking.get("http://192.0.0.1/endpoint/")
                .addHeaders(AUTHORIZATION, TOKEN_ + token)
                .setPriority(Priority.MEDIUM)
                .build()
                .getAsJSONObject(object : JSONObjectRequestListener {
                    override fun onResponse(response: JSONObject) {
                        recentPriceMessage.value = Gson().fromJson(response.toString(), RecentPriceModel::class.java)
                    }
                    override fun onError(anError: ANError) {
                        Log.e("error", anError.errorBody)
                    }
                })
```

**Comment by yogeshpaliyal** [comment]
on which android version you are trying

**Comment by GanzaCharles** [comment]
@yogeshpaliyal Pie and Nougat.

**Comment by yogeshpaliyal** [comment]
in pie you should add network config file in xml.

**Comment by GanzaCharles** [comment]
@yogeshpaliyal okay, but that would still leave me with the issue of it failing on Nougat, assuming that config file would solve it.

**Comment by yogeshpaliyal** [comment]
Can you provide the exact error

**Comment by GanzaCharles** [comment]
@yogeshpaliyal there is technically no error message but the status code is 0 which means no network or the server doesn't exist.

**Comment by yogeshpaliyal** [comment]
try hitting url in browser or postman

**Comment by kafan1986** [comment]
I am facing issue too. I am using Android Pie.

**Comment by GanzaCharles** [comment]
@kafan1986 I included `android:usesCleartextTraffic="true"` in the manifest file, inside the application tag. It seems to allow insecure connections but I haven't tested for ip address urls again yet. I think it should work though.

**Comment by kafan1986** [comment]
> @kafan1986 I included `android:usesCleartextTraffic="true"` in the manifest file, inside the application tag. It seems to allow insecure connections but I haven't tested for ip address urls again yet. I think it should work though.

Yes. It works.
