### ISSUE TITLE
om.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by niravtopsy** [amitshekhariitbhu/Fast-Android-Networking#460]
I am using Rx2AndroidNetworking for web service call.
After my web service change from the "http" to "https" i am frequently getting below error.
Out of 10 case i am getting 2 time this error.

> SSL handshake aborted: ssl=0x7f7c95d8c8: I/O error during system call, Connection reset by peer
> 
> com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7f7c95d8c8: I/O error during system call, Connection reset by peer
> at com.rx2androidnetworking.Rx2InternalNetworking$SimpleANObservable.subscribeActual(Rx2InternalNetworking.java:235)
> at io.reactivex.Observable.subscribe(Observable.java:12005)
> at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
> at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
> at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
> at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
> at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> at java.lang.Thread.run(Thread.java:818)
> 
> Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7f7c95d8c8: I/O error during system call, Connection reset by peer
> at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
> at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@19629019@19.6.29 (040400-278422107):6)
> at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19629019@19.6.29 (040400-278422107):14)
> at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
> at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
> at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
> at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
> at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
> at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
> at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
> at okhttp3.RealCall.execute(RealCall.java:92)
> at com.rx2androidnetworking.Rx2InternalNetworking$SimpleANObservable.subscribeActual(Rx2InternalNetworking.java:187)

i am tried following solutions for it but don't work, 

> try {
>             SSLContext.getInstance("TLSv1.2");
>         } catch (NoSuchAlgorithmException e) {
>             e.printStackTrace();
>         }
>         try {
>             ProviderInstaller.installIfNeeded(mContext.getApplicationContext());
>         } catch (GooglePlayServicesRepairableException e) {
>             e.printStackTrace();
>         } catch (GooglePlayServicesNotAvailableException e) {
>             e.printStackTrace();
>         }

So, How to outcome from the these issue? @amitshekhariitbhu

**Comment by ddopik** [comment]
have same Issues but for each request using android API 18

**Comment by amitshekhariitbhu** [comment]
@ddopik I guess you have solved it using the [reference](https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/297)

**Comment by niravtopsy** [comment]
@amitshekhariitbhu i upload one app with TrustManager[] trustAllCerts but its rejected by google play store, So, I think it not final solutions.
