### ISSUE TITLE
Set default event for all request

### ISSUE THREAD

**Issue by pesvn20** [amitshekhariitbhu/Fast-Android-Networking#47]
Can i set default function call back when get result from the server? In my case, if error code = 401 i want to change specific activity (I want write 1 time for all request, not write many times on all request).

**Comment by amitshekhariitbhu** [comment]
@pesvn20  Presently there is no such things, but will try to add in upcoming release.

Thanks
Amit Shekhar

**Comment by amitshekhariitbhu** [comment]
Did get a generic use case.
