### ISSUE TITLE
Upload progress for PUT request

### ISSUE THREAD

**Issue by iTruff** [amitshekhariitbhu/Fast-Android-Networking#48]
Can you please add upload progress support for PUT requests?

**Comment by amitshekhariitbhu** [comment]
@iTruff : Few more developers have requested this support, The new version will come with this support.

Thanks
Amit Shekhar

**Comment by iTruff** [comment]
@amitshekhariitbhu Thank you for quick answer. Can you provide us with any info about when new version will be?

**Comment by amitshekhariitbhu** [comment]
Coming weekend

**Comment by iTruff** [comment]
@amitshekhariitbhu Cool, thank you. Will do all things. 👍
