### ISSUE TITLE
com.androidnetworking.error.ANError

### ISSUE THREAD

**Issue by meriem1998** [amitshekhariitbhu/Fast-Android-Networking#489]
I try to send this request : 
` AndroidNetworking.initialize(context)
                    AndroidNetworking.post(URL)
                        .addBodyParameter("p1", "value1")
                        .setTag("test")
                        .setPriority(Priority.HIGH)
                        .build()
                        .getAsJSONObject(object : JSONObjectRequestListener {
                            override fun onResponse(response: JSONObject) {
                                // do anything with response
                        
                            }

                            override fun onError(error: ANError) {
                                // handle error
                                throw error
                            }
                        })`
in my android app the request is written in a fragment in my onactivitycreated function with kotlin but this error is returned :
`W/System.err: com.androidnetworking.error.ANError
W/System.err:     at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:80)
W/System.err:     at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by NotNotMarshall** [comment]
Instead of throwing the error log the important parts of it like the error.details and error.code and error.response.message

By the way can you post the actual code? You just posted a test copy-paste from the docs.
