### ISSUE TITLE
onError method of DonwloadListener is not invoked when downloading error

### ISSUE THREAD

**Issue by zachgenius** [amitshekhariitbhu/Fast-Android-Networking#49]
My code is the same with the tutorial. But when I start downloading and something wrong with the priority, the downloading thread just stopped without any callback. I reviewed the code and found that methods in mDownloadListener and mUploadListener are not invoked in ANRequest.deliverErrorResponse(). Is it a bug?

**Comment by amitshekhariitbhu** [comment]
Thanks @zachgenius for reporting this bug, It's a mistake from my side,  I will correct it in the new release.

Thanks
Amit Shekhar
