### ISSUE TITLE
Enable Caching without Server Headers Change

### ISSUE THREAD

**Issue by grndvl1** [amitshekhariitbhu/Fast-Android-Networking#492]
I have no control over the headers in a API I am using from boardgamegeek and that API is pretty stale.  How can I get the cache to work without mucking with the server headers?  Need to try to cache due to the limits BGG puts on their free API, once my app goes out in the world I may start hitting some limitations due to too many calls.

**Comment by amitshekhariitbhu** [comment]
Follow this blog: https://blog.mindorks.com/okhttp-interceptor-making-the-most-of-it
