### ISSUE TITLE
how to disable caching and only receive from network?

### ISSUE THREAD

**Issue by glomowa** [amitshekhariitbhu/Fast-Android-Networking#493]

**Comment by amitshekhariitbhu** [comment]
Use `.doNotCacheResponse()` or `.getResponseOnlyFromNetwork()`
Find complete document [here](https://amitshekhar.me/Fast-Android-Networking/caching.html).

**Comment by glomowa** [comment]
what if i use both, since im using .getResponseOnlyFromNetwork() sometimes still getting same old result..

**Comment by amitshekhariitbhu** [comment]
Only `getResponseOnlyFromNetwork()` should work. Also, check the data your server is sending.

**Comment by glomowa** [comment]
so which one is better?

**Comment by amitshekhariitbhu** [comment]
`doNotCacheResponse()` 
As it will not save the data which is not required. Make sure the uninstall the app and then test it.
