### ISSUE TITLE
Question: Can library support optional query parameters?

### ISSUE THREAD

**Issue by boyfox** [amitshekhariitbhu/Fast-Android-Networking#50]
So, I want call to google place autocomplete api, exists "language" query parameter in api and this parameter is optional, may be will be value or not. And my question do support library optional query parameter, library will be skip if I call AndroidNetworking library like as :

    AndroidNetworking.get("https://maps.googleapis.com/maps/api/place/autocomplete/json")
         .addQueryParameter("input", "Berlin")
         .addQueryParameter("language", null)
         .setExecutor(Executors.newSingleThreadExecutor())
        .setTag("placeReq")
        .build()
        .getAsJSONObject(new JSONObjectRequestListener() {
            @Override
            public void onResponse(JSONObject response) {}
            @Override
            public void onError(ANError anError) {}
        });

?
Thank you for advance!

**Comment by amitshekhariitbhu** [comment]
You can do so and also can be done in an another way, refer the link
https://amitshekhariitbhu.github.io/Fast-Android-Networking/building_a_request.html

Thanks
Amit Shekhar

**Comment by boyfox** [comment]
Thank you for helping!
