### ISSUE TITLE
Connection always return UNKNOWN

### ISSUE THREAD

**Issue by ubedthaheem** [amitshekhariitbhu/Fast-Android-Networking#502]
Hi Amit, i was trying to check internet connection with perfect bandwidth for my app, but there might be error with `AndroidNetworking.getCurrentBandwidth()`. 
here is method which created 
 

> private boolean isInternetConnection(){
        int currentBandwidth = AndroidNetworking.getCurrentBandwidth();
        if (currentBandwidth > 0){
            Log.d(TAG, "isInternetConnection: internet available and bandwidth is " + currentBandwidth);
            return true;
        }
        Log.d(TAG, "isInternetConnection: internet connection bandwidth = 0");
        return false;
    }

i am using WIFI internet with > 300KB/s speed but log returns 0 bandwidth
`2020-04-27 02:03:39.968 15346-15346/? D/HomeFragment: isInternetConnection: internet connection bandwidth = 0`

**Comment by aminPial** [comment]
Try to make some requests to get the current Bandwidth

**Comment by amitshekhariitbhu** [comment]
Correctly suggested by @aminPial, closing this issue.
