### ISSUE TITLE
Is it possible to upload document from Uri without getting File Path?

### ISSUE THREAD

**Issue by Dhaval2404** [amitshekhariitbhu/Fast-Android-Networking#503]
Recently,  I've added support for Android 10 Scoped Storage in my app. Using Document Picker I'm able to get Image Uri. Now I want to upload it to the server, I have not defined any storage permission in my app. And Still, I can access images due to the storage access framework. If I convert Uri to the file path, I will lose access to the image in Android 10+ devices.

Therefore, I'm looking for a way to upload an image from Uri or InputStream. Is there any option available in this lib?

**Comment by amitshekhariitbhu** [comment]
Currently only throughout the path

**Comment by Dhaval2404** [comment]
@amitshekhariitbhu Thanks for the quick reply.
