### ISSUE TITLE
Gif Image support

### ISSUE THREAD

**Issue by asker517** [amitshekhariitbhu/Fast-Android-Networking#51]
it seems powerful library,can make it load gif image from network?

**Comment by amitshekhariitbhu** [comment]
@asker517 I am glad u liked it, I will be adding GIF support in upcoming release

Thanks
Amit Shekhar

**Comment by amitshekhariitbhu** [comment]
The library size will increase by more than 100% so better use any image loading library like Glide or Fresco.
