### ISSUE TITLE
com.androidnetworking.error.ANError: android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by navidsol9** [amitshekhariitbhu/Fast-Android-Networking#527]
Hi @amitshekhariitbhu I am using your library to run GET/POST on Android 10. If I use this version:

AndroidNetworking.get("http://api.localhost.com/{pageNumber}/test")
                 .addPathParameter("pageNumber", "0")
                 .addQueryParameter("limit", "3")
                 .addHeaders("token", "1234")
                 .setTag("test")
                 .setPriority(Priority.LOW)
                 .build()
                 .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                    // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                    // handle error
                    }
                });

after getAsJSONArray it jumps off the code, hence no response.

                                                                                         *****

And if I code it this way:

        ANRequest request = AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                .setTag("test")
                .setPriority(Priority.MEDIUM)
                .setExecutor(Executors.newSingleThreadExecutor()) 
                .build();
        ANResponse response = request.executeForJSONObject();
        if (response.isSuccess()) {
            result[0] = String.valueOf(response.getResult());
                    Log.d(TAG, "response : " + result[0]);
        } else {
            ANError error = response.getError();
            Log.d(TAG, "response : " + error);
        }

I get this error: ANError: com.androidnetworking.error.ANError: android.os.NetworkOnMainThreadException

I am bit lost and would appreicate your insight.

**Comment by LucianoVandi** [comment]
@navidsol9 I'm having the same issue using the synchronous requests. On other issues I've seen @amitshekhariitbhu mentioning about `.setExecutor(Executors.newSingleThreadExecutor()) ` but that make no difference.

**Comment by navidsol9** [comment]
It now works for me after downloading the whole project with numerous libraries. Don't just copy paste the GET, POST routines. They work normal within the Github program. I then had to adapt the project and remove what I didn't need. https://github.com/amitshekhariitbhu/Fast-Android-Networking

**Comment by navidsol9** [comment]
It now works for me. Don't just copy paste the GET, POST routines that appear in some forums. Download the whole project which will take care of multithreading: https://github.com/amitshekhariitbhu/Fast-Android-Networking. and comment the functions you don't need.

**Comment by amitshekhariitbhu** [comment]
Nicely suggested by @navidsol9. So, closing this issue for now.
