### ISSUE TITLE
post request does not take effect after it is set setcontenttype()

### ISSUE THREAD

**Issue by jzh1996** [amitshekhariitbhu/Fast-Android-Networking#530]
The setcontenttype() of the post request does not take effect after it is set, and the addition of. Addheaders ("content type", "application / JSON") in addheaders() does not take effect. An error of content type 'application / x-www-form-urlencoded; charset = UTF-8' not supported is reported

**Comment by amitshekhariitbhu** [comment]
We can use `setContentType`
