### ISSUE TITLE
Expected literal value at character problem

### ISSUE THREAD

**Issue by SalihCanBinboga** [amitshekhariitbhu/Fast-Android-Networking#531]
Hello i have a error Expected literal value at character 45869 of

Json data: https://raw.githubusercontent.com/aoguk/data/master/all.json

**Comment by amitshekhariitbhu** [comment]
Can you please tell me a little bit about the model class you have created and the code snippet you are using?

**Comment by SalihCanBinboga** [comment]
> Can you please tell me a little bit about the model class you have created and the code snippet you are using?

`AndroidNetworking.get("https://raw.githubusercontent.com/aoguk/data/master/all.json")
                 .build()
                 .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                      // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                      // handle error
                    }
                });`

i am using this code snippet work to onError method

**Comment by amitshekhariitbhu** [comment]
Hi @SalihCanBinboga 

I tried it, it is working.

```
AndroidNetworking.get("https://raw.githubusercontent.com/aoguk/data/master/all.json")
                .build()
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                        Log.d(TAG, "onResponse object : " + response.toString());
                    }

                    @Override
                    public void onError(ANError error) {

                    }
                });
```

the output is: onResponse object : {"ag":{"001":{"team":"ag","name":"Ri.......

**Comment by amitshekhariitbhu** [comment]
Closing this, as this is not an issue.
