### ISSUE TITLE
Same_host Socketing

### ISSUE THREAD

**Issue by Studiodews** [amitshekhariitbhu/Fast-Android-Networking#536]
Hello Please I just want you to explain something you mentioned on a post on stackoverflow.
 
Statement:
Fast Android Networking Library supports HTTP/2 support allows all requests to the same host to share a socket

Source:
https://stackoverflow.com/questions/16902716/comparison-of-android-networking-libraries-okhttp-retrofit-and-volley

My question is how do I do the same host Socketing?

**Comment by amitshekhariitbhu** [comment]
It works on top of OkHttp. Also, check [this](https://square.github.io/okhttp/3.x/okhttp/okhttp3/ConnectionPool.html) for more.
