### ISSUE TITLE
OAuth2.0 integration

### ISSUE THREAD

**Issue by SimoneCarnio** [amitshekhariitbhu/Fast-Android-Networking#54]
Hi, 
any plan to integrate  OAuth2.0 functionalities?  
It would be nice if the library automagically manage login and token related task (get, refresh, etc). 
So, once the client is authenticated, authenticate header will be added on every API call and if expired, automatically renewed (with Password Grant Type)

**Comment by amitshekhariitbhu** [comment]
I have planned to do so in upcoming release, will be happy if somebody can do and make the pull request. :)

As you can customize okHttpClient while initializing it ([refer this link](https://amitshekhariitbhu.github.io/Fast-Android-Networking/custom_okHttpClient.html)) 

One solution can be referred from this [link](http://lgvalle.xyz/2015/07/27/okhttp-authentication/
)

Thanks
Amit Shekhar

**Comment by SimoneCarnio** [comment]
Hope someone else will read this issue, I've started developing on Android and Java 1 week ago, so, do not rely on me for the moment :)

This morning I was looking at these, but I not ready yet to understand how all these thing works together :)

https://github.com/JakeWharton/u2020/tree/master/src/main/java/com/jakewharton/u2020/data/api/oauth

https://github.com/previousdeveloper/Retrofit.OAuth-2

**Comment by amitshekhariitbhu** [comment]
I will add it in new release. :)

**Comment by SimoneCarnio** [comment]
I've done this in php/js/Objective c and python, in Java I still have to take confidence

**Comment by omar25h** [comment]
Hi, I would like to know if anyone is currently working on this or I should give it a try

**Comment by amitshekhariitbhu** [comment]
@omar25h let's discuss about the implementation to take it forward.

**Comment by omar25h** [comment]
Alright, 
I was thinking about having an OkHttp Authenticator which takes the url to refresh the token and client id and client secret as parameters. In the `authenticate()` method, we have create another okhttpclient that connects to the some URL and get the token and update the locally stored tokens (synchronously). I know this is probably not the best way but I couldn't think of something better. Any ideas?

**Comment by amitshekhariitbhu** [comment]
Looks good to me.

**Comment by omar25h** [comment]
Shall we  assume that the tokens should be stored somewhere? for example in the shared preferences since we need to update the stored tokens to avoid calling the authorization route each time the application starts.

**Comment by amitshekhariitbhu** [comment]
The user of the library should pass the object which will implement library's interface to get and put the preferences.

Example:
The library interface:
```
public interface FANTokenManager{
    void getAccessToken();
    void setAccessToken();
    void getRefreshToken();
    void setRefreshToken();
}
```
User class:
```
public MyTokenManager implements FANTokenMananger{

}
```

While initializing library, this object should be passed.

**Comment by omar25h** [comment]
Yeah that's better

**Comment by omar25h** [comment]
@amitshekhariitbhu I have added a new pull request. Let me know if any modifications are needed #110

**Comment by amitshekhariitbhu** [comment]
Awesome, I will go through it and discuss with you.

**Comment by brunovsiqueira** [comment]
It was added? Is there any documentation in how to implement OAuth2.0?

**Comment by einschneidend** [comment]
> It was added? Is there any documentation in how to implement OAuth2.0?

did you manage to figure it out?

**Comment by brunovsiqueira** [comment]
@einschneidend no, I am not using this lib anymore.
