### ISSUE TITLE
How to Make POST request 'blocking' in AndroidNetworking library

### ISSUE THREAD

**Issue by PeterNdomano** [amitshekhariitbhu/Fast-Android-Networking#540]
I was wondering how I could make POST request block other lines of code from executing (some sort of synchronous req) till the request is finished and response is obtained back.

Check in the example below (just summarized)

`

public  boolean auth(String userId, String token)
    {
        isAuthed = false;
        AndroidNetworking.post(mainUrl+"/auth.php")
                .addBodyParameter("userId", userId)
                .addBodyParameter("token", token)
                .setTag("AUTH")
                .setPriority(Priority.HIGH)
                .build()
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {

                        try {
                            int status = response.getInt("status");

                            if(status == 1)
                            {
                                isAuthed = true;//this too delays to run
                                Toast.makeText(activity, "Here...i", Toast.LENGTH_SHORT).show();//this delays to run
                            }
                        } catch (JSONException e) {
                            e.printStackTrace();

                        }
                    }

                    @Override
                    public void onError(ANError anError) {

                    }
                });
        
        return isAuthed; //this runs first hence returning false while in above lines I changed to true but due to delay it's not executed on time
    }

`

**Comment by amitshekhariitbhu** [comment]
Hi @PeterNdomano 
You will have to use the Synchronous Request, please check the example [here](https://amitshekhar.me/Fast-Android-Networking/synchronous_request.html).
