### ISSUE TITLE
connectionError(ErrorCode=0) on Android 4.X devices 

### ISSUE THREAD

**Issue by nigharsh** [amitshekhariitbhu/Fast-Android-Networking#55]
I'm getting a connection error with error code 0 on 4.X devices. I've tested on 4.1.1 and 4.4.4 with same results.

**Comment by nigharsh** [comment]
It was an SSL error. Looks like Android SDK 20 introduced TLSv1.2 and <20 doesn't. Forcing my server to use TLSv1 didn't look like a good option so I forced my app to use TLSv1.2 and it's working fine for now. 
It would be great if we can have in built TLSv1.2 support for older devices.

**Comment by amitshekhariitbhu** [comment]
fixed by updating okHttp library

**Comment by veersamrat** [comment]
That means need to use okHttp library separately ?.

**Comment by amitshekhariitbhu** [comment]
We have updated it in development, soon we will release it.

**Comment by preyesm** [comment]
Have you released with the above changes?

**Comment by amitshekhariitbhu** [comment]
Yes already released.

**Comment by preyesm** [comment]
But i still get this connectionError and errorCode = 0 error.
AndroidNetworking.get("api1.agentdesks.com/v2.0/user")
                    .addHeaders(NetworkUtil.getAgentDeskSpecificHeaders())
                    .build()
                    .getAsObject(ResponseWrapper.class, new ParsedRequestListener<ResponseWrapper>() {
                        @Override
                        public void onResponse(ResponseWrapper response) {
                            if (response.response instanceof AgentProfile) {
                                System.out.println("agent profile from android networking" + ((AgentProfile) response.response).getFirstName());
                            }
                        }

                        @Override
                        public void onError(ANError anError) {
                            System.out.println("error code" + anError.getErrorCode());
                            System.out.println("android networking error handled");
                        }
                    });
        } catch (Exception e) {
            e.printStackTrace();
        }
This is  my snippet

**Comment by amitshekhariitbhu** [comment]
Is the problem only coming on Android 4.X?

**Comment by preyesm** [comment]
No I am Android 7.0.

**Comment by amitshekhariitbhu** [comment]
I am just confirming, is that correct? Should not be like this:
```
getAsObject(ResponseWrapper.class, new ParsedRequestListener<ResponseWrapper>() {
                     @Override
                     public void onResponse(ResponseWrapper response) {
                        // do anything with response
                     }
                     @Override
                     public void onError(ANError anError) {
                        // handle error
                     }
                 }); 
```

**Comment by amitshekhariitbhu** [comment]
And one more thing, is your server receiving the request?

**Comment by preyesm** [comment]
You mean to say I have built in some wrong parameter. Yes, this is how I am using the above code as you have specified

**Comment by amitshekhariitbhu** [comment]
new ParsedRequestListener<ResponseWrapper>()  instead of new ParsedRequestListener()

**Comment by amitshekhariitbhu** [comment]
Let me check it once. Can I get the headers?

**Comment by preyesm** [comment]
could you explain me new "ParsedRequestListener() instead of new ParsedRequestListener()"
?

**Comment by preyesm** [comment]
and for the serve, in the existing infrastructure setup that we are using, we get the requests. I was thinking if you were asking, that did the request from your library hit the server.

**Comment by amitshekhariitbhu** [comment]
Did the request from FAN library hit the server?

**Comment by preyesm** [comment]
nope.

**Comment by preyesm** [comment]
Hey @amitshekhariitbhu, is there anything you could guide me with in using the library?

**Comment by amitshekhariitbhu** [comment]
I am not able to replicate at my end

**Comment by praveen-pro** [comment]
Even I'm facing the same issue on Android 7, @preyesm and @amitshekhariitbhu could you please tell me the solution.

**Comment by djoks** [comment]
Having the same issue after updating my android studio and gradle to latest version and migrating project to androidx.

**Comment by vishaltarsariya** [comment]
Android 9 pie getting this error.

2019-06-07 12:00:44.793 17196-17196/com.app.company D/---FAIL-1--: 0
2019-06-07 12:00:44.794 17196-17196/com.app.company D/---FAIL-2--: null
2019-06-07 12:00:44.794 17196-17196/com.app.company D/---FAIL-3--: connectionError
2019-06-07 12:01:06.969 17196-17215/com.app.company D/EGL_emulation: eglMakeCurrent: 0xe5189440: ver 2 0 (tinfo 0xe51b1a30)

**Comment by shmruin** [comment]
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
