### ISSUE TITLE
jcenter() shutdown

### ISSUE THREAD

**Issue by MarcoMirisola** [amitshekhariitbhu/Fast-Android-Networking#554]
Hello, since jCenter will be shutdown on 2022-02-01 are you planning to move the library to maven() or somewhere else?

**Comment by TkgJamuKeliling** [comment]
in the meantime, I followed the advice from the link [https://stackoverflow.com/a/67423513](url)

**Comment by MarcoMirisola** [comment]
> in the meantime, I followed the advice from the link [https://stackoverflow.com/a/67423513](url)

I tried your advice, but one I remove jCenter() and clean/rebuild project it will stop find the library. Does it work for you?

I also like to know if this library is still supported or not, and if you know some alternative to it.

**Comment by amitshekhariitbhu** [comment]
@mwshubham Can you suggest something here? Possible solution.

**Comment by amitshekhariitbhu** [comment]
@MarcoMirisola We will update it accordingly.

**Comment by mwshubham** [comment]
We don't have to follow the AS advice to remove jcenter for now. Yes @amitshekhariitbhu sir, we can update this library this month to jcenter alternative as it is heavily used. Adding this to our todo 👍

**Comment by n-droidev** [comment]
You can use it via jitpack.. Add this: 
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}


dependencies {
		implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:v1.0.2'
	}

**Comment by shubham-gupta-16** [comment]
The Jitpack library version works fine without adding jcenter(). But I like to see the official alternative.

**Comment by purjahini** [comment]
> mplementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:v1.0.2'

thanks it this solution for my problem

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```
