### ISSUE TITLE
the implement of ConnectionQuality may not very gracefully

### ISSUE THREAD

**Issue by leokelly** [amitshekhariitbhu/Fast-Android-Networking#57]
In code, you just calculate the average of instantaneous speed.
We should't evaluate the quality just by this.

**Comment by leokelly** [comment]
@amitshekhariitbhu

**Comment by amitshekhariitbhu** [comment]
I have considered two cases.
The version which supports traffic stats : Here in a given time frame I am taking the bytes downloaded in all the parallel request.
Maybe I need to fix for the lower version that does not support it.

**Comment by leokelly** [comment]
Though in version that supports traffic stats, we still can't evaluate connectionquality just by calculating the average

**Comment by amitshekhariitbhu** [comment]
Can u suggest me how to implement. I will be happy to implement that in new release.

**Comment by leokelly** [comment]
sorry,I am still looking for a good algorithm to evaluate bandwitdth more accurately, like westwood in tcp.But still not very good.Mobile network is so complicated...

**Comment by amitshekhariitbhu** [comment]
once check this.. same ... I got the idea from here only.
https://github.com/facebook/network-connection-class

**Comment by leokelly** [comment]
Thx~
