### ISSUE TITLE
Downloading Multiple Files breaks DownloadProgressListener

### ISSUE THREAD

**Issue by bikranttripathi** [amitshekhariitbhu/Fast-Android-Networking#58]
Hi,

I was playing around with this library for my project and I noticed this weird behavior with **DownloadProgressListener**.  

If I'm downloading just one file then **DownloadProgressListener** gives me correct progress report but if I'm downloading multiple files then **DownloadProgressListener** sometimes seem to stop progress reporting altogether or only trigger the progress listener callback for 1 file. 

Whereas **DownloadListener** seems to work fine though.

**Comment by amitshekhariitbhu** [comment]
I will check this issue.

Thanks
Amit Shekhar

**Comment by cshah3** [comment]
I am still noticing this issue.

**Comment by amitshekhariitbhu** [comment]
@cshah3  not reproducing at my end. Please tell me.
