### ISSUE TITLE
 jcenter() library does not working

### ISSUE THREAD

**Issue by voobl** [amitshekhariitbhu/Fast-Android-Networking#581]
hello

Failed to resolve: com.amitshekhar.android:android-networking:1.0.2

Hello, is there any help?

**Comment by gandatadyo** [comment]
when create project android studio in android studio bumblebee, jcenter must be add in settings.gradle

**Comment by pioneersingh321** [comment]
try something like this is build.gladle file

`allprojects {
    repositories {
      ....
        maven {
          url = "https://jcenter.bintray.com"
        }
    }
}`

**Comment by RahulGupta2312** [comment]
Update your settings.gradle like this:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = "https://jcenter.bintray.com" }
    }
}
```

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```
