### ISSUE TITLE
AndroidNetworking.initialize(getApplicationContext()); Not working

### ISSUE THREAD

**Issue by raktim1998** [amitshekhariitbhu/Fast-Android-Networking#585]
After adding (implementation 'com.amitshekhar.android:android-networking:1.0.2') this to my  build.gradle.
Error : Cannot resolve symbol 'AndroidNetworking.
Please solve the issue.

**Comment by jayantur13** [comment]
This might be the issue - https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/307
Because Jcenter is going to shutdown soon or may be already shutdown.

**Comment by tauseeqafzal** [comment]
I Have already  followed all steps and the issue #307 guidelines but issue still exist

**Comment by jayantur13** [comment]
I am on latest Android Studio,you may need to update it.Its working fine for me.

**Comment by tauseeqafzal** [comment]
i am also on Latest android Studio

**Comment by jayantur13** [comment]
Oh than, there's something else that needs to fixed by your side or in the dependency itself.

**Comment by tauseeqafzal** [comment]
Sure thanks

**Comment by assmaratib** [comment]
> 

I have the same problem!

**Comment by Talha135** [comment]
Same Problem.
Tell me solution

**Comment by aashisharma1** [comment]
same happens with me

**Comment by DineshDk01** [comment]
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.amitshekhar.android:android-networking:1.0.2.


i got this problem.,if anyone knows pls say?? how can i rectify this

**Comment by Imran1z** [comment]
> After adding (implementation 'com.amitshekhar.android:android-networking:1.0.2') this to my build.gradle. Error : Cannot resolve symbol 'AndroidNetworking. Please solve the issue.

I think I may have found the sollution for the same you have write this in your Setting.gradel file 

 maven {
            url ("https://jcenter.bintray.com")
        }

below the mavenCentral() line and make sure to add the above code to both the places as there you can see two mavenCentral() line in that file

and add the below line in your gradel.properties

android.enableJrtifier=true

**Comment by ricky40kr** [comment]
@Imran1z this works. Thanks

**Comment by amitshekhariitbhu** [comment]
Update:

Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```
