### ISSUE TITLE
Could not find com.amitshekhar.android:android-networking:1.0.2.

### ISSUE THREAD

**Issue by saurabh-proaxiom** [amitshekhariitbhu/Fast-Android-Networking#586]
I have used android studio Chipmunk

My settings.gradle file 

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

**Comment by ALTU-17** [comment]
I also face same problem in bumblebee.... if you found solution so plz share with me
Failed to resolve: com.amitshekhar.android:android-networking:1.0.2

**Comment by sumankhan-android-lover** [comment]
Hello,
 If `jcenter()` is not used in the kotlin project then it will not work properly. Please mention how to resolved this issue in kotlin project at latest version. 

Error :- 
Could not find - com.amitshekhar.android:android-networking:1.0.2.
Required by:
    project :app
[`Search in build.gradle files`](url)

Working : (Note - ` jcenter()` JCenter Maven repository is no longer receiving updates: newer library versions may be available elsewhere )
>    repositories {
        google()
        jcenter() 
        mavenCentral()
    }

Not Working :
> repositories {
        google()
        mavenCentral()
    }

**Comment by soundarya-code** [comment]
> 

thank you sir ,but there small correction you need to add jcenter() in setting.gradle inside of free existing reposities for new android studio dolphin

**Comment by aashisharma1** [comment]
Okey you should add
android.enableJetifier=true in Gradle. property file
and
jcenter()
in gradle.settengs in both plugin management and dependency resolution

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```

**Comment by Crustus** [comment]
I am getting 401 unathorized on jitpack.io server
what about to just move it on different maven repo?

**Comment by AbhinavMalviya58** [comment]
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/amitshekhariitbhu/Fast-Android-Networking/rx-android-networking/1.0.4/rx-android-networking-1.0.4.pom
       - https://repo.maven.apache.org/maven2/com/github/amitshekhariitbhu/Fast-Android-Networking/rx-android-networking/1.0.4/rx-android-networking-1.0.4.pom
     Required by:
         project :app
         





how can i fix this error

**Comment by depezo** [comment]
> ## 1: Task failed with an exception.
> * What went wrong:
>   Execution failed for task ':app:checkDebugAarMetadata'.
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/amitshekhariitbhu/Fast-Android-Networking/rx-android-networking/1.0.4/rx-android-networking-1.0.4.pom
> > - https://repo.maven.apache.org/maven2/com/github/amitshekhariitbhu/Fast-Android-Networking/rx-android-networking/1.0.4/rx-android-networking-1.0.4.pom
> > Required by:
> > project :app
> 
> how can i fix this error

https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/586#issuecomment-2295343752

**Comment by Gate194** [comment]
hola buenas, recien estoy empezando esto de crear apliaciones android y me ha gustado la libreria xgetter pero al momento de agregar la libreria me salta el mismo error com.amitshekhar.android:android-networking:1.0.2 ya intente actualizar la version a 1.0.4 pero me sigue saliendo el mismo error alguna solucion o recomendacion

[](https://i.imgur.com/nem456C.png)

**Comment by veersamrat** [comment]
Same issue, can you help us
