### ISSUE TITLE
 ?Why FAN depends on android.content.Context ?

### ISSUE THREAD

**Issue by kevin-leptons** [amitshekhariitbhu/Fast-Android-Networking#59]
**FAN** is networking library, so why it depends on **android.content.Context**. That make two problems:

- Hard to use. Each times use **FAN**, one times detect android context

- Hard to test. Must use **Mock** on unit test. And it contains many bugs potential

I know that **FAN** may be use few of information from android context, as cache directory. But any one can try other way, to remove depends from **android.content.Context** ?

**Comment by amitshekhariitbhu** [comment]
As you have said, FAN only require for cache directory. You can try it without cache also(do not initilize it).
