### ISSUE TITLE
Failed to resolve:

### ISSUE THREAD

**Issue by okdude24** [amitshekhariitbhu/Fast-Android-Networking#594]
Hello, the module cannot be downloaded
Mac operating system
error:Failed to resolve: com.amitshekhar.android:android-networking:1.0.2

https://s6.uupload.ir/files/screen_shot_2022-10-30_at_4.11.39_pm_ec7f.png

<img width="1280" alt="Screen Shot 2022-10-30 at 4 11 39 PM" src="https://user-images.githubusercontent.com/96055259/198879440-d3e8010d-49c6-48c4-b26e-58a1c852e0d5.png">

**Comment by vmc111** [comment]
Facing Same Problem

**Comment by chinmaydash007** [comment]
I have also facing same issue.

**Comment by paladin952** [comment]
same. this has to be moved to mavenCentral

**Comment by jimfoambox** [comment]
To @paladin952 's point, I have had build errors since yesterday with the same issue and it appears to be because Jcenter is down.  https://status.gradle.com/

@amitshekhariitbhu this is a great library, thank you for all your hard work on it, but I think for it to continue, as with all jcenter libraries, it has to move to mavenCentral because even though Jfrog has stated the read-only version of jcenter will be available (for now), I think the writing is on the wall that jcenter will eventually become unusable and support for outages such as this current one will fade more and more with time.

https://blog.gradle.org/jcenter-shutdown

**Comment by paladin952** [comment]
I suggest you guys check in your ~/.gradle/caches (or the internat) the .aar and put it manually in the project until there is a fix for this.

**Comment by Crustus** [comment]
++ to move

**Comment by pioneersingh321** [comment]
use this will resolve the error 

  maven {
          url = "https://jcenter.bintray.com"
        }

**Comment by danaibrilli** [comment]
Same Problem Here!

**Comment by anilthummar** [comment]
add this lib
  implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:v1.0.2'

**Comment by Dharmiksinhvaja15032004** [comment]
> add this lib implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:v1.0.2'

sem eroor hai to bhi

**Comment by pioneersingh321** [comment]
add dependencies
`
{
implementation 'com.amitshekhar.android:android-networking:1.0.2'
}
`
`
allprojects {
    repositories {
      google()
      mavenCentral()
      jcenter()
    }
}
`

its working for me

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```

**Comment by ShazmaRana** [comment]
> Hello, the module cannot be downloaded Mac operating system error:Failed to resolve: com.amitshekhar.android:android-networking:1.0.2
> 
> https://s6.uupload.ir/files/screen_shot_2022-10-30_at_4.11.39_pm_ec7f.png
> 
> <img alt="Screen Shot 2022-10-30 at 4 11 39 PM" width="1280" src="https://user-images.githubusercontent.com/96055259/198879440-d3e8010d-49c6-48c4-b26e-58a1c852e0d5.png">

Add this in :                 maven { setUrl("https://jitpack.io") }  in your dependencyResolutionManagement of your                 Settings.gradle.kts   file and add dependency :  implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")    in build.gradle.kts     and you are good to go

**Comment by Gate194** [comment]
plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.myapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.myapp"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.github.KhunHtetzNaing:xGetter:3.0'
    implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
}

segui la solucion pero me sale el mismo error
Failed to resolve: com.amitshekhar.android:android-networking:1.0.2

**Comment by ShazmaRana** [comment]
Have you added this : maven { setUrl("https://jitpack.io") } to your
dependencyResolutionManagement
Section of your Settings.gradle.kts file ?
