### ISSUE TITLE
addQueryParameter json object

### ISSUE THREAD

**Issue by FunnyDevs** [amitshekhariitbhu/Fast-Android-Networking#60]
Hi! I have tried to put a json object as query parameters, but there is a problem: The first and last brace ("{" and "}") are not urlencoded, why??? i am not able to send the object with this problem

**Comment by amitshekhariitbhu** [comment]
Let me try it.

**Comment by FunnyDevs** [comment]
I have seen that no brace is encoded, nor [ brace

**Comment by amitshekhariitbhu** [comment]
@FunnyDevs can u tell me through example about the problem u r facing in more detail ?

**Comment by FunnyDevs** [comment]
.addQueryParameter("query", {"key1":"value", "key2": "value"})

when i see the log of okhttp, the query parameter is encoded: {%22key1%22%3A%22value%22%2C%20%22key2%22%3A%20%22value%22%}

insteadof

%7B%22key1%22%3A%22value%22%2C%20%22key2%22%3A%20%22value%22%7D


and so my server is unable to handle the parameter.

**Comment by amitshekhariitbhu** [comment]
can u once try this
```
String query ="{"key1":"value", "key2": "value"}" ;
try {
   query = URLEncoder.encode(query, "UTF-8");
} catch (UnsupportedEncodingException e) {
   e.printStackTrace();
}
.addQueryParameter("query", query);
```

**Comment by FunnyDevs** [comment]
i have just tried, and the problem is a double encoding, so the parameter becams

%7B%2522key1%2522%253A%2522value%2522%252C%2520%2522key2%2522%253A%2520%2522value%2522%25%7D

**Comment by amitshekhariitbhu** [comment]
I think this should work.
```
JsonObject jsonObject = new JsonObject();
jsonObject.addProperty("key1","value1");
jsonObject.addProperty("key2","value2");
addQueryParameter("query", jsonObject.toString())
```

**Comment by FunnyDevs** [comment]
Ok, now it works! Thanks!
