### ISSUE TITLE
AndroidNetworking class is not being imported

### ISSUE THREAD

**Issue by singhdeep02401gmail** [amitshekhariitbhu/Fast-Android-Networking#602]
i already add dependencies implementation 'com.amitshekhar.android:android-networking:1.0.2'
but when i initialize in onCreate method AndroidNetworking.initialize(getApplicationContext());
the Android Studio Cannot resolve the AndroidNetworking.class, and i cannot import it too

**Comment by aashisharma1** [comment]
Okey you should add 
android.enableJetifier=true in Gradle. property file 
and 
jcenter()
in gradle.settengs in both plugin management and dependency resolution

**Comment by HosseinKurd** [comment]
JCenter Maven repository is no longer receiving updates: newer library versions may be available elsewhere

**Comment by rockypatel8757** [comment]
Replace Mavencentral() to jcenter() 
in gradle.settengs in both plugin management and dependency resolution
it will work 100% 😊😊`pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        jcenter()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        jcenter()
    }
}`

**Comment by Ayush9599** [comment]
> Okey you should add android.enableJetifier=true in Gradle. property file and jcenter() in gradle.settengs in both plugin management and dependency resolution

yup it works

**Comment by MurthadaSakhbani** [comment]
I still find the issue even though I have followed your instructions @rockypatel8757 . What should I do?

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```

**Comment by SubhashJadav19** [comment]
Followed all the steps properly sync is also done but still "AndroidNetworking.initialize(getApplicationContext());" is giving red line (error) how to solve it ?

**Comment by wissedenis** [comment]
> Followed all the steps properly sync is also done but still "AndroidNetworking.initialize(getApplicationContext());" is giving red line (error) how to solve it ?

![image](https://github.com/user-attachments/assets/50931114-712f-4f5e-af55-c68bdf0b1c1d)

and use this: implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
it worked for me

**Comment by aniruddha81** [comment]
@wissedenis  it worked bro
