### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by Dharmiksinhvaja15032004** [amitshekhariitbhu/Fast-Android-Networking#607]
Failed to resolve: com.amitshekhar.android:android-networking:1.0.2
Show in Project Structure dialog
Affected Modules: app

this tye isue is use to

**Comment by steve111MV** [comment]
Something like this ?

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.amitshekhar.android:android-networking:1.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/amitshekhar/android/android-networking/1.0.2/android-networking-1.0.2.pom
       - https://repo.maven.apache.org/maven2/com/amitshekhar/android/android-networking/1.0.2/android-networking-1.0.2.pom
     Required by:
         project :app

**Comment by AkinWilderman** [comment]
> Failed to resolve: com.amitshekhar.android:android-networking:1.0.2 Show in Project Structure dialog Affected Modules: app
> 
> this tye isue is use to

Update your repository to include Maven repository

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4")
```

Using the Fast Android Networking with Jackson Parser

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:jackson-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava2

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4")
```

Using the Fast Android Networking with RxJava

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu.Fast-Android-Networking:rx-android-networking:1.0.4")
```
