### ISSUE TITLE
Failed to resolve: com.amitshekhar.android:jackson-android-networking:1.0.4 or 1.0.2

### ISSUE THREAD

**Issue by rakeshrohilla** [amitshekhariitbhu/Fast-Android-Networking#609]
I have installed Android Studio Ladybug
Gradle version - 8.9
Gradle plugin version - 8.2.2

I have added these in build.gradle (project -level):
repositories {
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/ksoap2-android-releases"}
        google()
        maven { url "https://jitpack.io"}
    }

But after all, I am getting this error:
Failed to resolve: com.amitshekhar.android:jackson-android-networking:1.0.4

Please help. Attaching the screenshot as well
![Screenshot 2024-10-22 180901](https://github.com/user-attachments/assets/1d6d3598-38d0-4e2b-a536-2973e4db4527)

**Comment by amitshekhariitbhu** [comment]
@rakeshrohilla I hope this is resolved.

**Comment by Ak129** [comment]
how its resolve

**Comment by amitshekhariitbhu** [comment]
@Ak129 Please check: https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/607
