### ISSUE TITLE
Problem with priorities and async request

### ISSUE THREAD

**Issue by xino12** [amitshekhariitbhu/Fast-Android-Networking#61]
Post request with priority HIGH not being executed immediately.

They are executed after another request is executed.

Here is the code:
```

AndroidNetworking.post(nc.api_endpoint + nc.getPath("login"))
                    .addBodyParameter("grant_type", "convert_token")
                    .setPriority(Priority.HIGH)
                    .build()
                    .getAsString(new StringRequestListener() {
                        @Override
                        public void onResponse(String response) {
                            try {

                            } catch (JSONException e) {
                                e.printStackTrace();
                            }

                        }

                        @Override
                        public void onError(ANError error) {
                            // handle error
                            Log.d("ERROR", error.getResponse() + error.getErrorBody());
                        }
                    });

```
And if I try this: https://amitshekhariitbhu.github.io/Fast-Android-Networking/synchronous_request.html

The app gets stucked.

Thanks.

**Comment by amitshekhariitbhu** [comment]
@xino12 I will check the issue. The second example that you have tried is the synchronous request. The synchronous request must be called from the background thread.

**Comment by xino12** [comment]
Have you been able to reproduce this behaviour?
I've tried with IMMEDIATE and it's also not doing the request immediately.

`D/AndroidNetworking:` addRequest: after addition - mCurrentRequests size: 1
D/AndroidNetworking: execution started : ANRequest{sequenceNumber='14, mMethod=1, mPriority=IMMEDIATE, mRequestType=0, mUrl=
/AndroidNetworking: execution started : ANRequest{sequenceNumber='15, mMethod=0, mPriority=LOW, mRequestType=0, mUrl=https://climboapp.vdedalt.info/api/gyms/}
D/AndroidNetworking: addRequest: after addition - mCurrentRequests size: 3
D/AndroidNetworking: execution started : ANRequest{sequenceNumber='16, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/angry-rogester.png}
D/AndroidNetworking: addRequest: after addition - mCurrentRequests size: 4
D/AndroidNetworking: execution started : ANRequest{sequenceNumber='17, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/gym2-logo.png}
D/AndroidNetworking: addRequest: after addition - mCurrentRequests size: 5
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='16, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/angry-rogester.png}
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='16, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/angry-rogester.png}
D/AndroidNetworking: execution started : ANRequest{sequenceNumber='18, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/gym1-logo.jpg}
D/AndroidNetworking: addRequest: after addition - mCurrentRequests size: 6
D/AndroidNetworking: execution started : ANRequest{sequenceNumber='19, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/deudits-logo.png}
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='18, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/gym1-logo.jpg}
D/AndroidNetworking: addRequest: after addition - mCurrentRequests size: 7
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='18, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/gym1-logo.jpg}
D/AndroidNetworking: execution started : ANRequest{sequenceNumber='20, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/coolclimbs.png}
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='17, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/gym2-logo.png}
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='17, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/gym2-logo.png}
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='20, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/coolclimbs.png}
D/AndroidNetworking: finish: after removal - mCurrentRequests size: 6
D/AndroidNetworking: finish: after removal - mCurrentRequests size: 5
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='20, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/coolclimbs.png}
I/art: Background sticky concurrent mark sweep GC freed 15796(1073KB) AllocSpace objects, 1(44KB) LOS objects, 0% free, 12MB/12MB, paused 5.033ms total 25.360ms
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='15, mMethod=0, mPriority=LOW, mRequestType=0, mUrl=https://climboapp.vdedalt.info/api/gyms/}
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='15, mMethod=0, mPriority=LOW, mRequestType=0, mUrl=https://climboapp.vdedalt.info/api/gyms/}
D/AndroidNetworking: finish: after removal - mCurrentRequests size: 4
D/AndroidNetworking: finish: after removal - mCurrentRequests size: 3
D/AndroidNetworking: finish: after removal - mCurrentRequests size: 2
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='19, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/deudits-logo.png}
D/AndroidNetworking: finish: after removal - mCurrentRequests size: 1
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='19, mMethod=0, mPriority=MEDIUM, mRequestType=0, mUrl=https://climboapp.vdedalt.info/media/deudits-logo.png}
D/AndroidNetworking: Delivering success : ANRequest{sequenceNumber='14, mMethod=1, mPriority=IMMEDIATE, mRequestType=0, mUrl=https://climboapp.vdedalt.info/auth/token/}
D/AndroidNetworking: execution done : ANRequest{sequenceNumber='14, mMethod=1, mPriority=IMMEDIATE, mRequestType=0, `mUrl=https://climboapp.vdedalt.info/auth/token/}`

**Comment by xino12** [comment]
@amitshekhariitbhu At least as a workaround could you please tell me if there is a way to set the Threadpool to 1 except than 3 so requests that alter the UI are done immediately?

Thanks Amit.

**Comment by amitshekhariitbhu** [comment]
Please share your code snippet. I am not able to understand why the request is not firing immediately.

**Comment by xino12** [comment]
@amitshekhariitbhu Here you have.
```
        NetworkController nc = new NetworkController();
        AndroidNetworking.post(nc.api_endpoint + path)
                .addHeaders("Authorization", "Bearer " + userLocalStorage.getToken())
                .addJSONObjectBody(data)
                .setPriority(Priority.IMMEDIATE)
                .build()
                .getAsString(new StringRequestListener() {
                    @Override
                    public void onResponse(String response) {
                        // do anything with response
                        Log.d("NETWORK", "GET REQUEST " + response);
                        System.out.println("NETWORK" + response);
                    }

                    @Override
                    public void onError(ANError error) {
                        // handle error
                        Log.d("NETWORK", error.toString());
                        System.out.println("NETWORK" + error.getErrorBody());
                        Log.d("NETWORK", "ERROR GET REQUEST");
                    }
                });
```

**Comment by amitshekhariitbhu** [comment]
@xino12 are you not getting the response ?

**Comment by xino12** [comment]
@amitshekhariitbhu So the problem is that I need the response immediately because I need that response to update the UI and that is why I've used the IMMEDIATE priority thinking that this priority should execute the request immediately but what happens is that this request is getting queued as it was any other request and until I execute 2 more requests(so the threadpool then it's full)  the request is not executed and then I get the response.

After I add the 2 additional request I get the response to all 3 requests but I making 2 dummy requests in order to get the response that I need to update the UI immediately.

**Comment by amitshekhariitbhu** [comment]
@xino12 Now I got what u are telling, I will check it now and update u.

**Comment by amitshekhariitbhu** [comment]
For me it is working perfectly, can u try this with my API

```
AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                .setTag(this)
                .addPathParameter("pageNumber", "0")
                .addQueryParameter("limit", "3")
                .setPriority(Priority.IMMEDIATE)
                .build()
                .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                        Log.d(TAG, "onResponse array : " + response.toString());
                    }

                    @Override
                    public void onError(ANError error) {
                        if (error.getErrorCode() != 0) {
                            // received ANError from server
                            // error.getErrorCode() - the ANError code from server
                            // error.getErrorBody() - the ANError body from server
                            // error.getErrorDetail() - just a ANError detail
                            Log.d(TAG, "onError errorCode : " + error.getErrorCode());
                            Log.d(TAG, "onError errorBody : " + error.getErrorBody());
                            Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
                        } else {
                            // error.getErrorDetail() : connectionError, parseError, requestCancelledError
                            Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
                        }
                    }
                });
```

**Comment by xino12** [comment]
This is working correctly, only puts and posts are not being triggered immediately.

**Comment by xino12** [comment]
this api is working correctly only posts and puts are mot being triggered
immediately.

On Dec 13, 2016 08:09, "AMIT SHEKHAR" <notifications@github.com> wrote:

For me it is working perfectly, can u try this with my API

AndroidNetworking.get("https://fierce-cove-29863.herokuapp.com/getAllUsers/{pageNumber}")
                .setTag(this)
                .addPathParameter("pageNumber", "0")
                .addQueryParameter("limit", "3")
                .setPriority(Priority.IMMEDIATE)
                .build()
                .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                        Log.d(TAG, "onResponse array : " + response.toString());
                    }

                    @Override
                    public void onError(ANError error) {
                        if (error.getErrorCode() != 0) {
                            // received ANError from server
                            // error.getErrorCode() - the ANError code
from server
                            // error.getErrorBody() - the ANError body
from server
                            // error.getErrorDetail() - just a ANError detail
                            Log.d(TAG, "onError errorCode : " +
error.getErrorCode());
                            Log.d(TAG, "onError errorBody : " +
error.getErrorBody());
                            Log.d(TAG, "onError errorDetail : " +
error.getErrorDetail());
                        } else {
                            // error.getErrorDetail() :
connectionError, parseError, requestCancelledError
                            Log.d(TAG, "onError errorDetail : " +
error.getErrorDetail());
                        }
                    }
                });

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/61#issuecomment-266663635>,
or mute the thread
