### ISSUE TITLE
Is Gzipinterceptor working correctly

### ISSUE THREAD

**Issue by hiteshrawat** [amitshekhariitbhu/Fast-Android-Networking#62]
Server not returning "content-encoding:gzip" header in response.

when i add custom header "accept-encoding:gzip" without using gzipinterceptor   in request then the response returns "content-encoding" header but the response text is not readable.

Please suggest a working code to get gzip parsed response

**Comment by amitshekhariitbhu** [comment]
Have u configured your server for GZIP ?

**Comment by hiteshrawat** [comment]
actually it is not my server.
but when i used online gzip checker tool it says its enabled.
server is "www.frendz4m.com/forum"
also i ve tested it by sending request header "accept-encoding" it returns gzip content

**Comment by amitshekhariitbhu** [comment]
By default, If response it coming with GZIP encoding, it handle it automatically. But when we send from client to the server, it must be handled by the server when you add GZIP interceptor.

**Comment by hiteshrawat** [comment]
is there any code to unzip gzip string response?

**Comment by amitshekhariitbhu** [comment]
Check http://stackoverflow.com/questions/3621750/decompress-gzip-string-in-java

**Comment by hiteshrawat** [comment]
thank you Amit
