### ISSUE TITLE
Upload image with "PUT" method

### ISSUE THREAD

**Issue by javiersamaniego** [amitshekhariitbhu/Fast-Android-Networking#63]
Hi!

Do you know how I can upload an image from "PUT" method and "form-data" Content-Type. I have to send the image to a parameter "item[picture]" with ruby on rails.

But I get the 500 Server Error - error code 

Thanks!

**Comment by amitshekhariitbhu** [comment]
can u give me the sample that u tried now ?

**Comment by deveshbhandari** [comment]
same issue my side how to upload using Put data

**Comment by fahmisdk6** [comment]
So, how do we upload image using 'PUT' method with this library?
