### ISSUE TITLE
how to user jackson parse

### ISSUE THREAD

**Issue by littlezan** [amitshekhariitbhu/Fast-Android-Networking#64]
![image](https://cloud.githubusercontent.com/assets/5358278/21168961/00df1040-c1f3-11e6-8496-15a920f02a2f.png)

only Gson type？

thanks

**Comment by amitshekhariitbhu** [comment]
in your Gradle, write these two lines also

```
compile 'com.amitshekhar.android:jackson-android-networking:0.3.0'
// Then set the JacksonParserFactory like below
AndroidNetworking.setParserFactory(new JacksonParserFactory());
```

**Comment by littlezan** [comment]
if parse valid json is ok, but  when parsing invalid json with dynamic key has error.

the invalid json like this, copy from:
[parsing JSON containing an array of objects and array of maps w/ dynamic keys](http://stackoverflow.com/questions/17904845/jackson-parsing-json-containing-an-array-of-objects-and-array-of-maps-w-dynamic)

mine real json almost like it.
```
{

    "users":{
           "1234":{
                 "firstname":"Joe",
                 "lastname":"Smith"
           },
           "9876":{
                 "firstname":"Bob",
                 "lastname":"Anderson"
           }
    },
    "jobs":[
          {
              "id":"abc",
              "location":"store"
          },
          {
              "id":"def",
              "location":"factory"
          }
    ]
}
```


MyCustomClass.java

 ```
public class MyCustomClass {
    @JsonProperty("users")
    public LinkedHashMap<String, User> users;

    @JsonProperty("jobs")
    public ArrayList<Job> jobs;
}
```

```
 RxAndroidNetworking.get(LIVE_CATEGORY_HOT_LIST)
                .addQueryParameter(queryMap)
                .build()
                .getParseObservable(new TypeToken<MyCustomClass>() {
                });
```
then throw error
```
com.androidnetworking.error.ANError: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field...
```

when I get String result from net by RxAndroidNetworking.getStringObservable(), parse by Jackson ,is ok
```
 ObjectMapper mapper = new ObjectMapper();
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        try {
            return mapper.readValue(jsonResult, MyCustomClass.class);
        } catch (IOException e) {
            e.printStackTrace();
        }
```

sorry for my pool English, hope you can understand~

Thanks
littlezan

**Comment by amitshekhariitbhu** [comment]
```
ObjectMapper mapper = new ObjectMapper();
mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
```
If you are using mapper.disable(), you can pass custom ObjectMapper while passing 

`AndroidNetworking.setParserFactory(new JacksonParserFactory(mapper));
`

**Comment by littlezan** [comment]
It's works good.
Thinks

**Comment by hirenpatel868** [comment]
by using which method we can get response using jackson parsing

**Comment by amitshekhariitbhu** [comment]
@hirenpatel868 You can use `getAsObject`
