### ISSUE TITLE
I want to  create two different requests but only the get as JSon response works 

### ISSUE THREAD

**Issue by Adeyiwunmi** [amitshekhariitbhu/Fast-Android-Networking#66]
i want to create two different android networking request in one activity. i dont know how to go about it @amitshekhariitbhu ```
`public class VolleyActivity extends AppCompatActivity {

    String server_url = "http://api.androidhive.info/volley/person_object.json";
    private Button btn, btn2;
    private TextView text;
private ProgressDialog pdialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_volley);
       AndroidNetworking.initialize(getApplicationContext());

        btn = (Button) findViewById(R.id.bn);btn2 = (Button) findViewById(R.id.button);

         pdialog = new ProgressDialog(this); pdialog.setTitle("please wait ");
        pdialog.setCancelable(false);
        text = (TextView) findViewById(R.id.txt);
       btn.setOnClickListener(new View.OnClickListener() {
           @Override
           public void onClick(View v) {

               makeReq();
           }
       });

        btn2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                makearry();

            }
        });

}
public void makeReq(){
    AndroidNetworking.get(server_url)
            .setTag("first request")
            .setPriority(Priority.HIGH)
            .build()
            .getAsJSONObject(new JSONObjectRequestListener() {
                @Override
                public void onResponse(JSONObject response) {
                    try {
                        String name = response.getString("name"); String email = response.getString("email");
                        JSONObject phone = response.getJSONObject("phone");
                        String mobile = phone.getString("mobile");
                        String home = phone.getString("home");
                        String resspone = "Name : " + name + "\n"
                                + "Email:  " + email + "\n"
                                + "Mobile Phone Number:  " + mobile + "\n"
                                + "Home Phone Number   " + home + "\n";

                        text.setText(resspone);
                        pdialog.hide();
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }

                }

                @Override
                public void onError(ANError anError) {
                    text.setText(anError.toString());
                }
            });

}

    public void makearry(){
        AndroidNetworking.initialize(getApplicationContext());
        AndroidNetworking.get("http://api.androidhive.info/volley/person_array.json")
                .setTag("array req")
                .setPriority(Priority.HIGH)
                .build()
                .getAsJSONArray(new JSONArrayRequestListener() {
            @Override
            public void onResponse(JSONArray response) {

                try {
                    JSONObject person1 = (JSONObject) response.get(1);
                    String name1 = person1.getString("name"); String email1 = person1.getString("email");
                    JSONObject phone = person1.getJSONObject("phone");
                    String mobile1 = phone.getString("mobile");
                    String home1 = phone.getString("home");
                    String response1=  "Name : " + name1 + "\n"
                            + "Email:  " + email1 + "\n"
                            + "Mobile Phone Number:  " + mobile1 + "\n"
                            + "Home Phone Number   " + home1 + "\n";
                        JSONObject person2 = (JSONObject) response.get(2);
                    String name2 = person2.getString("name"); String email2 = person2.getString("email");
                    JSONObject phone2 = person2.getJSONObject("phone");
                    String mobile2 = phone2.getString("mobile");
                    String home2 = phone2.getString("home");
                    String response2=  "Name : " + name2 + "\n"
                            + "Email:  " + email2 + "\n"
                            + "Mobile Phone Number:  " + mobile2 + "\n"
                            + "Home Phone Number   " + home2 + "\n";
String totalresposne = "Person 1: " + "\n" + response1 + "\n"
                   + "Person 2:    "  + "\n" + response2 ;
                    text.setText(totalresposne);
                        pdialog.hide();

                } catch (JSONException e) {
                    e.printStackTrace();
                }

            }

            @Override
            public void onError(ANError anError) {
anError.printStackTrace();
            }
        });

    }
}`
```

**Comment by amitshekhariitbhu** [comment]
There is no need to initialize it two times `AndroidNetworking.initialize(getApplicationContext());`

**Comment by amitshekhariitbhu** [comment]
It is working for me.

**Comment by Adeyiwunmi** [comment]
wasnt getting error, the button just didnt work, i found the mistake, i used the wrong array index.  in  `JsonObject phone = (JsonObject) reponse.get(1)`  its means to be  `JsonObject phone = (JsonObject) reponse.get(0) 
   and so on 
my array index started from 1 instead of 0.  i have corrected it thanks .

**Comment by amitshekhariitbhu** [comment]
ok
