### ISSUE TITLE
AndroidNetworking depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by DeveloperMCD** [amitshekhariitbhu/Fast-Android-Networking#67]
Why am I getting this error?

    compile fileTree(dir: 'libs', include: '*.jar')
    compile fileTree(dir: "$buildDir/native-libs", include: 'native-libs.jar')
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.squareup.okio:okio:1.11.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.github.amitshekhariitbhu:AndroidNetworking:v0.3.0'

    compile ('com.github.asne.facebook:facebook:3.15.0')
            {
                exclude module: 'support-v4'
            }
    compile('com.crashlytics.sdk.android:crashlytics:2.1.0@aar') {
        transitive = true;
    }

I also tried

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile fileTree(dir: "$buildDir/native-libs", include: 'native-libs.jar')
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.squareup.okio:okio:1.11.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.github.amitshekhariitbhu:AndroidNetworking:v0.3.0@aar'

    compile ('com.github.asne.facebook:facebook:3.15.0')
            {
                exclude module: 'support-v4'
            }
    compile('com.crashlytics.sdk.android:crashlytics:2.1.0@aar') {
        transitive = true;
    }
}

**Comment by amitshekhariitbhu** [comment]
Remove that and use this 
compile 'com.amitshekhar.android:android-networking:0.3.0'

**Comment by DeveloperMCD** [comment]
Error:(48, 13) Failed to resolve:
      com.amitshekhar.android:android-networking:0.3.0
      
      <a href="openFile:/home/matthew/dev/java/build.gradle">Show
      in File</a><br>
      <a href="open.dependency.in.project.structure">Show in
      Project Structure dialog</a>
      
      On 12/17/2016 11:39 PM, AMIT SHEKHAR wrote:
    
    
      Remove that and use this
        compile 'com.amitshekhar.android:android-networking:0.3.0'
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/amitshekhariitbhu/Fast-Android-Networking","title":"amitshekhariitbhu/Fast-Android-Networking","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/amitshekhariitbhu/Fast-Android-Networking"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amitshekhariitbhu in #67: Remove that and use this \r\ncompile 'com.amitshekhar.android:android-networking:0.3.0'"}],"action":{"name":"View Issue","url":"https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/67#issuecomment-267804630"}}}
