### ISSUE TITLE
Consume response before closing it for prefetch

### ISSUE THREAD

**Issue by modislaszlox2** [amitshekhariitbhu/Fast-Android-Networking#69]
InternalRunnable.executeSimpleRequest should call **response.body().source().skip(Long.MAX_VALUE)** for prefetch request before calling close. Close will timeout for larger content/slower networks.

The call could be added to ANRequest.parseResponse also.

**Comment by modislaszlox2** [comment]
Created a pull request with the change: https://github.com/amitshekhariitbhu/Fast-Android-Networking/pull/70

**Comment by modislaszlox2** [comment]
@amitshekhariitbhu any chance you can merge it today? I need the fix myself.

**Comment by amitshekhariitbhu** [comment]
@modislaszlox2 your code is correct, right now we are planning to release the new version on upcoming Sunday. As of now, you can use your forked code.

Thanks
Amit Shekhar
