### ISSUE TITLE
Add support for Jackson

### ISSUE THREAD

**Issue by jotaemepereira** [amitshekhariitbhu/Fast-Android-Networking#7]
Add support for Jackson converter to Android-Networking

**Comment by amitshekhariitbhu** [comment]
@jotaemepereira : As of now, we have added the GSON as a default parser. In upcoming release we will make it more modular so that Jackson can be used.

**Comment by amitshekhariitbhu** [comment]
@jotaemepereira : Jackson Support is added 
 ```
        compile 'com.amitshekhar.android:jackson-android-networking:0.2.0'
        AndroidNetworking.initialize(getApplicationContext());
        AndroidNetworking.setParserFactory(new JacksonParserFactory());
```
