### ISSUE TITLE
TypeToken not working

### ISSUE THREAD

**Issue by tallaltasawar** [amitshekhariitbhu/Fast-Android-Networking#71]
Hi, 

Its a great effort and I really appreciate that, I was having issues in auto mapping feature using TypeToken<MyClass> as Parsed Response but I dont get anything no error no response. like so 

AndroidNetworking.post(API.END_POINT+API.LOGIN_ACTION)
                .addHeaders("Accept","application/json")
                .addHeaders("Content-Type","application/x-www-form-urlencoded")
                .addStringBody(request)
                .build()
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                        try {
                            secretToken = response.getString("access_token");
                            Log.i("onResponse: ",secretToken);
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }
                    }

                    @Override
                    public void onError(ANError anError) {
                        Log.e("onError: ",anError.getMessage() );
                    }
                });

**Comment by amitshekhariitbhu** [comment]
Where are u using getAsParsed()?
