### ISSUE TITLE
Error:Failed to resolve: com.squareup.okhttp3:okhttp:3.2.0

### ISSUE THREAD

**Issue by IkechukwuAKalu** [amitshekhariitbhu/Fast-Android-Networking#76]
Hello, I am getting this error "Error:Failed to resolve: com.squareup.okhttp3:okhttp:3.2.0" while trying to compile this repo in my app. Any help is appreciated. Thanks.

**Comment by amitshekhariitbhu** [comment]
Can u share the code, as this error should not come?

**Comment by IkechukwuAKalu** [comment]
![capture](https://cloud.githubusercontent.com/assets/25153373/21986746/f354f6b0-dc00-11e6-8cab-e9fe00a01129.PNG)

I haven't added any code to it. It occurred when building the project after adding the depenency

**Comment by amitshekhariitbhu** [comment]
Once try by updating the version to 0.3.0

**Comment by amitshekhariitbhu** [comment]
and also refer 
http://stackoverflow.com/questions/36269340/error28-13-failed-to-resolve-com-squareup-okhttp3okhttp3-2-0
