### ISSUE TITLE
Cancel or ForceCancel not working

### ISSUE THREAD

**Issue by heitorzc** [amitshekhariitbhu/Fast-Android-Networking#78]
Hi there,

First of all, I would like to compliment you for your great work with this library. =)

Everything works perfectly and smoothly, except for one thing...
I'm trying to cancel a request by calling `forceCancel()` or `forceCancelAll()` but no luck here. =/
This is how I am sending my request:

```
return RxAndroidNetworking.get(BASE_URL + GET_REPOS_URL)
                .addPathParameter("username", username)
                .setPriority(Priority.HIGH)
                .build()
                .getParseObservable(new TypeToken<ArrayList<GithubRepository>>() {});
```

I also tried setting a tag for each request via `.setTag("tag")` and then canceling via `.forceCancel(tag)` but I didn't work either.

Any clue of what's going on?

Thanks a million.

**Comment by amitshekhariitbhu** [comment]
Thank you so much, The issue is that when you use RXAndroidNetworking instead of AndroidNetworking, you have to cancel it using Subscription. Refer the link
https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/rxsampleapp/src/main/java/com/rxsampleapp/SubscriptionActivity.java

**Comment by Jendorski** [comment]
Is it possible to say that in rxJava2, the best way to cancel a network operation is to use the CompositeDisposable#clear(); ?
