### ISSUE TITLE
Image download hangs UI

### ISSUE THREAD

**Issue by AndroidHitchhiking** [amitshekhariitbhu/Fast-Android-Networking#8]
Image download working in main thread and it cause the hang of UI When showing the list of user with their profile images.
It must be like Glide or Picasso.

Let me know if I am wrong or I have to use any other/extra code for doing so.
Currently I am doing code as below....and showing in recyclerview using adapter.

```
public static void loadImageDirect(final String url, final ImageView img, final String TAG) {
        NetworkingBase.get(url)
                .setTag("imageRequestTag")
                .setPriority(Priority.MEDIUM)
                .setImageScaleType(null)
                .setBitmapMaxHeight(0)
                .setBitmapMaxWidth(0)
                .setBitmapConfig(Bitmap.Config.ARGB_8888)
                .build()
                .setAnalyticsListener(new AnalyticsListener() {
                    @Override
                    public void onReceived(long timeTakenInMillis, long bytesSent, long bytesReceived, boolean isFromCache) {
                        Log.d(TAG, " timeTakenInMillis : " + timeTakenInMillis);
                        Log.d(TAG, " bytesSent : " + bytesSent);
                        Log.d(TAG, " bytesReceived : " + bytesReceived);
                        Log.d(TAG, " isFromCache : " + isFromCache);
                    }
                })
                .getAsBitmap(new BitmapRequestListener() {
                    @Override
                    public void onResponse(final Bitmap response) {
                        Log.d(TAG, "onResponse Bitmap");
                                img.setImageBitmap(response);
                    }

                    @Override
                    public void onError(LibError error) {
                        if (error.getErrorCode() != 0) {

                            Log.d(TAG, "onError errorCode : " + error.getErrorCode());
                            Log.d(TAG, "onError errorBody : " + error.getErrorBody());
                            Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
                        } else {
                            // error.getErrorDetail() : connectionError, parseError, requestCancelledError
                            Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
                        }
                    }
                });
    }
```

and calling this loadImageDirect(...) method from adapter.

**Comment by amitshekhariitbhu** [comment]
@AndroidHitchhiking 
Instead of using this direct in an adapter, Using this will solve your problem.

```
<com.androidnetworking.widget.ANImageView
          android:id="@+id/img"
          android:layout_width="100dp"
          android:layout_height="100dp"
          android:layout_gravity="center" />
```
and call this in adapter .

   ```
      img.setDefaultImageResId(R.drawable.default);
      img.setErrorImageResId(R.drawable.error);
      img.setImageUrl(imageUrl);
```          

As this uses memcache and proper canceling of request when user scroll the view.

And the problem that you are getting is because of the continuous decoding of bitmap as there is no cancelation and no bitmap caching in memcache. So use the above code.

Glide use a bitmap pool concept that we are going to implement it here. You can read more about that [here](https://medium.freecodecamp.com/how-to-use-bitmap-pool-in-android-56c71a55533c#.c9genklsy) 

Anyway as you told, it must be like glide or picasso. We will add it in future upcoming release. It will be great if anybody will help me do it fast as soon as possible.

**Comment by mupm1** [comment]
- can i use , like Picasso ? or "com.androidnetworking.widget.ANImageView" Circular?
Picasso.with(mContext).load(item.getImage())
                .placeholder(R.drawable.shopping_bag)
                .error(R.drawable.shopping_bag)
                .centerCrop()
                .fit()
                .into(holder.imgShop);

**Comment by amitshekhariitbhu** [comment]
@mupm1 The best library for Image loading is Glide.

**Comment by mupm1** [comment]
@amitshekhariitbhu can you speake persian?
