### ISSUE TITLE
Error while return 304 but no cache stored

### ISSUE THREAD

**Issue by mindfreak269** [amitshekhariitbhu/Fast-Android-Networking#80]
i have server cache, and if server cache created it will return 304, but if my Application initial for first time and request API, so if server return 304 and no app local cache, it give me null error, how i can tell server it first time request from device?

**Comment by amitshekhariitbhu** [comment]
How can your server return 304 when no cache is stored?

**Comment by mindfreak269** [comment]
sorry my bad, it self make cache in server, i have been fixed , by match HTTP_IF_NONE_MATCH and hash data of server cache, the problem is in my backend. 
i confused because im using Fiddler to monitor request, in fiddler 304 will be return with body, but okhttp will not allowed, solution is add another verification with IF NONE MATCH , and it solved it.

^_^
