### ISSUE TITLE
.Jar file

### ISSUE THREAD

**Issue by sucklifex** [amitshekhariitbhu/Fast-Android-Networking#82]
First, Thank you for your awesome library.
Because of country restrict, i cannot use gradle,
So, if you put your project in maven or upload a .jar file would be great

**Comment by amitshekhariitbhu** [comment]
@sucklifex ... I will update you soon on this.

**Comment by Reza-77** [comment]
hello, Thank you for very comfortable library. it is so easy to use.

**Comment by amitshekhariitbhu** [comment]
Not a requirement. So closing this issue. Please use it through gradle dependency.
