### ISSUE TITLE
in DefaultHttpClient there is  HttpEntity entity = new StringEntity("'"); what is alternative in Fast-Android-Networking

### ISSUE THREAD

**Issue by proAhmed** [amitshekhariitbhu/Fast-Android-Networking#84]
in DefaultHttpClient there is  HttpEntity entity = new StringEntity("'"); 
    httppost.setEntity(entity);
what is alternative in Fast-Android-Networking
can I use library as soap consumer or get response of soap as  string
or can I get soap as string

**Comment by amitshekhariitbhu** [comment]
You can do this with `addStringBody` and if your server accept application/atom+xml, you can also set that with setContentType("application/atom+xml; charset=utf-8")
There is one method `getAsString` to get as the string.

Thanks
Amit Shekhar
