### ISSUE TITLE
New Method "addMultipartFiles (String key, ArrayList<File>)"

### ISSUE THREAD

**Issue by PedroMobile** [amitshekhariitbhu/Fast-Android-Networking#85]
How can I do something like :

.addMultipartFiles (String key, ArrayList<File>) ;

**Comment by amitshekhariitbhu** [comment]
How can you send multiple files with the same key?

**Comment by amitshekhariitbhu** [comment]
I will explore it and add it in the upcoming release.

**Comment by singhdd93** [comment]
Hope this is coming soon. I really needed it today.
But I used upload with map function. It made my server side complex.

**Comment by amitshekhariitbhu** [comment]
@singhdd93 Sure I will add it soon, need help from your side for reviewing it. I will ask when I add it.

**Comment by JasperSenpai** [comment]
Hi @amitshekhariitbhu have u already added this features? i need it badly it would be great if u have it. if not how can i do that like approach

**Comment by amitshekhariitbhu** [comment]
@JasperSenpai We also need a API for testing this. I mean to say endpoint which support this.

**Comment by nirzonpop192** [comment]
Does this feature added now ???
