### ISSUE TITLE
Network on main thread

### ISSUE THREAD

**Issue by mohsin1122** [amitshekhariitbhu/Fast-Android-Networking#86]
hi,
i am using the below code to get synchronous call, but got network on main thread error

> ANRequest request = AndroidNetworking.get(getResources().getString(R.string.server_url_user_mgmt_services) + "GetUserAuthorizationToken?eload_number={eloadnum}")
                    .addHeaders("Content-Type", "application/json")
                    .addHeaders("Authorization", CommonMethods.getSecurityHeader(OTP.this))
                    .addPathParameter("eloadnum", user.getUserIdentifier())
                    .build();
            ANResponse<JSONObject> response = request.executeForParsed(new TypeToken<JSONObject>() {});
            if (response.isSuccess()) {
                JSONObject obj = response.getResult();
                try {
                    boolean isValidUser = obj.getBoolean("isSuccessful");
                    if (isValidUser) {
                        if (!obj.getString("Token").isEmpty()) {
                            randomString = obj.getString("Token");
                        }
                        else
                        {
                            randomString = null;
                        }
                    }
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            } else {
                ANError error = response.getError();
                // Handle Error
                Toast.makeText(OTP.this, "Some error occured!\nTry Again", Toast.LENGTH_SHORT).show();
            }

**Comment by amitshekhariitbhu** [comment]
You must make synchronous call from background thread.

**Comment by mohsin1122** [comment]
isnt that the Async Request?
```
AndroidNetworking.post("https://fierce-cove-29863.herokuapp.com/createAnUser")
                 .addBodyParameter("firstname", "Amit")
                 .addBodyParameter("lastname", "Shekhar")
                 .setTag("test")
                 .setPriority(Priority.MEDIUM)
                 .build()
                 .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                      // do anything with response
                    }
                    @Override
                    public void onError(ANError error) {
                      // handle error
                    }
                });
```

**Comment by amitshekhariitbhu** [comment]
This will do the network task in the background and return the response in the main thread. However, you can also get the response in another thread of your choice by using `setExecutor`

**Comment by mohsin1122** [comment]
i am getting this error when i generate signed apk with obfuscated code with proguard
java.lang.IllegalArgumentException: class com.traker.dms.app.b.c  declares multiple JSON fields named a

**Comment by mohsin1122** [comment]
is there a way for SSL Pinning in AFN?

**Comment by amitshekhariitbhu** [comment]
@mohsin1122 As FAN is built on OkHttp Layer, you can definitely pass custom OkHttpClient while initializing it.

**Comment by mohsin1122** [comment]
i tried by this way but it is not showing errors as the sha key is incorrect
```
String hostname = "https://publicobject.com";
        CertificatePinner certificatePinner = new CertificatePinner.Builder()
                .add(hostname, "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
                .build();
        OkHttpClient client = new OkHttpClient().newBuilder().certificatePinner(certificatePinner).build();

        //initialize fastnetwork android for api calls
        AndroidNetworking.initialize(getApplicationContext(),client);
```

also try this way but still it gets the response for WS
```
String hostname = "https://publicobject.com";
        CertificatePinner certificatePinner = new CertificatePinner.Builder()
                .add(hostname, "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
                .build();
        OkHttpClient client = new OkHttpClient().newBuilder().certificatePinner(certificatePinner).build();

AndroidNetworking.post(getResources().getString(R.string.server_url_user_mgmt_services) + "GetUserDetails")
                    .setOkHttpClient(client)
                    .addHeaders("Content-Type", "application/json")
                    .addHeaders("Authorization", CommonMethods.getSecurityHeader(LoginActivity.this))
                    .addJSONObjectBody(json)
                    .setPriority(Priority.HIGH)
                    .build()
                    .setAnalyticsListener(new AnalyticsListener() {
                        @Override
                        public void onReceived(long timeTakenInMillis, long bytesSent, long bytesReceived, boolean isFromCache) {
                            Log.d("", " timeTakenInMillis : " + timeTakenInMillis);
                            Log.d("", " bytesSent : " + bytesSent);
                            Log.d("", " bytesReceived : " + bytesReceived);
                            Log.d("", " isFromCache : " + isFromCache);
                        }
                    })
                    .getAsJSONObject(new JSONObjectRequestListener() {
                        @Override
                        public void onResponse(JSONObject response) {
                            
                        }

                        @Override
                        public void onError(ANError anError) {
                           
                        }
                    });
```

**Comment by amitshekhariitbhu** [comment]
@mohsin1122 without the url how can I debug?

**Comment by mohsin1122** [comment]
@amitshekhariitbhu https://apollo.telenor.com.pk/

**Comment by amitshekhariitbhu** [comment]
@mohsin1122 I am getting server error.

**Comment by mohsin1122** [comment]
why?
complete url: 

> https://apollo.telenor.com.pk/UserManagement/UserManagement.svc/

**Comment by amitshekhariitbhu** [comment]
@mohsin1122 cannot help with little information. At least can tell me the exact error body you are getting. As the request is having many input like headers and JSON.

**Comment by mohsin1122** [comment]
@amitshekhariitbhu is there a way we can have chat?
coz i cant share the details publicly

**Comment by mohsin1122** [comment]
plz provide me the example how to implement ssl pinning using FAN.

**Comment by amitshekhariitbhu** [comment]
I will provide it as an example on website, I think there is some problem from your server side

**Comment by mohsin1122** [comment]
@amitshekhariitbhu thanks 
plz provide the example asap as i have deadlines to meet

**Comment by amitshekhariitbhu** [comment]
@mohsin1122 Have you tried your request from Postman (just for testing, is your server working).

**Comment by mohsin1122** [comment]
@amitshekhariitbhu bro server is working fine
it requires username and password to work but due to security reason i am unable to provide you that hope u understand.
plz create a demo to use ssl pining with FAN

**Comment by amitshekhariitbhu** [comment]
@mohsin1122 You are doing it right, but I do not why that is not working. Try putting the password like this

```
OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .certificatePinner(certificatePinner)
        .authenticator(new Authenticator() {
            @Override
            public Request authenticate(Route route, Response response) throws IOException {
                String credential = Credentials.basic("username", "password");
                return response.request().newBuilder()
                        .header("Authorization", credential)
                        .build();
            }
        })
        .build();
```

**Comment by mohsin1122** [comment]
the snippet u provide is working but still not validating the certificate(not giving any errors)

**Comment by mohsin1122** [comment]
**Resolved**
problem lie in this line
`String hostname = "https://publicobject.com"; `
hostname is **publicobject.com** https is not a part of hostname
