### ISSUE TITLE
how is it possible to listen on connection process ?

### ISSUE THREAD

**Issue by navotera** [amitshekhariitbhu/Fast-Android-Networking#87]
i cannot find any listener either for getAsString or getAsJsonArray when connection in process... ?
can u help me how can i do that to set some method when this library on connection process. thank

**Comment by amitshekhariitbhu** [comment]
As of now, this feature is not present, I will this in the upcoming release.

**Comment by navotera** [comment]
hope it would released soon... 💃

**Comment by amitshekhariitbhu** [comment]
Let the issue be opened, for discussion on implementation and tracking.
