### ISSUE TITLE
Head request

### ISSUE THREAD

**Issue by amervelic** [amitshekhariitbhu/Fast-Android-Networking#9]
I need example HEAD request. I tried this

  AndroidNetworking.head (BASE_URL)
                 .addQueryParameter ("username", username)
                 .addQueryParameter ("password", password)
                 .setPriority (Priority.MEDIUM)
                 .build ()
                 .getAsString (stringRequestListener);

But the response is an empty string.

**Comment by amitshekhariitbhu** [comment]
@amervelic : HEAD request is useful for retrieving meta-information written in response headers, without having to transport the entire content. So the response is empty. Any there is a bug that I will fix to expose the headers as a response in upcoming release. As of you can not get the headers as it is not exposed.

**Comment by amitshekhariitbhu** [comment]
@amervelic : fixed in development branch

**Comment by amitshekhariitbhu** [comment]
In version 0.1.0 there is no way to access headers from server. I have added it in version 0.2.0.
Version 0.2.0 has been released
'com.amitshekhar.android:android-networking:0.2.0'

The sample code is :

  ```
                 AndroidNetworking.head(url)
                            .build()
                            .getAsOkHttpResponse(new OkHttpResponseListener() {
                                @Override
                                public void onResponse(Response response) {
                                    Log.d(TAG, "Headers :" + response.headers());
                                }

                                @Override
                                public void onError(ANError anError) {
                                    //handle error
                                }
                            });
```
