### ISSUE TITLE
how to set, response data is  ResponsePageData<T>

### ISSUE THREAD

**Issue by wfxphoebus** [amitshekhariitbhu/Fast-Android-Networking#93]
` public class ResponsePageData<T> {
    private int ret;
    private String msg;
    PageInfo<T> data;
}`

**Comment by amitshekhariitbhu** [comment]
Can u please describe the problem in detail?

Thanks
Amit Shekhar

**Comment by wfxphoebus** [comment]
**Return JSON from server**：
{"ret":0,"msg":"suc","url":null,"data":{"pageNum":1,"pageSize":1,"size":1,"startRow":1,"endRow":1,"total":63,"pages":63,"list":[{"id":1,"page":1,"rows":10,"name":"1","age":"1","address":"123","date":"2017-02-15 09:38:25.0"}],"prePage":0,"nextPage":2,"isFirstPage":true,"isLastPage":false,"hasPreviousPage":false,"hasNextPage":true,"navigatePages":8}}

Local object：
public class ResponsePageData<T> { private int ret; private String msg; PageInfo<T> data; }


Do not know how to convert？

**Comment by amitshekhariitbhu** [comment]
Check https://amitshekhariitbhu.github.io/Fast-Android-Networking/get_request.html#getting-parsed-object-as-response

**Comment by wfxphoebus** [comment]
Can support generics，How to write？

**Comment by amitshekhariitbhu** [comment]
`getAsParsed(new TypeToken< ResponsePageData<T>>(){}.getType(), listener)`

**Comment by gziren** [comment]
I find this way, is what i need
```
public Single<ResponsePageData<LoginResponse>> doGoogleLoginApiCall(LoginRequest.GoogleLoginRequest
                                                              request) {

        return Rx2AndroidNetworking.post(ApiEndPoint.ENDPOINT_GOOGLE_LOGIN)
                .addHeaders(mApiHeader.getPublicApiHeader())
                .addBodyParameter(request)
                .build()
                .getParseSingle(new TypeToken<ResponsePageData<LoginResponse>>() {
                             });
    }
```
