### ISSUE TITLE
Request how to submit a list of data collection?I would like to submit a list of data but made a mistake

### ISSUE THREAD

**Issue by alitong** [amitshekhariitbhu/Fast-Android-Networking#98]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 53 path $.
at com.google.gson.Gson.fromJson(Gson.java:899)
at com.google.gson.Gson.fromJson(Gson.java:852)
at com.google.gson.Gson.fromJson(Gson.java:801)
at com.androidnetworking.gsonparserfactory.GsonParserFactory.getStringMap(GsonParserFactory.java:85)
at com.androidnetworking.common.ANRequest$PostRequestBuilder.addBodyParameter(ANRequest.java:1231)
this log ....

my request is {
@Expose
    @SerializedName("ids")
    private String ids	;
@Expose
    @SerializedName("data")
    private List<StoreInputData> mInputDatas  // This is list data .
}

**Comment by amitshekhariitbhu** [comment]
Define  YourObjectClass  in `List<YourObjectClass>` mInputDatas

**Comment by alitong** [comment]
thank you for your reply！
Definitely defined List<YourObjectClass> ，Can write a demo  ？ 
I use  .addBodyParameter(request)   post Request. The request is my Define Object

**Comment by amitshekhariitbhu** [comment]
- Can you write the request class that you have created and the JSON which is expected at the server?
- The other case can be that your server accepts `application/json`, so use `addApplicationJsonBody`

**Comment by alitong** [comment]
Haha, no problem, the request contains the collection data should be used  .addApplicationJsonBody .
thank you amitshekhariitbhu!

**Comment by amitshekhariitbhu** [comment]
Awesome.
