### ISSUE TITLE
Cache messing cart get request

### ISSUE THREAD

**Issue by japheth-waswa** [amitshekhariitbhu/Fast-Android-Networking#99]
Hellow iam building an App for magento using the XmlConnect Magento API,so far Fast-Android-Networking has been great but when fetching inserted cart contents,it returns cached response.How can i disable caching for the current request ?To get the latest data ?

**Comment by amitshekhariitbhu** [comment]
Refer https://amitshekhariitbhu.github.io/Fast-Android-Networking/caching.html#do-not-cache-response

**Comment by japheth-waswa** [comment]
Hello i have tried all that ie "doNotCacheResponse()"but still it returns the cached response.What can i do next please

**Comment by amitshekhariitbhu** [comment]
Once try getResponseOnlyFromNetwork method, there may a case that your server is returning cached data

**Comment by japheth-waswa** [comment]
ok cool.

**Comment by japheth-waswa** [comment]
thanks i have noticed it is a server issue.
